# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared_core/blueprint.md | §
# [MODULE] zephyr.shared.blueprint_tools.blueprint_scorer
# [DOMAIN] D_SHARED
# [DEPENDENCIES] zephyr.shared.__init__
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-SHR_blueprint_scorer | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] permanent

"""
blueprint_scorer.py — Re-export wrapper → canonical: zephyr.trading.orchestrator.blueprint_scorer

Backward-compatible top-level alias. Canonical implementation at orchestrator/blueprint_scorer.py.
Edit orchestrator/blueprint_scorer.py to modify logic — do NOT edit this file.
"""

import importlib

# Re-export shim — canonical: zephyr.trading.orchestrator.blueprint_scorer
_mod = importlib.import_module("zephyr.trading.orchestrator.blueprint_scorer")
for _name in getattr(_mod, "__all__", [n for n in dir(_mod) if not n.startswith("_")]):
    globals()[_name] = getattr(_mod, _name)
del _mod, _name
