# [BLUEPRINT] MOD-INF-016 | (auto-injected by S4 reconciler) | §
# [TTL] permanent
# [TTL] permanent
"""
Auto-generated contracts package — market

Generated by: scripts/governance/d5_architecture/generate_contracts.py

# [ALGO_FLOW] external: docs/03_modules/_domain_trading/algo_flow/market__init__.yaml
"""

from .signal_degradation_warning import SignalDegradationWarning

__all__ = [
    "signal_degradation_warning",
]
