# [TTL] permanent
"""
Auto-generated contracts package — market

Generated by: scripts/governance/d5_architecture/generate_contracts.py

# [ALGO_FLOW]
# 层: 输入
# - id: I1
#   name: 包内子模块公共符号
#   fields: import 再导出符号: SignalDegradationWarning
#   code: __init__.py import L34
# 层: 算法
# - id: A1
#   name_zh: ① 包公共面再导出
#   name_en: __init__ re-export
#   intro: 再导出 signal_degradation_warning（共 1 符号）
#   desc: __init__ import L34；__all__ 1 项（AST 事实）
#   inputs: I1
#   outputs: __all__ 公共符号表
# 层: 输出
# - id: O1
#   name_zh: 公共 API 面（1 符号）
#   name_en: __all__
#   intro: signal_degradation_warning
#   downstream: 见模块头 [CONSUMERS]
# [/ALGO_FLOW]
#
# 边:
# I1 --> A1
# A1 --> O1
"""

from .signal_degradation_warning import SignalDegradationWarning

__all__ = [
    "signal_degradation_warning",
]
