# [BLUEPRINT] MOD-INF-016 | (auto-injected by S4 reconciler) | §
# [TTL] permanent
"""
Auto-generated contracts package — market

Generated by: scripts/governance/d5_architecture/generate_contracts.py
"""

from .signal_degradation_warning import SignalDegradationWarning

__all__ = [
    "signal_degradation_warning",
]
