"""ZephyrAlpha Pipeline 模块 — M1-M11 双管线 + K8s Scheduling Framework + 跨层数据路由
A区（M1-M5）生产管线 + B区（M6-M11）审计管线。
GOV-AI-002 v2.0.0 决策树 + 插件化路由 + Agent 桥接 + Schema 校验。
v0.7.0: Phase C — LayerDataRouter 模型冻结与路由串联
v0.8.0: Phase D — LayerConsumerRegistry 全层消费者回调注册
"""

from zephyr.pipeline.models import (
    M_MODULE_SPECS,
    M_MODULES,
    A_DAG,
    B_DAG,
    ABExperimentRoute,
    AFFINITY_CONSTRAINTS,
    AffinityWeight,
    AIImpactAssessment,
    ArtifactClassification,
    ArtifactType,
    CircuitBreakerState,
    ClaudeRescueTrigger,
    CostRecord,
    DeadLetterEntry,
    EmergencyFallbackPlan,
    ExperimentVariant,
    GenericModuleOutput,
    M1ParseOutput,
    M3GenerateOutput,
    M6DiffOutput,
    M7ReviewOutput,
    M8ComplianceOutput,
    M9RiskOutput,
    M10ReportOutput,
    M11GatingOutput,
    ModelCollapseAlert,
    ModelConfidence,
    ModelVersionInfo,
    ModuleInput,
    ModuleResult,
    PipelineAffinityConstraint,
    PipelineArtifact,
    PipelineArtifactManifest,
    PipelineDAG,
    PipelineLineageChain,
    PipelineLineageEntry,
    PipelineOrchestratorConfig,
    PipelineResult,
    PipelineRouteDecision,
    PipelineStage,
    PipelineStatus,
    PreemptionRecord,
    StageContext,
    StageOnFailure,
    validate_module_output,
)
from zephyr.pipeline.pipeline_agent_bridge import (
    PipelineAgentBridge,
    M_TO_ROLE,
    role_for_module,
    domain_for_pipeline,
)
from zephyr.pipeline.pipeline_roadmap import (
    SLOMetric,
    ErrorBudget,
    SLOState,
    PolicyDiffReport,
    FaultInjectionSpec,
    ChaosExperimentResult,
    DegradationLevel,
    GoldenTestResult,
    HallucinationCheckResult,
    SessionBrief,
    HealthReport,
    PipelineOrchestratorRoadmapMixin,
    BlueprintCodeDriftEntry,
    DriftReport,
    BlueprintCodeDriftChecker,
    MutationTestResult,
    ROICalculator,
    OrchestratorIntegrationBridge,
    AdversarialDeceptionProtocol,
    AlertEscalationTracker,
    AntiPatternEntry,
    AuditIndependenceProof,
    ByzantineFailureCheck,
    CheckpointResumeState,
    CodebaseHealthScore,
    ConceptDriftMonitor,
    ConstructionPhaseTracker,
    CrossMarketGuard,
    CrossModuleSyncEntry,
    DataProvenanceTracker,
    DegradationTimeline,
    Dependency,
    DependencyHealthChecker,
    DependencyRotDetector,
    DeschedulerTaskState,
    DriftIntoFailureAlert,
    KillSwitchStatus,
    MannKendallResult,
    MarketDataPipelineStatus,
    ModelArbitrageResult,
    OutcomeBiasCheck,
    PhaseStatus,
    PIPELINE_DEPENDENCIES,
    PIPELINE_DEPENDENCIES_MAP,
    PIPELINE_VERSION_MAP,
    PipelineSignalData,
    PolicyTestCase,
    PositionEffectCheck,
    PortfolioRiskSnapshot,
    PostmortemReport,
    PROFILES,
    ReproducibilityManifest,
    ResilienceBudget,
    ReviewDebtTracker,
    RouteDecisionLog,
    SagaLogEntry,
    SchedulingProfileDef,
    select_profile,
    SilentFailureAlert,
    StopTheLineTrigger,
    SupplyChainIntegrityCheck,
    TOCTOUGuardResult,
)

from zephyr.pipeline.ct_pipe_routing import (
    CtPipeRoutingHints,
    PipelineRoutingInputsError,
    ct_pipe_hints_from_task_card,
    modules_slice_from_node,
    resolve_ct_pipe_orc001,
    enforce_affinity,
)

from zephyr.pipeline.pipeline_lock import (
    PipelineLock,
    FileLockBackend,
    LockBackend,
    LockResult,
    LockStatus,
    MemoryLockBackend,
)
from zephyr.pipeline.pipeline_orchestrator import PipelineOrchestrator
from zephyr.pipeline.model_router import ModelRouter
from zephyr.pipeline.routing_plugins import (
    PipelineRouter,
    RoutingPlugin,
    RoutingContext,
    NoEligibleNodeError,
    DEFAULT_PLUGINS,
)
from zephyr.pipeline.layer_router import (
    LayerDataRouter,
    LayerRouteMap,
    LayerRouteResult,
    RouteEntry,
    load_route_map,
    get_layer_router,
    reset_layer_router,
    handle_layer_onboarding,
    handle_layer_data_route,
    handle_layer_query,
)
from zephyr.pipeline.layer_consumer_registry import (
    register_all_consumers,
    register_for_layer,
    get_registry_summary,
)
from zephyr.pipeline.backpressure_manager import (
    BackpressureManager,
    BpState,
    BpSymbolState,
    emit_pause,
    emit_throttle,
    emit_resume,
)

from zephyr.pipeline.model_profiler import (
    ALL_BENCHMARK_CASES,
    BenchmarkCase,
    CaseResult,
    CATEGORY_MAP,
    DiscoveredModel,
    ModelDiscovery,
    ModelProfile,
    ModelProfiler,
    ModelTaskEntry,
    ModelTaskMatrix,
    TaskRecommendation,
)
from zephyr.pipeline.model_profiler.results_writer import (
    detect_drift,
    load_benchmark_history,
    to_model_benchmark_result,
    write_benchmark_results,
)

__all__ = ['ABExperimentRoute', 'AFFINITY_CONSTRAINTS', 'AIImpactAssessment', 'A_DAG', 'AffinityWeight', 'ArtifactClassification', 'ArtifactType', 'B_DAG', 'BackpressureManager', 'BlueprintCodeDriftChecker', 'BlueprintCodeDriftEntry', 'BpState', 'BpSymbolState', 'ChaosExperimentResult', 'CircuitBreakerState', 'ClaudeRescueTrigger', 'CostRecord', 'CtPipeRoutingHints', 'DEFAULT_PLUGINS', 'DeadLetterEntry', 'DegradationLevel', 'DriftReport', 'EmergencyFallbackPlan', 'ErrorBudget', 'ExperimentVariant', 'FaultInjectionSpec', 'FileLockBackend', 'GenericModuleOutput', 'GoldenTestResult', 'HallucinationCheckResult', 'HealthReport', 'LayerDataRouter', 'LayerRouteMap', 'LayerRouteResult', 'LockBackend', 'LockResult', 'LockStatus', 'M10ReportOutput', 'M11GatingOutput', 'M1ParseOutput', 'M3GenerateOutput', 'M6DiffOutput', 'M7ReviewOutput', 'M8ComplianceOutput', 'M9RiskOutput', 'M_MODULES', 'M_MODULE_SPECS', 'M_TO_ROLE', 'MemoryLockBackend', 'ModelCollapseAlert', 'ModelConfidence', 'ModelRouter', 'ModelVersionInfo', 'ModuleInput', 'ModuleResult', 'MutationTestResult', 'NoEligibleNodeError', 'OrchestratorIntegrationBridge', 'PipelineAffinityConstraint', 'PipelineAgentBridge', 'PipelineArtifact', 'PipelineArtifactManifest', 'PipelineDAG', 'PipelineLineageChain', 'PipelineLineageEntry', 'PipelineLock', 'PipelineOrchestrator', 'PipelineOrchestratorConfig', 'PipelineOrchestratorRoadmapMixin', 'PipelineResult', 'PipelineRouteDecision', 'PipelineRouter', 'PipelineRoutingInputsError', 'PipelineStage', 'PipelineStatus', 'PolicyDiffReport', 'PreemptionRecord', 'ROICalculator', 'RouteEntry', 'RoutingContext', 'RoutingPlugin', 'SLOMetric', 'SLOState', 'SessionBrief', 'StageContext', 'StageOnFailure', 'backpressure_manager', 'ct_pipe_hints_from_task_card', 'ct_pipe_routing', 'domain_for_pipeline', 'emit_pause', 'emit_resume', 'emit_throttle', 'enforce_affinity', 'get_layer_router', 'get_registry_summary', 'handle_layer_data_route', 'handle_layer_onboarding', 'handle_layer_query', 'layer_consumer_registry', 'load_route_map', 'models', 'modules_slice_from_node', 'pipeline_agent_bridge', 'pipeline_lock', 'pipeline_orchestrator', 'pipeline_roadmap', 'register_all_consumers', 'register_for_layer', 'reset_layer_router', 'resolve_ct_pipe_orc001', 'role_for_module', 'routing_plugins', 'validate_module_output', 'layer_router', 'ALL_BENCHMARK_CASES', 'BenchmarkCase', 'CaseResult', 'CATEGORY_MAP', 'DiscoveredModel', 'ModelDiscovery', 'ModelProfile', 'ModelProfiler', 'detect_drift', 'load_benchmark_history', 'to_model_benchmark_result', 'write_benchmark_results', 'ModelTaskEntry', 'ModelTaskMatrix', 'TaskRecommendation']
