# [BLUEPRINT] MOD-BT-001 | (auto-injected by S4 reconciler) | §
# [TTL] permanent
"""



Auto-generated contracts package — io

Generated by: scripts/governance/d5_architecture/generate_contracts.py

# [ALGO_FLOW] external: docs/03_modules/_domain_backtest/algo_flow/io__init__.yaml
"""

from .backtest_result_sink import BacktestSinkData, sink_backtest_result
from .result_repository import (
    ArtifactNotFoundError,
    BacktestRunArtifact,
    build_artifact_from_data,
    delete_artifact,
    get_artifact,
    list_artifacts,
    save_artifact,
)

__all__ = [
    "result_repository",
    "backtest_result_sink",
    "BacktestSinkData",
    "sink_backtest_result",
]
