# [BLUEPRINT] MOD-BT-001 | (auto-injected by S4 reconciler) | §
# [TTL] permanent
"""
Auto-generated contracts package — io

Generated by: scripts/governance/d5_architecture/generate_contracts.py
"""

from .result_repository import ArtifactNotFoundError, BacktestRunArtifact, save_artifact, get_artifact, list_artifacts, delete_artifact, build_artifact_from_data
from .backtest_result_sink import BacktestSinkData, sink_backtest_result

__all__ = [
    "result_repository",
    "backtest_result_sink",
    "BacktestSinkData",
    "sink_backtest_result",
]
