# [BLUEPRINT] MOD-BT-001 | (auto-injected by S4 reconciler) | §
# [TTL] permanent
"""



Auto-generated contracts package — io

Generated by: scripts/governance/d5_architecture/generate_contracts.py

# [ALGO_FLOW]
# 层: 输入
# - id: I1
#   name: backtest_result_sink 子模块符号 2个
#   fields: BacktestSinkData / sink_backtest_result
#   code: backtest_result_sink
# - id: I2
#   name: result_repository 子模块符号 7个
#   fields: ArtifactNotFoundError / BacktestRunArtifact / save_artifact / get_artifact / list_artifacts / delete_artifact 等7个
#   code: result_repository
# 层: 算法
# - id: A1
#   name_zh: ① 包级聚合再导出
#   name_en: zephyr.backtest.io.__init__
#   intro: Auto-generated contracts package — io
#   desc: MOD-BT-001 包入口，包级聚合再导出并声明 __all__（4项）
#   inputs: I1 I2
#   outputs: zephyr.backtest.io 包级公共命名空间
#   invariant: 包级导出以 __all__ 声明为准（4项）
# 层: 输出
# - id: O1
#   name_zh: zephyr.backtest.io 包公共 API
#   name_en: __all__ 4项
#   intro: Auto-generated contracts package — io——对外统一出口
#   downstream: 见蓝图头 [CONSUMERS] 声明
# [/ALGO_FLOW]
# 边:
# I1 --> A1
# I2 --> A1
# A1 --> O1
"""

from .backtest_result_sink import BacktestSinkData, sink_backtest_result
from .result_repository import (
    ArtifactNotFoundError,
    BacktestRunArtifact,
    build_artifact_from_data,
    delete_artifact,
    get_artifact,
    list_artifacts,
    save_artifact,
)

__all__ = [
    "result_repository",
    "backtest_result_sink",
    "BacktestSinkData",
    "sink_backtest_result",
]
