import sqlite3
conn = sqlite3.connect('data/databases/depgraph.db')
print('Domains:', conn.execute('SELECT COUNT(*) FROM domains').fetchone()[0])
print('Hyphen domains:', conn.execute('SELECT COUNT(*) FROM domains WHERE domain_id LIKE "%-%"').fetchone()[0])
print('D-GOV_RULE nodes:', conn.execute('SELECT COUNT(*) FROM nodes WHERE domain_id="D-GOV_RULE"').fetchone()[0])
print('D-GOV_AUDIT nodes:', conn.execute('SELECT COUNT(*) FROM nodes WHERE domain_id="D-GOV_AUDIT"').fetchone()[0])
print('D-BEHAVIORAL_AUDIT nodes:', conn.execute('SELECT COUNT(*) FROM nodes WHERE domain_id="D-BEHAVIORAL_AUDIT"').fetchone()[0])
print('D-GOV_DRIFT nodes:', conn.execute('SELECT COUNT(*) FROM nodes WHERE domain_id="D-GOV_DRIFT"').fetchone()[0])
print('D-TEST domains:', conn.execute('SELECT COUNT(*) FROM domains WHERE domain_id="D-TEST"').fetchone()[0])
print('D-GOVERNANCE prod:', conn.execute('SELECT COUNT(*) FROM nodes WHERE domain_id="D-GOVERNANCE" AND design_maturity="production"').fetchone()[0])
print('D-GOVERNANCE total:', conn.execute('SELECT COUNT(*) FROM nodes WHERE domain_id="D-GOVERNANCE"').fetchone()[0])
print('D-INFRA_RUNTIME:', conn.execute('SELECT COUNT(*) FROM domains WHERE domain_id="D-INFRA_RUNTIME"').fetchone()[0])
print('D-INFRASTRUCTURE:', conn.execute('SELECT COUNT(*) FROM domains WHERE domain_id="D-INFRASTRUCTURE"').fetchone()[0])
print()
print('All domains:')
for r in conn.execute('SELECT domain_id, ssot_path FROM domains ORDER BY domain_id').fetchall():
    print(f'  {r[0]:30s} {r[1] or ""}')
