# [BLUEPRINT] MOD-INF-005 | scripts/governance/d3_metadata/generate_wiring_registry.py | §
# [MODULE] scripts.governance.d3_metadata.generate_wiring_registry
# [DOMAIN] D_GOV_SCRIPTS
# [DEPENDENCIES] yaml
# [CONSUMERS] tests/governance/test_consumption_census_redproof.py（R-K 机器视图考卷）; src/zephyr/governance/consumption/consumption_census.py（头注在案消费声明·孤岛入账）; src/zephyr/governance/consumption/consumption_census_reconciler.py（入账指路）
# [STARTUP] manual
# [MATURITY] new
# [INVARIANTS] wiring_registry 机器视图唯一产出者=本件（派生产物禁手改，禁手工维护清单=宪法 §9.5）; --check 只读（账面缺项=漂移 rc=1，入账后复跑 rc=0），本件永不直写登记册（入账=交总筹落 YAML）; 孤岛 wiring_status 复用既有册词表 {unwired,wired,exempt}，新岛默认 unwired、已在册者继承原值; 治愈回填事件（island_transitions）只认 census 复跑 state=active 实证（doc 提及/消失不算）; 生成全确定性——时间字段只取 census 台账 updated_at，禁 datetime.now()/time.time()（RULE-SCHEMA-TZ）; 观测者身份自排（scan_scope_converged C5：本件提及实体名不算消费者）
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT] census 台账缺失/不可解析 -> exit 2（不写盘）; --check 检出账面缺项 -> exit 1; 生成模式缺 --out -> exit 2
# [TESTS] 自动: tests/governance/test_consumption_census_redproof.py::test_generator_books_islands_with_existing_vocabulary; 手动: python scripts/governance/d3_metadata/generate_wiring_registry.py --repo-root . --out <yaml> --check
# [A_module] module_id=MOD-INF-005 | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] permanent
# noqa: m11-perm-manual-legitimate  M11豁免: census 孤岛入账机器视图 CLI（--check 只读对账、永不直写登记册），manual 触发即设计语义；不内建 sleep/Timer（宪法 §9.3）
# create-guard-not-dup: 本件=波13 在册能力 generate_wiring_registry 的唯一实现（capability_canonical_file_registry token 已在册，规格=lane-r2 §3/测试 R-K）；非 yaml_utils/check_naming_convention 第二真源，_load_yaml 系私有一次性读入助手非通用能力面
"""generate_wiring_registry.py — 消费普查孤岛 → wiring_registry 机器视图生成器。

治本对象 = test_consumption_census_redproof R-K（wiring_registry 机器视图）：
消费普查引擎（zephyr.governance.consumption.consumption_census）产出的孤岛清单
此前无入账通道，本件把"读台账→按既有词表归类→产机器视图→--check 对账"变成
可重复执行的生成器（规格留痕：.runtime/tmp/st-zchief9-20260929/defers/lane-r2.md §3）。

三段输出（在既有册内容之上增补，既有 modules/classes 原样保留）：
  1. consumption_islands —— 逐孤岛 entity_id 入账：wiring_status ∈
     {unwired, wired, exempt}（复用既有册词表），已在册者继承原值、新岛默认
     unwired；按 census 孤岛序（value_score 降序）截取 --top N。
  2. island_transitions —— 治愈回填事件：已在册 unwired 孤岛复跑后离开孤岛账面
     且 census 实证 state=active（补上真消费者）⇒ 记 wiring_status=wired 事件。
  3. modules —— 既有册 modules 段原样保留（wiring_status=exempt 不动）。
另置 ``generator: <GEN_PATH_COMMENT>``（假声明归真：声明必须指向本生成器真实路径）。

--check 语义：--registry 指向在册 YAML，以与生成共用的默认 --top 视角重建对照视图，
账面缺项（对照视图的孤岛未入账或 wiring_status 不一致）= 漂移 exit 1；入账后复跑
exit 0。本件只读对账，不代写入登记册（新岛报警归事件触发 reconciler，R-J）。

用法
----
    python .../generate_wiring_registry.py --repo-root . --out view.yaml --top 10
    python .../generate_wiring_registry.py --repo-root . --registry <prod> --check
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import yaml

GEN_PATH_COMMENT = "generated by scripts/governance/d3_metadata/generate_wiring_registry.py"
CATALOG_DIR = Path("docs/01_policies_and_standards/_registry/catalogs")
REGISTRY_NAME = "wiring_registry.yaml"
LEDGER_REL = Path("data/runtime/consumption_census_ledger.json")
WIRING_VOCAB = ("unwired", "wired", "exempt")
_SECTIONS = ("consumption_islands", "island_transitions", "generator")


def _load_yaml(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    doc = yaml.safe_load(path.read_text(encoding="utf-8"))
    return doc if isinstance(doc, dict) else {}


def _load_ledger(path: Path) -> dict[str, Any]:
    """读消费普查台账（schema=consumption_census/2，doc 本体直写 JSON）。"""
    if not path.is_file():
        raise FileNotFoundError("census 台账不存在（先跑消费普查产出）")
    doc = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(doc, dict) or "islands" not in doc:
        raise ValueError("census 台账格式不识别（缺 islands 段）")
    return doc


def _census_rows(ledger: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """台账 families[].entries 拍平成 {entity_id: row}（治愈实证用）。"""
    rows: dict[str, dict[str, Any]] = {}
    for fam in ledger.get("families") or []:
        for row in fam.get("entries") or []:
            eid = str(row.get("entity_id", ""))
            if eid:
                rows[eid] = row
    return rows


def _booked_islands(ledger: dict[str, Any], prior: dict[str, dict[str, Any]], top: int) -> list[dict[str, Any]]:
    """孤岛入账：census 序（value_score 降序）截 top N，词表归类已在册者优先。"""
    booked: list[dict[str, Any]] = []
    for island in (ledger.get("islands") or [])[: max(top, 0)]:
        eid = str(island.get("entity_id", ""))
        if not eid:
            continue
        status = str(prior.get(eid, {}).get("wiring_status", ""))
        booked.append(
            {
                "entity_id": eid,
                "family": island.get("family", ""),
                "wiring_status": status if status in WIRING_VOCAB else "unwired",
                "value_score": island.get("value_score", 0),
                "suggested_wiring_target": island.get("suggested_wiring_target", ""),
                "booked_at": ledger.get("updated_at", ""),
            }
        )
    return booked


def _healing_transitions(
    prior: dict[str, dict[str, Any]],
    booked_ids: set[str],
    rows: dict[str, dict[str, Any]],
    booked_at: Any,
) -> list[dict[str, Any]]:
    """治愈回填事件：已入账 unwired 孤岛离开账面且 census 实证 state=active ⇒ wired。"""
    transitions: list[dict[str, Any]] = []
    for eid, old in sorted(prior.items()):
        if eid in booked_ids or old.get("wiring_status") != "unwired":
            continue
        row = rows.get(eid)
        if row is None or row.get("state") != "active":
            continue  # 无治愈实证（doc 提及/实体消失）不记事件
        transitions.append(
            {
                "entity_id": eid,
                "family": row.get("family", old.get("family", "")),
                "wiring_status": "wired",
                "from_status": "unwired",
                "event": "healed_by_consumer",
                "booked_at": booked_at,
            }
        )
    return transitions


def build_view(ledger: dict[str, Any], registry: dict[str, Any], top: int) -> dict[str, Any]:
    """台账 + 既有册 → 机器视图（既有键原样保留，三段输出 + generator 声明）。"""
    prior = {
        str(e.get("entity_id", "")): e
        for e in registry.get("consumption_islands") or []
        if isinstance(e, dict) and e.get("entity_id")
    }
    booked = _booked_islands(ledger, prior, top)
    transitions = _healing_transitions(
        prior, {b["entity_id"] for b in booked}, _census_rows(ledger), ledger.get("updated_at", "")
    )
    view: dict[str, Any] = {k: v for k, v in registry.items() if k not in _SECTIONS}
    view["consumption_islands"] = booked
    view["island_transitions"] = transitions
    view["generator"] = GEN_PATH_COMMENT
    return view


def _check(booked: list[dict[str, Any]], registry: dict[str, Any]) -> int:
    """账面缺项=漂移：生成视图每个孤岛必须在册且 wiring_status 一致。"""
    in_book = {
        str(e.get("entity_id", "")): str(e.get("wiring_status", ""))
        for e in registry.get("consumption_islands") or []
        if isinstance(e, dict)
    }
    missing = [
        f"{b['entity_id']}(期望 {b['wiring_status']}, 账面 {in_book.get(b['entity_id'], '缺')})"
        for b in booked
        if in_book.get(b["entity_id"]) != b["wiring_status"]
    ]
    if missing:
        print(f"DRIFT: 账面缺项 {len(missing)} 条: {'; '.join(missing)}")
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="消费普查孤岛 → wiring_registry 机器视图生成器")
    parser.add_argument("--repo-root", required=True, help="仓库根")
    parser.add_argument("--out", help="机器视图输出 YAML（--check 时可省）")
    parser.add_argument(
        "--top",
        type=int,
        default=5,
        help="入账孤岛数上限（value_score 降序截取；默认 5=考卷钉定，生成与 --check 共用同一默认视角）",
    )
    parser.add_argument(
        "--registry",
        help=f"既有 wiring_registry YAML（缺省={CATALOG_DIR / REGISTRY_NAME}）",
    )
    parser.add_argument("--check", action="store_true", help="只读对账：账面缺项=漂移 exit 1")
    args = parser.parse_args(argv)

    repo = Path(args.repo_root)
    ledger_path = repo / LEDGER_REL
    try:
        ledger = _load_ledger(ledger_path)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"ERROR: {exc}; ledger={ledger_path}", file=sys.stderr)
        return 2
    registry_path = Path(args.registry) if args.registry else repo / CATALOG_DIR / REGISTRY_NAME
    try:
        registry = _load_yaml(registry_path)
    except yaml.YAMLError as exc:
        print(f"ERROR: 既有册不可解析 {registry_path}: {exc}", file=sys.stderr)
        return 2
    view = build_view(ledger, registry, args.top)

    if args.check:
        return _check(view["consumption_islands"], registry)

    if not args.out:
        parser.error("生成模式必须给 --out（本件永不直写登记册）")
        return 2
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        yaml.safe_dump(view, allow_unicode=True, sort_keys=False, default_flow_style=False),
        encoding="utf-8",
        newline="\n",
    )
    print(f"OK: {len(view['consumption_islands'])} 孤岛入账 → {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
