# [A_module] module_id=MOD-UNK_monitoring_stack | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
"""
Auto-generated contracts package — traces

Generated by: scripts/governance/d5_architecture/generate_contracts.py
"""

# STUB: from .span_stub import *
# Reason: span_stub.py does not exist in monitoring_stack/
__all__ = []
