# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared_core/contracts_blueprint.md
# [A_module] module_id=MOD-INTEGRATION | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] permanent
"""



Auto-generated contracts package — errors

Generated by: scripts/governance/d5_architecture/generate_contracts.py

# [ALGO_FLOW]
# 层: 输入
# - id: I1
#   name: contract_violation_error 子模块符号 1个
#   fields: ContractViolationError
#   code: zephyr.integration.shared.contracts.errors.contract_violation_error
# - id: I2
#   name: data_quality_error 子模块符号 1个
#   fields: DataQualityError
#   code: zephyr.integration.shared.contracts.errors.data_quality_error
# - id: I3
#   name: execution_rejection_error 子模块符号 1个
#   fields: ExecutionRejectionError
#   code: zephyr.integration.shared.contracts.errors.execution_rejection_error
# - id: I4
#   name: factor_computation_error 子模块符号 1个
#   fields: FactorComputationError
#   code: zephyr.integration.shared.contracts.errors.factor_computation_error
# - id: I5
#   name: risk_limit_violation_error 子模块符号 1个
#   fields: RiskLimitViolationError
#   code: zephyr.integration.shared.contracts.errors.risk_limit_violation_error
# - id: I6
#   name: signal_degradation_warning 子模块符号 1个
#   fields: SignalDegradationWarning
#   code: zephyr.integration.shared.contracts.errors.signal_degradation_warning
# 层: 算法
# - id: A1
#   name_zh: ① 包级聚合再导出
#   name_en: zephyr.integration.shared.contracts.errors.__init__
#   intro: Auto-generated contracts package — errors
#   desc: MOD-INTEGRATION 包入口，包级聚合再导出并声明 __all__（6项）
#   inputs: I1 I2 I3 I4 I5 I6
#   outputs: zephyr.integration.shared.contracts.errors 包级公共命名空间
#   invariant: 包级导出以 __all__ 声明为准（6项）
# 层: 输出
# - id: O1
#   name_zh: zephyr.integration.shared.contracts.errors 包公共 API
#   name_en: __all__ 6项
#   intro: Auto-generated contracts package — errors——对外统一出口
#   downstream: 见蓝图头 [CONSUMERS] 声明
# [/ALGO_FLOW]
# 边:
# I1 --> A1
# I2 --> A1
# I3 --> A1
# I4 --> A1
# I5 --> A1
# I6 --> A1
# A1 --> O1
"""

from zephyr.integration.shared.contracts.errors.contract_violation_error import ContractViolationError
from zephyr.integration.shared.contracts.errors.data_quality_error import DataQualityError
from zephyr.integration.shared.contracts.errors.execution_rejection_error import ExecutionRejectionError
from zephyr.integration.shared.contracts.errors.factor_computation_error import FactorComputationError
from zephyr.integration.shared.contracts.errors.risk_limit_violation_error import RiskLimitViolationError
from zephyr.integration.shared.contracts.errors.signal_degradation_warning import SignalDegradationWarning

__all__ = [
    "ContractViolationError",
    "DataQualityError",
    "ExecutionRejectionError",
    "FactorComputationError",
    "RiskLimitViolationError",
    "SignalDegradationWarning",
]
