# [A_module] module_id=MOD-SHR_errors | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] permanent
"""
Auto-generated contracts package — errors

Generated by: scripts/governance/d5_architecture/generate_contracts.py
"""

from zephyr.integration.shared.contracts.errors.contract_violation_error import ContractViolationError
from zephyr.integration.shared.contracts.errors.data_quality_error import DataQualityError
from zephyr.integration.shared.contracts.errors.execution_rejection_error import ExecutionRejectionError
from zephyr.integration.shared.contracts.errors.factor_computation_error import FactorComputationError
from zephyr.integration.shared.contracts.errors.risk_limit_violation_error import RiskLimitViolationError
from zephyr.integration.shared.contracts.errors.signal_degradation_warning import SignalDegradationWarning

__all__ = [
    "ContractViolationError",
    "DataQualityError",
    "ExecutionRejectionError",
    "FactorComputationError",
    "RiskLimitViolationError",
    "SignalDegradationWarning",
]
