"""
Auto-generated contracts package — backpressure

Generated by: scripts/governance/d5_architecture/generate_contracts.py
"""

from .pause import BackpressurePause
from .resume import BackpressureResume
from .throttle import BackpressureThrottle

__all__ = [
    "pause",
    "resume",
    "throttle",
]
