# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared_core/blueprint.md | §
# [MODULE] zephyr.shared.io.pagination
# [DOMAIN] D_SHARED
# [DEPENDENCIES] zephyr.shared.utils.pagination
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-SHR_pagination | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] permanent

"""
pagination.py —— Re-export wrapper → canonical: zephyr.shared.utils.pagination

Backward-compatible top-level alias. Canonical implementation at utils/pagination.py.
Edit utils/pagination.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.utils.pagination import *  # noqa: F403
