# [BLUEPRINT] MOD-INF-026 | docs/03_modules/_domain-infra_ops/asset-inventory/blueprint.md
# [MODULE] zephyr.infrastructure.asset_inventory.metadata
# [DOMAIN] D_INFRA_RUNTIME
# [DEPENDENCIES] zephyr.infrastructure.asset_inventory.__init__
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] production
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-INF_metadata | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] permanent

"""MOD-INF-026 §24-25 — Git 历史元数据提取 + 多 IDE 规则生成器。

SRC-0040: 从 git_metadata.py + multi_ide.py 合并。
"""

import logging

logger = logging.getLogger(__name__)

import os
import re
import subprocess
from datetime import UTC, datetime
from pathlib import Path

from pydantic import BaseModel, Field

# ============================================================================
# Git 历史元数据提取引擎 (原 git_metadata.py)
# ============================================================================


class GitCommitInfo(BaseModel):
    sha: str
    author: str
    date: datetime
    message: str
    lines_added: int = 0
    lines_deleted: int = 0


class GitAssetMetadata(BaseModel):
    file_path: str
    first_commit_sha: str = ""
    first_commit_date: datetime | None = None
    last_commit_sha: str = ""
    last_commit_date: datetime | None = None
    total_commits: int = 0
    authors: list[str] = Field(default_factory=list)
    primary_author: str = ""
    ai_commits_ratio: float = 0.0
    lines_added_total: int = 0
    lines_deleted_total: int = 0
    net_lines: int = 0
    churn_rate: float = 0.0
    bug_fix_commits: int = 0
    co_changed_files: list[str] = Field(default_factory=list)
    co_changed_count: int = 0


_AI_COMMIT_PATTERNS = re.compile(
    r"\[AI\]|\[agent\]|\[auto\]|generated by|auto-generated|ai-session|trae|claude|copilot",
    re.IGNORECASE,
)
_BUG_FIX_PATTERNS = re.compile(r"\b(fix|bug|hotfix|patch)\b", re.IGNORECASE)


class GitMetadataExtractor:
    def __init__(self, project_root: Path) -> None:
        self._root = project_root

    def extract(self, file_path: str) -> GitAssetMetadata | None:
        log = self._run_git_log(file_path)
        if not log:
            return None

        current_lines = self._current_lines(file_path)

        authors_list = list(dict.fromkeys(c.author for c in log))
        primary = max(set(c.author for c in log), key=lambda a: sum(1 for c in log if c.author == a)) if log else ""

        total_added = sum(c.lines_added for c in log)
        total_deleted = sum(c.lines_deleted for c in log)
        total_churn = total_added + total_deleted

        co_changed = self._find_co_changed(file_path)

        return GitAssetMetadata(
            file_path=file_path,
            first_commit_sha=log[-1].sha if log else "",
            first_commit_date=log[-1].date if log else None,
            last_commit_sha=log[0].sha if log else "",
            last_commit_date=log[0].date if log else None,
            total_commits=len(log),
            authors=authors_list,
            primary_author=primary,
            ai_commits_ratio=sum(1 for c in log if self._is_ai_commit(c.message)) / max(1, len(log)),
            lines_added_total=total_added,
            lines_deleted_total=total_deleted,
            net_lines=total_added - total_deleted,
            churn_rate=total_churn / max(1, current_lines),
            bug_fix_commits=sum(1 for c in log if _BUG_FIX_PATTERNS.search(c.message)),
            co_changed_files=[f for f, _ in co_changed[:5]],
            co_changed_count=len(co_changed),
        )

    def _run_git_log(self, file_path: str) -> list[GitCommitInfo]:
        try:
            result = subprocess.run(
                ["git", "log", "--follow", "--numstat", "--format=%H|%an|%ai|%s", "--", file_path],
                capture_output=True,
                text=True,
                cwd=str(self._root),
                timeout=30,
            )
        except (subprocess.TimeoutExpired, FileNotFoundError):
            return []

        if result.returncode != 0:
            return []

        return self._parse_log_output(result.stdout)

    def _parse_log_output(self, output: str) -> list[GitCommitInfo]:
        commits: list[GitCommitInfo] = []
        lines = output.strip().split("\n")

        current: dict | None = None  # type: ignore[type-arg]

        for line in lines:
            if not line.strip():
                continue

            if "|" in line and "@" not in line.split("|", 2)[1] if len(line.split("|")) >= 2 else False:
                continue

            parts = line.split("|", 3)
            if len(parts) >= 4:
                if current:
                    commits.append(GitCommitInfo(**current))
                current = {
                    "sha": parts[0],
                    "author": parts[1],
                    "date": self._parse_date(parts[2].strip()),
                    "message": parts[3].strip(),
                    "lines_added": 0,
                    "lines_deleted": 0,
                }
            elif current and "\t" in line:
                parts_ns = line.split("\t")
                if len(parts_ns) >= 3:
                    try:
                        current["lines_added"] += int(parts_ns[0]) if parts_ns[0] != "-" else 0
                        current["lines_deleted"] += int(parts_ns[1]) if parts_ns[1] != "-" else 0
                    except ValueError:
                        pass

        if current:
            commits.append(GitCommitInfo(**current))

        return commits

    @staticmethod
    def _parse_date(date_str: str) -> datetime:
        try:
            return datetime.strptime(date_str.strip()[:19], "%Y-%m-%d %H:%M:%S").replace(tzinfo=UTC)
        except ValueError:
            return datetime.min.replace(tzinfo=UTC)

    def _current_lines(self, file_path: str) -> int:
        full = self._root / file_path
        if not full.exists():
            return 0
        try:
            # 5.59.3 修复：原 errors="ignore" 静默丢弃非法字节，行数统计和 import 计数失真，影响架构决策数据。
            # 改用二进制模式按 b"\n" 计数，避免编码问题影响行数。
            return len(full.read_bytes().split(b"\n"))
        except (OSError, PermissionError):
            return 0

    @staticmethod
    def _is_ai_commit(message: str) -> bool:
        return bool(_AI_COMMIT_PATTERNS.search(message))

    def _find_co_changed(self, file_path: str) -> list[tuple[str, str]]:
        try:
            result = subprocess.run(
                ["git", "log", "--follow", "--name-only", "--format=COMMIT %H", "--", file_path],
                capture_output=True,
                text=True,
                cwd=str(self._root),
                timeout=15,
            )
        except (subprocess.TimeoutExpired, FileNotFoundError):
            return []

        if result.returncode != 0:
            return []

        counter: dict[str, int] = {}
        current_commit = ""

        for line in result.stdout.strip().split("\n"):
            if line.startswith("COMMIT "):
                current_commit = line[7:].strip()
                continue
            if line.strip() and current_commit and line.strip() != file_path:
                counter[line.strip()] = counter.get(line.strip(), 0) + 1

        return sorted(counter.items(), key=lambda x: x[1], reverse=True)


# ============================================================================
# 多 IDE 兼容规则文件生成器 (原 multi_ide.py)
# ============================================================================


class MultiIDERuleGenerator:
    """多 IDE 规则文件生成器——从 asset-inventory 配置生成。

    支持: Cursor (.cursorrules) / Trae (.trae/rules/) / VSCode (.github/copilot-instructions.md) / JetBrains (.idea/asset-inventory.xml)
    一次生成，随时更新——不从 LLM 推理，直接从配置映射。
    """

    def __init__(self, project_root: Path) -> None:
        self._root = project_root

    def _collect_project_rules(self) -> str:
        rules_path = self._root / ".trae" / "rules" / "project_rules.md"
        if not rules_path.exists():
            return "# No project_rules.md found"

        try:
            content = rules_path.read_text(encoding="utf-8")
            return f"# --- project_rules.md ---\n{content[:8000]}\n"
        except (OSError, PermissionError):
            return "# project_rules.md read error"

    def _header(self) -> str:
        return datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")

    def _asset_rules_block(self) -> str:
        return (
            "# --- 自动盘点安全规则 ---\n"
            "# 以下规则由 MOD-INF-026 自动生成\n"
            "# 文件创建前查 registry_of_registries.yaml\n"
            "# 敏感文件不扫描 (.env, .secrets, token)\n"
            "# 超大文件跳过 (>50MB)\n"
        )

    def _atomic_write(self, target: Path, content: str) -> Path:
        target.parent.mkdir(parents=True, exist_ok=True)
        tmp = f"{target}.{os.getpid()}.tmp"
        tmp_path = Path(tmp)
        tmp_path.write_text(content, encoding="utf-8")
        os.replace(tmp, str(target))
        return target

    def generate_cursor_rules(self, output_path: Path | None = None) -> Path:
        target = output_path or (self._root / ".cursorrules")
        template = f"""# ZephyrAlpha Cursor Rules — 自动生成于 {self._header()}
# 来源: MOD-INF-026 Asset Inventory + project_rules.md
# 不要手工编辑——运行 python -m zephyr.data.asset_inventory cursor-rules 重新生成

{self._collect_project_rules()}

{self._asset_rules_block()}
"""
        return self._atomic_write(target, template)

    def generate_trae_rules(self, output_path: Path | None = None) -> Path:
        target = output_path or (self._root / ".trae" / "rules" / "asset_inventory_rules.md")
        template = f"""# ZephyrAlpha Trae Rules — 自动生成于 {self._header()}
# 来源: MOD-INF-026 Asset Inventory + project_rules.md
# 不要手工编辑——运行 python -m zephyr.data.asset_inventory trae-rules 重新生成

{self._collect_project_rules()}

{self._asset_rules_block()}
"""
        return self._atomic_write(target, template)

    def generate_vscode_rules(self, output_path: Path | None = None) -> Path:
        target = output_path or (self._root / ".github" / "copilot-instructions.md")
        template = f"""# ZephyrAlpha Copilot Instructions — 自动生成于 {self._header()}
# 来源: MOD-INF-026 Asset Inventory + project_rules.md
# 不要手工编辑——运行 python -m zephyr.data.asset_inventory vscode-rules 重新生成

{self._collect_project_rules()}

{self._asset_rules_block()}
"""
        return self._atomic_write(target, template)

    def generate_jetbrains_rules(self, output_path: Path | None = None) -> Path:
        target = output_path or (self._root / ".idea" / "asset-inventory.xml")
        rules_content = self._collect_project_rules()
        asset_block = self._asset_rules_block()
        escaped_rules = rules_content.replace("&", "&").replace("<", "<").replace(">", ">")
        escaped_asset = asset_block.replace("&", "&").replace("<", "<").replace(">", ">")
        template = f"""<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="AssetInventoryRules">
    <option name="generatedAt" value="{self._header()}" />
    <option name="source" value="MOD-INF-026 Asset Inventory + project_rules.md" />
    <option name="projectRules" value="{escaped_rules.strip()}" />
    <option name="assetRules" value="{escaped_asset.strip()}" />
  </component>
</project>
"""
        return self._atomic_write(target, template)

    def generate_all(self) -> dict[str, Path]:
        results: dict[str, Path] = {}
        try:
            results["cursor"] = self.generate_cursor_rules()
        except Exception as e:
            logger.warning("suppressed error in metadata", exc_info=True)
        try:
            results["trae"] = self.generate_trae_rules()
        except Exception as e:
            logger.warning("suppressed error in metadata", exc_info=True)
        try:
            results["vscode"] = self.generate_vscode_rules()
        except Exception as e:
            logger.warning("suppressed error in metadata", exc_info=True)
        try:
            results["jetbrains"] = self.generate_jetbrains_rules()
        except Exception as e:
            logger.warning("suppressed error in metadata", exc_info=True)
        return results
