# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared_core/blueprint.md | §
# [MODULE] zephyr.shared.events.observer
# [DOMAIN] D_SHARED
# [DEPENDENCIES] zephyr.shared.infra.observer
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-SHR_observer | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] permanent

"""
observer.py —— Re-export wrapper → canonical: zephyr.shared.infra.observer

Backward-compatible top-level alias. Canonical implementation at infra/observer.py.
Edit infra/observer.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.infra.observer import *  # noqa: F403
