# [A_module] module_id=MOD-GOV_lifecycle_governance | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
__all__ = [
    "api_lifecycle",
    "migration_strategy",
    "paper_live_transition",
    "post_live_verification",
    "TransitionPhase",
    "PhaseSpec",
    "TransitionState",
    "get_phase_spec",
    "valid_transition",
    "get_next_phase",
    "create_transition_state",
    "PLVCheck",
    "PLVSpec",
    "get_plv_spec",
    "MigrationPhase",
    "PhaseDef",
    "get_phase_def",
    "get_next_phase",
    "APIState",
    "DeprecationNotice",
    "APIEndpoint",
    "deprecate_api",
    "remove_api",
]
