/* 长城任务四·批 1：大盘分析+板块全景 渲染（演示数据，SVG 手写零依赖） */
(function(){
function SR(v){var x=0;for(var i=0;i<v.length;i++)x=(x*31+v.charCodeAt(i))>>>0;return function(){x=(x*1103515245+12345)&0x7fffffff;return x/0x7fffffff;};}
function spark(id,seed){var el=document.getElementById(id);if(!el)return;var r=SR(seed),n=60,v=[],p=100;for(var i=0;i<n;i++){p+=(r()-0.46)*3;v.push(p);}var w=el.clientWidth||300,h=el.clientHeight||30,mn=Math.min.apply(null,v),mx=Math.max.apply(null,v),pts=v.map(function(y,i){return (i/(n-1)*w).toFixed(1)+','+(h-(y-mn)/(mx-mn+1e-9)*(h-6)-3).toFixed(1);}).join(' ');el.innerHTML='<polyline points="'+pts+'" fill="none" stroke="#99C5FF" stroke-width="1.3"/>';}   /* v7：副指数迷你线=信息蓝统一（涨跌语义由 chip 承载） */
/* v7：大盘分析主图=日K实芯蜡烛（DS-5 蜡烛族锁色 红#CA3F64/绿#25A750 平涂）+MA10（DS-5 MA 族：MA10 品红 #EC407A）+虚线网格+右轴价位+底月份 */
function candles(id,seed){var el=document.getElementById(id);if(!el)return;var r=SR(seed),n=64,d=[],p=3560;for(var i=0;i<n;i++){var o=p,c=o+(r()-.46)*1.15*p/100,hh=Math.max(o,c)+r()*1.15*p/300,ll=Math.min(o,c)-r()*1.15*p/300;d.push({o:o,h:hh,l:ll,c:c});p=c;}
var w=el.clientWidth||600,h=el.clientHeight||124,padL=4,padR=46,padT=8,padB=18;
var lo=Math.min.apply(null,d.map(function(k){return k.l})),hi=Math.max.apply(null,d.map(function(k){return k.h}));
function X(i){return padL+(i+.5)*(w-padL-padR)/n;}function Y(v){return padT+(hi-v)/(hi-lo)*(h-padT-padB);}
var out='',g;
for(g=0;g<4;g++){var gv=lo+(hi-lo)*g/3,gy=Y(gv);out+='<line x1="'+padL+'" x2="'+(w-padR)+'" y1="'+gy.toFixed(1)+'" y2="'+gy.toFixed(1)+'" stroke="rgba(243,243,243,.16)" stroke-dasharray="2 5" stroke-width="1"/><text x="'+(w-padR+7)+'" y="'+(gy+3.5).toFixed(1)+'" font-size="10" fill="#59626D">'+gv.toFixed(0)+'</text>';}
var months=['5月','6月','7月','8月'];for(g=0;g<4;g++){var mx2=padL+(g+.5)*(w-padL-padR)/4;out+='<text x="'+mx2.toFixed(1)+'" y="'+(h-5)+'" font-size="10" fill="#59626D" text-anchor="middle">'+months[g]+'</text>';}
var bw=Math.max(2.2,(w-padL-padR)/n*.58);
d.forEach(function(k,i2){var up=k.c>=k.o,col=up?'#CA3F64':'#25A750';out+='<line x1="'+X(i2).toFixed(1)+'" x2="'+X(i2).toFixed(1)+'" y1="'+Y(k.h).toFixed(1)+'" y2="'+Y(k.l).toFixed(1)+'" stroke="'+col+'" stroke-width="1"/><rect x="'+(X(i2)-bw/2).toFixed(1)+'" y="'+Y(Math.max(k.o,k.c)).toFixed(1)+'" width="'+bw.toFixed(1)+'" height="'+Math.max(1.2,Math.abs(Y(k.o)-Y(k.c))).toFixed(1)+'" fill="'+col+'" rx="0.5"/>';});
var mp='',i2,j;for(i2=9;i2<d.length;i2++){var s=0;for(j=0;j<10;j++)s+=d[i2-j].c;mp+=(mp?'L':'M')+X(i2).toFixed(1)+','+Y(s/10).toFixed(1);}
out+='<path d="'+mp+'" fill="none" stroke="#EC407A" stroke-width="1.4" stroke-linejoin="round"/>';
el.innerHTML=out;}
/* 分档分布直方图 */
function drawDist(){var el=document.getElementById('mk-dist');if(!el)return;var bins=[['>10%',50,1],['10~7',82,1],['7~5',77,1],['5~3',303,1],['3~0',2501,1],['0%',144,0],['0~3',1957,-1],['3~5',296,-1],['5~7',92,-1],['7~10',32,-1],['>10%',13,-1]];var w=el.clientWidth||560,h=el.clientHeight||180,bw=w/bins.length,out='';bins.forEach(function(b,i){var bh=Math.sqrt(b[1])/Math.sqrt(2501)*(h-34),x=i*bw+bw*0.15,y=b[2]>=0?(h-22-bh):(h-22),c=b[2]>0?'#CA3F64':(b[2]<0?'#25A750':'#8B949E');out+='<rect x="'+x+'" y="'+y+'" width="'+(bw*0.7)+'" height="'+bh+'" fill="'+c+'" rx="2"/>';out+='<text x="'+(x+bw*0.35)+'" y="'+(b[2]>=0?y-4:y+bh+12)+'" font-size="10" fill="#EDEFF2" text-anchor="middle">'+b[1]+'</text>';out+='<text x="'+(x+bw*0.35)+'" y="'+(h-8)+'" font-size="9" fill="#8B949E" text-anchor="middle">'+b[0]+'</text>';});el.innerHTML=out;}
/* 成交额三线（v7：今日实线 vs 昨日虚线 vs 预测点线——预测=近 20 日同时段均值外推） */
function drawVol(){var el=document.getElementById('mk-vol');if(!el)return;var r=SR('vol1'),n=48,t=[],y=[],f=[],a=0,b=0,c2=0;for(var i=0;i<n;i++){a+=(r()+0.6)*92;t.push(a);b+=(r()+0.55)*90;y.push(b);c2+=(r()+0.52)*88;f.push(c2);}var w=el.clientWidth||700,h=el.clientHeight||112,mx=Math.max(t[n-1],y[n-1]);function line(v,c,dash,wd){var pts=v.map(function(z,i){return (i/(n-1)*w).toFixed(1)+','+(h-z/mx*(h-14)-4).toFixed(1);}).join(' ');return '<polyline points="'+pts+'" fill="none" stroke="'+c+'" stroke-width="'+(wd||1.6)+'" '+(dash?'stroke-dasharray="'+dash+'"':'')+'/>';}el.innerHTML=line(f,'rgba(243,243,243,.30)','2 4',1.2)+line(y,'#8B949E','5 4')+line(t,'#3D8BFF',false,1.8)+'<text x="'+(w-4)+'" y="14" font-size="10" fill="#3D8BFF" text-anchor="end">— 今日 21,180 亿</text><text x="'+(w-4)+'" y="26" font-size="10" fill="#8B949E" text-anchor="end">- - 昨日 21,413 亿</text><text x="'+(w-4)+'" y="38" font-size="10" fill="rgba(243,243,243,.45)" text-anchor="end">·· 预测（20 日同时段均值）</text>';}
/* RS 光谱地图 */
function drawRs(){var el=document.getElementById('sc-rsmap');if(!el)return;var rows=[['半导体',2.8,1],['软件算力',2.1,1],['证券',1.4,1],['创新药',0.8,1],['小金属',1.2,1],['电力',0.3,1],['白酒',-0.2,-1],['银行',-0.4,-1],['地产',-1.6,-1],['煤炭',-2.2,-1]];rows.sort(function(a,b){return b[1]-a[1];});var w=el.clientWidth||900,h=340,rh=h/rows.length,mid=w*0.5,scale=w*0.5/3.2,out='';out+='<line x1="'+mid+'" y1="0" x2="'+mid+'" y2="'+h+'" stroke="#EDEFF2" stroke-width="1" stroke-dasharray="4 3"/>';out+='<text x="'+mid+'" y="12" font-size="10" fill="#EDEFF2" text-anchor="middle">大盘 +0.61%</text>';rows.forEach(function(r,i){var y=i*rh+rh*0.2,bh=rh*0.56,len=Math.abs(r[1])*scale,x=r[1]>=0?mid:mid-len,c=r[1]>=0?'#CA3F64':'#25A750';out+='<rect x="'+x+'" y="'+y+'" width="'+len+'" height="'+bh+'" fill="'+c+'" rx="2" opacity="0.85"/>';var tx=r[1]>=0?x+len+6:x-6;out+='<text x="'+tx+'" y="'+(y+bh*0.68)+'" font-size="11" fill="#EDEFF2" text-anchor="'+(r[1]>=0?'start':'end')+'">'+r[0]+' '+(r[1]>0?'+':'')+r[1]+'%</text>';});el.innerHTML=out;}
/* v7 渲染时机修正（系统性缺陷根治）：隐藏页 display:none 时 clientWidth=0 → 图表按退化坐标系落盘；page:show（go() 广播）+ resize 时重绘本组图表 */
function renderMkt(){candles('mk-sh','sh20260828');spark('mk-sz','sz');spark('mk-cy','cy');spark('mk-kc','kc');drawDist();drawVol();drawRs();}
renderMkt();
document.addEventListener('page:show',function(e){if(e.detail==='live'||e.detail==='sector')renderMkt();});
window.addEventListener('resize',function(){var a=document.querySelector('.page.active');if(a&&(a.id==='p-live'||a.id==='p-sector'))renderMkt();});
})();
