# [A_module] module_id=MOD-INF_layer3_coordination | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [BLUEPRINT] MOD-INF-025 | docs/03_modules/_domain_infrastructure_operations/agent_to_agent_protocol/blueprint.md
# [MODULE] zephyr.infrastructure.a2a_protocol.layer3_coordination
# [INVARIANTS] pending_review
# [MODIFY-GUARD] no structural changes without owner approval
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [CONSUMERS]
# [ERROR_CONTRACT]
# [TESTS]
# [TTL] permanent
"""Layer 3: 协调+仲裁 — Coordinator, Living Spec 同步, 死锁防护, 全量 25 模块落地"""

from zephyr.infrastructure.a2a_protocol.layer3_coordination._consensus import (
    A2ADebate,
    A2ANegotiation,
    A2ASaga,
    A2AVoting,
    A2AWorkSteal,
    DebatePhase,
    DebateResult,
    DebateRound,
    NegotiationOffer,
    NegotiationResult,
    NegotiationStatus,
    SagaResult,
    SagaStatus,
    SagaStep,
    TaskQueue,
    VoteAction,
    VotingResult,
)
from zephyr.infrastructure.a2a_protocol.layer3_coordination._core_coordination import (
    AgentMeta,
    AgentRole,
    ArbitrationResult,
    Arbitrator,
    CascadeGuard,
    ChangeRange,
    ChangeSet,
    Conflict,
    ConflictDetector,
    ConflictSeverity,
    ConflictType,
    ConstructionVerifier,
    DeadlockGuard,
    FileOwnership,
    LivelockDetector,
    SemanticDiffEngine,
    SemanticDiffEntry,
    SemanticDiffReport,
    SemanticDiffType,
    SemanticRegion,
    StubAnalysis,
    Supervisor,
    VerifierResult,
)
from zephyr.infrastructure.a2a_protocol.layer3_coordination._governance_integration import (
    A2ADashboard,
    A2AFormalVerification,
    A2AFrameNegotiation,
    A2AGovernanceAdapter,
    A2AProtocolGateway,
    A2ATracing,
    DashboardPanel,
    FrameOffer,
    GatewayResult,
    GovernanceCheckResult,
    NegotiatedFrame,
    PropertyCheck,
    Span,
    SpecSync,
    SpecSyncEntry,
    VerificationReport,
    VerificationStatus,
)
from zephyr.infrastructure.a2a_protocol.layer3_coordination._intelligence import (
    A2ABehaviorFingerprint,
    A2ABlameAttribution,
    A2ACausalTrace,
    A2ACollusionDetector,
    A2AKnowledgeDistill,
    A2ALatentComm,
    BehaviorFingerprint,
    BlameItem,
    BlameReport,
    CausalEdge,
    CausalGraph,
    CausalNode,
    CollusionFinding,
    CollusionReport,
    CrossAgentSemanticFlow,
    DistilledKnowledge,
    LatentCommSignal,
    SemanticFlow,
    SemanticFlowNode,
)
from zephyr.infrastructure.a2a_protocol.layer3_coordination._security_and_economics import (
    A2AAnomalyDetector,
    A2ADelegationChain,
    A2AEconomics,
    A2AForgetting,
    A2AIdempotency,
    A2AIdleGuard,
    A2ARedTeam,
    A2ASecurityReport,
    A2ASecurityScanner,
    A2ATemporalAdmission,
    AnomalyLevel,
    AnomalyRecord,
    AttackCategory,
    AttackSeverity,
    AttackVector,
    MetricBaseline,
    MetricKey,
    SecurityFinding,
    SecurityVerdict,
    SessionSmugglingDefense,
    SmugglingAttempt,
    ThreatCategory,
)
# AI-14 审计 P5: 直接 import（_security_and_economics 为 frozen/immutable_core，不宜改）
from zephyr.infrastructure.a2a_protocol.layer3_coordination.a2a_agent_blocklist import (
    A2AAgentBlocklist,
)

__all__ = [
    "A2AAgentBlocklist",
    "A2AAnomalyDetector",
    "A2ABehaviorFingerprint",
    "A2ABlameAttribution",
    "A2ACausalTrace",
    "A2ACollusionDetector",
    "A2ADashboard",
    "A2ADebate",
    "A2ADelegationChain",
    "A2AEconomics",
    "A2AForgetting",
    "A2AFormalVerification",
    "A2AFrameNegotiation",
    "A2AGovernanceAdapter",
    "A2AIdempotency",
    "A2AIdleGuard",
    "A2AKnowledgeDistill",
    "A2ALatentComm",
    "A2ANegotiation",
    "A2AProtocolGateway",
    "A2ARedTeam",
    "A2ASaga",
    "A2ASecurityReport",
    "A2ASecurityScanner",
    "A2ATemporalAdmission",
    "A2ATracing",
    "A2AVoting",
    "A2AWorkSteal",
    "AgentMeta",
    "AgentRole",
    "AnomalyLevel",
    "AnomalyRecord",
    "ArbitrationResult",
    "Arbitrator",
    "AttackCategory",
    "AttackSeverity",
    "AttackVector",
    "BehaviorFingerprint",
    "BlameItem",
    "BlameReport",
    "CascadeGuard",
    "CausalEdge",
    "CausalGraph",
    "CausalNode",
    "ChangeRange",
    "ChangeSet",
    "CollusionFinding",
    "CollusionReport",
    "Conflict",
    "ConflictDetector",
    "ConflictSeverity",
    "ConflictType",
    "ConstructionVerifier",
    "CrossAgentSemanticFlow",
    "DashboardPanel",
    "DeadlockGuard",
    "DebatePhase",
    "DebateResult",
    "DebateRound",
    "DistilledKnowledge",
    "FileOwnership",
    "FrameOffer",
    "GatewayResult",
    "GovernanceCheckResult",
    "LatentCommSignal",
    "LivelockDetector",
    "MetricBaseline",
    "MetricKey",
    "NegotiatedFrame",
    "NegotiationOffer",
    "NegotiationResult",
    "NegotiationStatus",
    "PropertyCheck",
    "SagaResult",
    "SagaStatus",
    "SagaStep",
    "SecurityFinding",
    "SecurityVerdict",
    "SemanticDiffEngine",
    "SemanticDiffEntry",
    "SemanticDiffReport",
    "SemanticDiffType",
    "SemanticFlow",
    "SemanticFlowNode",
    "SemanticRegion",
    "SessionSmugglingDefense",
    "SmugglingAttempt",
    "Span",
    "SpecSync",
    "SpecSyncEntry",
    "StubAnalysis",
    "Supervisor",
    "TaskQueue",
    "ThreatCategory",
    "VerificationReport",
    "VerificationStatus",
    "VerifierResult",
    "VoteAction",
    "VotingResult",
    "_consensus",
    "_core_coordination",
    "_governance_integration",
    "_intelligence",
    "_security_and_economics",
    "a2a_anomaly_detector",
    "a2a_behavior_fingerprint",
    "a2a_blame_attribution",
    "a2a_carbon",
    "a2a_causal_trace",
    "a2a_checkpoint",
    "a2a_collusion_detector",
    "a2a_consent",
    "a2a_constitutional",
    "a2a_context_rot",
    "a2a_cross_agent_semantic_flow",
    "a2a_dashboard",
    "a2a_debate",
    "a2a_delegation_chain",
    "a2a_economics",
    "a2a_forgetting",
    "a2a_formal_verification",
    "a2a_frame_negotiation",
    "a2a_governance_adapter",
    "a2a_hardware_router",
    "a2a_hibernate",
    "a2a_idempotency",
    "a2a_idle_guard",
    "a2a_immune",
    "a2a_knowledge_distill",
    "a2a_latent_comm",
    "a2a_metrics",
    "a2a_negotiation",
    "a2a_protocol_gateway",
    "a2a_agent_blocklist",
    "a2a_red_team",
    "a2a_saga",
    "a2a_security",
    "a2a_temporal_admission",
    "a2a_tracing",
    "a2a_vector_reputation",
    "a2a_voting",
    "a2a_work_steal",
    "arbitrator",
    "cascade_guard",
    "conflict_detector",
    "construction_verifier",
    "deadlock_guard",
    "livelock_detector",
    "semantic_diff",
    "session_smuggling_defense",
    "spec_sync",
    "supervisor",
]

__version__ = "0.10.0"

_SUBMODULES = [
    "a2a_hardware_router",
    "a2a_metrics",
]


def __getattr__(name):
    if name in _SUBMODULES:
        import importlib

        return importlib.import_module(f"zephyr.infrastructure.a2a_protocol.layer3_coordination.{name}")
    raise AttributeError(f"module 'zephyr.infrastructure.a2a_protocol.layer3_coordination' has no attribute {name!r}")
