# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared_core/blueprint.md | §
# [MODULE] zephyr.shared.foundation.migration
# [DOMAIN] D_SHARED
# [DEPENDENCIES] zephyr.shared.utils.migration
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-SHR_migration | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] permanent

"""
migration.py —— Re-export wrapper -> canonical: zephyr.shared.utils.migration

Backward-compatible top-level alias. Canonical implementation at utils/migration.py.
Edit utils/migration.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.utils.migration import *  # noqa: F403
