"""MOD-INF-026 §25 — Git 历史元数据提取引擎。

GitMetadataExtractor: git log --follow + --numstat → GitAssetMetadata。
不读文件内容，只读 git metadata。对标 CodePulse / GitPrime 工程智能。
"""

from __future__ import annotations

import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from pydantic import BaseModel, Field


class GitCommitInfo(BaseModel):
    sha: str
    author: str
    date: datetime
    message: str
    lines_added: int = 0
    lines_deleted: int = 0


class GitAssetMetadata(BaseModel):
    file_path: str
    first_commit_sha: str = ""
    first_commit_date: Optional[datetime] = None
    last_commit_sha: str = ""
    last_commit_date: Optional[datetime] = None
    total_commits: int = 0
    authors: list[str] = Field(default_factory=list)
    primary_author: str = ""
    ai_commits_ratio: float = 0.0
    lines_added_total: int = 0
    lines_deleted_total: int = 0
    net_lines: int = 0
    churn_rate: float = 0.0
    bug_fix_commits: int = 0
    co_changed_files: list[str] = Field(default_factory=list)
    co_changed_count: int = 0


_AI_COMMIT_PATTERNS = re.compile(
    r"\[AI\]|\[agent\]|\[auto\]|generated by|auto-generated|ai-session|trae|claude|copilot",
    re.IGNORECASE,
)
_BUG_FIX_PATTERNS = re.compile(r"\b(fix|bug|hotfix|patch)\b", re.IGNORECASE)


class GitMetadataExtractor:

    def __init__(self, project_root: Path) -> None:
        self._root = project_root

    def extract(self, file_path: str) -> Optional[GitAssetMetadata]:
        log = self._run_git_log(file_path)
        if not log:
            return None

        current_lines = self._current_lines(file_path)

        authors_list = list(dict.fromkeys(c.author for c in log))
        primary = max(set(c.author for c in log), key=lambda a: sum(1 for c in log if c.author == a)) if log else ""

        total_added = sum(c.lines_added for c in log)
        total_deleted = sum(c.lines_deleted for c in log)
        total_churn = total_added + total_deleted

        co_changed = self._find_co_changed(file_path)

        return GitAssetMetadata(
            file_path=file_path,
            first_commit_sha=log[-1].sha if log else "",
            first_commit_date=log[-1].date if log else None,
            last_commit_sha=log[0].sha if log else "",
            last_commit_date=log[0].date if log else None,
            total_commits=len(log),
            authors=authors_list,
            primary_author=primary,
            ai_commits_ratio=sum(1 for c in log if self._is_ai_commit(c.message)) / max(1, len(log)),
            lines_added_total=total_added,
            lines_deleted_total=total_deleted,
            net_lines=total_added - total_deleted,
            churn_rate=total_churn / max(1, current_lines),
            bug_fix_commits=sum(1 for c in log if _BUG_FIX_PATTERNS.search(c.message)),
            co_changed_files=[f for f, _ in co_changed[:5]],
            co_changed_count=len(co_changed),
        )

    def _run_git_log(self, file_path: str) -> list[GitCommitInfo]:
        try:
            result = subprocess.run(
                ["git", "log", "--follow", "--numstat", "--format=%H|%an|%ai|%s", "--", file_path],
                capture_output=True, text=True, cwd=str(self._root),
                timeout=30,
            )
        except (subprocess.TimeoutExpired, FileNotFoundError):
            return []

        if result.returncode != 0:
            return []

        return self._parse_log_output(result.stdout)

    def _parse_log_output(self, output: str) -> list[GitCommitInfo]:
        commits: list[GitCommitInfo] = []
        lines = output.strip().split("\n")

        current: Optional[dict] = None  # type: ignore[type-arg]

        for line in lines:
            if not line.strip():
                continue

            if "|" in line and "@" not in line.split("|", 2)[1] if len(line.split("|")) >= 2 else False:
                continue

            parts = line.split("|", 3)
            if len(parts) >= 4:
                if current:
                    commits.append(GitCommitInfo(**current))
                current = {
                    "sha": parts[0],
                    "author": parts[1],
                    "date": self._parse_date(parts[2].strip()),
                    "message": parts[3].strip(),
                    "lines_added": 0,
                    "lines_deleted": 0,
                }
            elif current and "\t" in line:
                parts_ns = line.split("\t")
                if len(parts_ns) >= 3:
                    try:
                        current["lines_added"] += int(parts_ns[0]) if parts_ns[0] != "-" else 0
                        current["lines_deleted"] += int(parts_ns[1]) if parts_ns[1] != "-" else 0
                    except ValueError:
                        pass

        if current:
            commits.append(GitCommitInfo(**current))

        return commits

    @staticmethod
    def _parse_date(date_str: str) -> datetime:
        try:
            return datetime.strptime(date_str.strip()[:19], "%Y-%m-%d %H:%M:%S").replace(tzinfo=timezone.utc)
        except ValueError:
            return datetime.min.replace(tzinfo=timezone.utc)

    def _current_lines(self, file_path: str) -> int:
        full = self._root / file_path
        if not full.exists():
            return 0
        try:
            return len(full.read_text(encoding="utf-8", errors="ignore").split("\n"))
        except (OSError, PermissionError):
            return 0

    @staticmethod
    def _is_ai_commit(message: str) -> bool:
        return bool(_AI_COMMIT_PATTERNS.search(message))

    def _find_co_changed(self, file_path: str) -> list[tuple[str, str]]:
        try:
            result = subprocess.run(
                ["git", "log", "--follow", "--name-only", "--format=COMMIT %H", "--", file_path],
                capture_output=True, text=True, cwd=str(self._root),
                timeout=15,
            )
        except (subprocess.TimeoutExpired, FileNotFoundError):
            return []

        if result.returncode != 0:
            return []

        counter: dict[str, int] = {}
        current_commit = ""

        for line in result.stdout.strip().split("\n"):
            if line.startswith("COMMIT "):
                current_commit = line[7:].strip()
                continue
            if line.strip() and current_commit and line.strip() != file_path:
                counter[line.strip()] = counter.get(line.strip(), 0) + 1

        return sorted(counter.items(), key=lambda x: x[1], reverse=True)
