# [A_module] module_id=MOD-INT_backpressure | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] task_bound
"""
Auto-generated contracts package — backpressure

Generated by: scripts/governance/d5_architecture/generate_contracts.py
"""

from zephyr.integration.shared_08.contracts.backpressure.pause import BackpressurePause
from zephyr.integration.shared_08.contracts.backpressure.resume import BackpressureResume
from zephyr.integration.shared_08.contracts.backpressure.throttle import BackpressureThrottle

__all__ = [
    "BackpressurePause",
    "BackpressureResume",
    "BackpressureThrottle",
    "pause",
    "resume",
    "throttle",
]
