# [BLUEPRINT] MOD-KB-001 | docs/03_modules/_domain_knowledge/knowledge_base/blueprint.md | §
# [MODULE] zephyr.governance.kb
# [DOMAIN] D_GOV_KB
# [DEPENDENCIES] aggregates 26 submodules (see __all__)
# [CONSUMERS] zephyr.research.*; zephyr.knowledge.*
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] KB 知识引擎入口包——聚合子模块符号；新增子模块 MUST 在 __all__ 登记
# [MODIFY-GUARD] 新增子模块 MUST 在 __all__ 登记；shim 文件禁止定义新符号
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-DAT_kb | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] permanent

__all__ = [
    "ACTIVE_DIR_NAME",
    "ALLOWED_EXTENSIONS",
    "APPROVED_LABELS",
    "AUTO_ACTIVATE_THRESHOLD",
    "BEST_PRACTICES_DIR_NAME",
    "BLACKLIST_PATTERNS",
    "CREATE_INDEX_SQL",
    "CREATE_TABLE_SQL",
    "DEFAULT_RERANK_MODEL",
    "DEFAULT_SCORE_THRESHOLD",
    "DEFAULT_TOP_K",
    "EXTRACTION_TEMPLATES",
    "FUTURE_DIR_NAME",
    "HIGH_VALUE_THRESHOLD",
    "LESSONS_DIR_NAME",
    "MIN_CONTENT_CHARS",
    "NOISE_HEADINGS",
    "PATTERN_PII",
    "PATTERN_SHA",
    "PATTERN_TIMESTAMP",
    "REJECT_THRESHOLD",
    "REQUIRED_FRONTMATTER_FIELDS",
    "SCORING_DIMENSIONS",
    "VALID_DOC_TYPES",
    "VALID_LAYERS",
    "VALUE_SCORE_THRESHOLD",
    "ActivateGate",
    "ActivateResult",
    "AnalyzeGate",
    "AnalyzeResult",
    "BatchIngestEntry",
    "BatchIngestReport",
    "BatchIngestor",
    "Bootstrap",
    "BootstrapChunk",
    "BootstrapConfig",
    "BootstrapResult",
    "CheckResult",
    "CheckStatus",
    "DriftReport",
    "EmbeddingMigrator",
    "EmbeddingVersion",
    "ExtractGate",
    "ExtractResult",
    "FactChecker",
    "FactResult",
    "FreezeCircuitBreaker",
    "FreezeMode",
    "FreezeReason",
    "FreezeRecord",
    "GraphValidator",
    "HashEntry",
    "InMemoryMemoryBackend",
    "IngestGate",
    "IngestResult",
    "IntegrityGuard",
    "LBEntry",
    "LBStatus",
    "LoadBearingWall",
    "Manifest",
    "MemoryBackend",
    "MemoryBackendError",
    "MemoryRecord",
    "MigrationCheckpoint",
    "MigrationPlan",
    "MigrationResult",
    "MigrationStatus",
    "OperationType",
    "PreFlightResult",
    "QuietPeriodMonitor",
    "QuietPeriodReport",
    "RerankedHit",
    "Reranker",
    "RiskLevel",
    "SafetyBrake",
    "SelfTest",
    "SelfTestReport",
    "TombstoneEntry",
    "TombstoneManager",
    "VMSMemoryBackend",
    "ValidationIssue",
    "ValidationReport",
    "ValidationSeverity",
    "WallReport",
    "_backend_protocol",
    "batch_ingest",
    "bootstrap",
    "build_kb_gate_eval_task",
    "classify_category",
    "classify_chunk",
    "create_vms_backend",
    "discover_document_sources",
    "embedding_migrate",
    "freeze",
    "graph_validator",
    "ingest",
    "integrity",
    "kb_gate_task",
    "ke_tombstone",
    "load_bearing",
    "logger",
    "logger",
    "logger",
    "logger",
    "logger",
    "logger",
    "logger",
    "logger",
    "main",
    "main",
    "main",
    "main",
    "main",
    "main",
    "main",
    "main",
    "quiet_period_monitor",
    "rerank_batch",
    "reranker",
    "run_bootstrap",
    "safety_brake",
    "segment_document",
    "self_test",
    "unified_memory_api",
    "verify",
    "vms_memory_backend",
'citation_walker', 'embedding_version_lock', 'fragmentation_index', 'ke_justification', 'knowledge_distiller', 'knowledge_engine', 'pattern_library']
