"""G1: 从 depgraph.db arch_directory_tree 表生成项目物理路径树状图(中英文)输出到generated/

[BLUEPRINT] ARCHITECTURE-DIAGRAM-PLAN | docs/02_enterprise_architecture/architecture_diagram_construction_plan.md | §4.4
[MODULE] scripts.governance.d5_architecture.generators.generate_path_tree
[INVARIANTS] 输出幂等(相同输入→相同输出);只读depgraph.db;输出到generated/目录
[MODIFY-GUARD] 修改需通过DM-200910任务卡或后续维护任务卡
[CONSUMERS] CI自动触发;人工查看generated/path_tree_zh.md+path_tree_en.md
[STABILITY] evolving
[SAFETY] L
[AI_AUTONOMY] ai_modifiable
[ERROR_CONTRACT] depgraph.db不存在→exit 1;查询失败→exit 2
[TESTS] tests/test_dm200910_generators.py
[DOMAIN] D-GOVERNANCE
"""

from __future__ import annotations

import argparse
import os
import sqlite3
import sys
from datetime import datetime
from pathlib import Path

DEPGRAPH_DB = Path("D:/ZephyrAlpha/data/databases/depgraph.db")
OUTPUT_DIR = Path("D:/ZephyrAlpha/docs/02_enterprise_architecture/1_全局架构图")


def build_tree_rows(conn: sqlite3.Connection) -> list[dict]:
    """从 arch_directory_tree 表查询所有目录记录，按 path 排序。"""
    cur = conn.execute(
        "SELECT path, parent_path, path_type, domain_id, build_status, design_maturity "
        "FROM arch_directory_tree WHERE path_type='directory' ORDER BY path"
    )
    rows = []
    for r in cur.fetchall():
        rows.append(
            {
                "path": r[0] or "",
                "parent_path": r[1] or "",
                "path_type": r[2] or "",
                "domain_id": r[3] or "",
                "build_status": r[4] or "",
                "design_maturity": r[5] or "",
            }
        )
    return rows


def build_tree_structure(rows: list[dict]) -> dict:
    """将扁平记录列表构建为嵌套树结构。

    返回: {path: {"children": set(), "domain_id": str, "data": dict}}
    """
    tree: dict[str, dict] = {}
    for row in rows:
        path = row["path"]
        if not path:
            continue
        tree[path] = {
            "children": set(),
            "domain_id": row["domain_id"],
            "data": row,
        }
    # 建立 parent->children 关系
    for path, node in tree.items():
        parent = node["data"]["parent_path"]
        if parent and parent in tree:
            tree[parent]["children"].add(path)
    return tree


def render_tree(tree: dict, root_path: str, prefix: str, lines: list[str], lang: str) -> None:
    """递归渲染树状图。"""
    if root_path not in tree:
        return
    node = tree[root_path]
    # 显示当前节点
    display_name = root_path
    domain = node["domain_id"]
    domain_tag = f" [{domain}]" if domain else ""
    lines.append(f"{prefix}{display_name}{domain_tag}")

    # 递归子节点
    children = sorted(node["children"])
    for i, child in enumerate(children):
        is_last = i == len(children) - 1
        child_prefix = prefix + "    " if is_last else prefix + "│   "
        # 子节点显示时用相对路径
        child_name = child
        if root_path and child.startswith(root_path):
            child_name = child[len(root_path) :].lstrip("/")
        child_domain = tree[child]["domain_id"]
        child_tag = f" [{child_domain}]" if child_domain else ""
        connector = "└── " if is_last else "├── "
        lines.append(f"{prefix}{connector}{child_name}{child_tag}")
        # 递归孙节点
        grandchildren = sorted(tree[child]["children"])
        for j, grandchild in enumerate(grandchildren):
            is_last_grand = j == len(grandchildren) - 1
            render_tree(tree, grandchild, child_prefix, lines, lang)


def find_roots(tree: dict) -> list[str]:
    """找到所有根节点（没有父节点或父节点不在树中的节点）。"""
    roots = []
    for path, node in tree.items():
        parent = node["data"]["parent_path"]
        if not parent or parent not in tree:
            roots.append(path)
    return sorted(roots)


def generate_path_tree(lang: str, conn: sqlite3.Connection) -> str:
    """生成路径树内容。

    lang: 'zh' 或 'en'
    """
    rows = build_tree_rows(conn)
    tree = build_tree_structure(rows)
    roots = find_roots(tree)

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    if lang == "zh":
        header = f"""# ZephyrAlpha 项目物理路径树

> 本文档由 generate_path_tree.py 从 depgraph.db 自动生成
> 最后更新: {now}
> 数据源: depgraph.db arch_directory_tree 表（仅目录）

## 完整路径树

"""
        stats_title = "## 统计"
        total_dirs_label = "总目录数"
        total_domains_label = "涉及域数"
    else:
        header = f"""# ZephyrAlpha Project Physical Path Tree

> Auto-generated by generate_path_tree.py from depgraph.db
> Last updated: {now}
> Data source: depgraph.db arch_directory_tree table (directories only)

## Complete Path Tree

"""
        stats_title = "## Statistics"
        total_dirs_label = "Total directories"
        total_domains_label = "Domains involved"

    lines = [header.rstrip()]

    # 限制根节点数量，避免输出过大
    MAX_ROOTS = 50
    displayed_roots = roots[:MAX_ROOTS]
    if len(roots) > MAX_ROOTS:
        lines.append(f"\n> (仅显示前 {MAX_ROOTS} 个根节点，共 {len(roots)} 个)\n")

    for root in displayed_roots:
        render_tree(tree, root, "", lines, lang)
        lines.append("")

    # 统计
    domains_involved = set()
    for row in rows:
        if row["domain_id"]:
            domains_involved.add(row["domain_id"])

    lines.append(stats_title)
    lines.append(f"- {total_dirs_label}: {len(rows)}")
    lines.append(f"- {total_domains_label}: {len(domains_involved)}")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    """入口：生成中英文物理路径树。"""
    parser = argparse.ArgumentParser(description="G1: 生成项目物理路径树(中英文)")
    parser.add_argument("--output-dir", type=str, default=str(OUTPUT_DIR), help="输出目录")
    parser.add_argument("--lang", type=str, choices=["zh", "en", "both"], default="both", help="生成语言")
    args = parser.parse_args()

    if not DEPGRAPH_DB.exists():
        print(f"ERROR: depgraph.db 不存在: {DEPGRAPH_DB}", file=sys.stderr)
        sys.exit(1)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    conn = sqlite3.connect(str(DEPGRAPH_DB))
    try:
        if args.lang in ("zh", "both"):
            content = generate_path_tree("zh", conn)
            out_path = output_dir / "path_tree_zh.md"
            out_path.write_text(content, encoding="utf-8")
            print(f"[OK] 生成 {out_path} ({len(content)} 字符)")

        if args.lang in ("en", "both"):
            content = generate_path_tree("en", conn)
            out_path = output_dir / "path_tree_en.md"
            out_path.write_text(content, encoding="utf-8")
            print(f"[OK] 生成 {out_path} ({len(content)} 字符)")
    finally:
        conn.close()


if __name__ == "__main__":
    main()
