# [A_test] module_id: MOD-GOV_metadata | layer=test | stability=volatile | safety=L | ai_autonomy=ai_modifiable
# [BLUEPRINT] MOD-INF-026 | docs/03_modules/_domain_infrastructure_operations/asset_inventory/blueprint.md | §
# [MODULE] tests.test_metadata
# [INVARIANTS] GitMetadataExtractor.extract returns GitAssetMetadata or None; MultiIDERuleGenerator generates files
# [MODIFY-GUARD] none
# [CONSUMERS] pytest
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT] subprocess.TimeoutExpired handled gracefully
# [TESTS] tests/test_metadata.py
# [TTL] task_bound

from __future__ import annotations

from zephyr.infrastructure.asset_inventory.metadata import (
    GitAssetMetadata,
    GitCommitInfo,
    GitMetadataExtractor,
    MultiIDERuleGenerator,
)


class TestGitCommitInfo:
    def test_create(self):
        from datetime import UTC, datetime

        c = GitCommitInfo(
            sha="abc123",
            author="test",
            date=datetime.now(UTC),
            message="test commit",
        )
        assert c.sha == "abc123"
        assert c.lines_added == 0
        assert c.lines_deleted == 0


class TestGitAssetMetadata:
    def test_defaults(self):
        m = GitAssetMetadata(file_path="src/test.py")
        assert m.total_commits == 0
        assert m.authors == []
        assert m.ai_commits_ratio == 0.0


class TestGitMetadataExtractorInstantiation:
    def test_create(self, tmp_path):
        ext = GitMetadataExtractor(project_root=tmp_path)
        assert ext.root == tmp_path


class TestGitMetadataExtractorExtract:
    def test_extract_nonexistent_file(self, tmp_path):
        ext = GitMetadataExtractor(project_root=tmp_path)
        result = ext.extract("nonexistent.py")
        assert result is None

    def test_extract_from_git_repo(self, tmp_path):
        import subprocess

        subprocess.run(["git", "init"], cwd=str(tmp_path), capture_output=True, timeout=10)
        subprocess.run(
            ["git", "config", "user.email", "test@test.com"], cwd=str(tmp_path), capture_output=True, timeout=10
        )
        subprocess.run(["git", "config", "user.name", "Test"], cwd=str(tmp_path), capture_output=True, timeout=10)
        (tmp_path / "test.py").write_text("x = 1", encoding="utf-8")
        subprocess.run(["git", "add", "."], cwd=str(tmp_path), capture_output=True, timeout=10)
        subprocess.run(["git", "commit", "-m", "initial"], cwd=str(tmp_path), capture_output=True, timeout=10)
        ext = GitMetadataExtractor(project_root=tmp_path)
        result = ext.extract("test.py")
        if result is not None:
            assert result.total_commits >= 1
            assert result.file_path == "test.py"


class TestGitMetadataExtractorIsAiCommit:
    def test_ai_commit(self):
        assert GitMetadataExtractor.is_ai_commit("[AI] auto fix") is True
        assert GitMetadataExtractor.is_ai_commit("generated by copilot") is True

    def test_human_commit(self):
        assert GitMetadataExtractor.is_ai_commit("fix typo") is False


class TestGitMetadataExtractorParseDate:
    def test_valid_date(self):
        dt = GitMetadataExtractor.parse_date("2026-05-22 10:30:00")
        assert dt.year == 2026
        assert dt.month == 5

    def test_invalid_date(self):
        dt = GitMetadataExtractor.parse_date("invalid")
        assert dt == dt


class TestMultiIDERuleGeneratorInstantiation:
    def test_create(self, tmp_path):
        gen = MultiIDERuleGenerator(project_root=tmp_path)
        assert gen.root == tmp_path


class TestMultiIDERuleGeneratorGenerateCursorRules:
    def test_generate(self, tmp_path):
        gen = MultiIDERuleGenerator(project_root=tmp_path)
        out = gen.generate_cursor_rules(output_path=tmp_path / ".cursorrules")
        assert out.exists()
        content = out.read_text(encoding="utf-8")
        assert "ZephyrAlpha" in content

    def test_generate_with_project_rules(self, tmp_path):
        rules_dir = tmp_path / ".trae" / "rules"
        rules_dir.mkdir(parents=True)
        (rules_dir / "project_rules.md").write_text("RULE-ZERO: always lock", encoding="utf-8")
        gen = MultiIDERuleGenerator(project_root=tmp_path)
        out = gen.generate_cursor_rules(output_path=tmp_path / ".cursorrules")
        content = out.read_text(encoding="utf-8")
        assert "RULE-ZERO" in content


class TestMultiIDERuleGeneratorGenerateTraeRules:
    def test_generate(self, tmp_path):
        gen = MultiIDERuleGenerator(project_root=tmp_path)
        out = gen.generate_trae_rules(output_path=tmp_path / "trae_rules.md")
        assert out.exists()
        content = out.read_text(encoding="utf-8")
        assert "Trae" in content


class TestMultiIDERuleGeneratorGenerateVscodeRules:
    def test_generate(self, tmp_path):
        gen = MultiIDERuleGenerator(project_root=tmp_path)
        out = gen.generate_vscode_rules(output_path=tmp_path / "copilot.md")
        assert out.exists()
        content = out.read_text(encoding="utf-8")
        assert "Copilot" in content


class TestMultiIDERuleGeneratorGenerateJetbrainsRules:
    def test_generate(self, tmp_path):
        gen = MultiIDERuleGenerator(project_root=tmp_path)
        out = gen.generate_jetbrains_rules(output_path=tmp_path / "asset-inventory.xml")
        assert out.exists()
        content = out.read_text(encoding="utf-8")
        assert "AssetInventoryRules" in content


class TestMultiIDERuleGeneratorGenerateAll:
    def test_generate_all(self, tmp_path):
        gen = MultiIDERuleGenerator(project_root=tmp_path)
        results = gen.generate_all()
        assert isinstance(results, dict)
        assert len(results) > 0
        for key, path in results.items():
            assert path.exists()
