# [A_module] module_id=MOD-GOV_behavioral_auditor | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [BLUEPRINT] MOD-INF-033 | docs/03_modules/_cross_layer/behavioral-auditor/blueprint.md
from __future__ import annotations

from . import (
    absence_manager,
    ai_context_injector,
    alert_router,
    architecture_contracts,
    architecture_principles,
    backcompat_checker,
    baseline_manager,
    baseline_poisoning_guard,
    benchmark_integrity,
    brain_integration,
    canary_controller,
    cascade_detector,
    code_review_ai,
    config_consistency,
    cross_env_consistency,
    cross_module_score,
    dashboard,
    data_classification,
    data_lifecycle,
    data_quality,
    data_source_reliability,
    dependency_manager,
    detector_dispatcher,
    drift_training,
    file_attr_checker,
    gate_persistence,
    git_bisector,
    gitignore_auditor,
    handoff_manager,
    headless_scanner,
    incremental_scanner,
    integration_test_runner,
    ml_engineering,
    model_drift_monitor,
    naming_magic_checker,
    performance_baseline,
    python_compat,
    reconciler,
    regime_detector,
    resource_guard,
    roi_engine,
    rollback_bridge,
    runbook_generator,
    scan_mutex,
    state_machine,
    suppression_learner,
    symlink_checker,
    system_topology,
    tamper_proof_audit,
    test_fixture_checker,
    trend_analyzer,
)

"""[BLUEPRINT] MOD-INF-033 | docs/03_modules/_cross_layer/behavioral-auditor/blueprint.md

[MODULE] zephyr.governance.behavioral_auditor

[INVARIANTS] 漂移检测结果不可伪造;基线不可被污染;检测器注册表不可绕过

[MODIFY-GUARD] docs/03_modules/infrastructure_runtime_integration/drift-detector/blueprint.md

[CONSUMERS] zephyr.integration.runtime_core; zephyr.security.access_control; zephyr.infrastructure.pipeline

[STABILITY] stable

[SAFETY] H

[AI_AUTONOMY] human_gated

[ERROR_CONTRACT] 异常必须包含 detector_id 和 drift_type

[TESTS] tests/test_behavioral_auditor.py

behavioral-auditor — MOD-INF-023 · 行为审计器 / 漂移检测引擎"""

from zephyr.behavioral_audit.absence_manager import (
    AbsenceManagerConfig,
    EscalationEntry,
    OwnerStatus,
    check_absence,
    detect_owner_return,
    escalate_if_absent,
    record_activity,
    set_severity_limit,
)
from zephyr.behavioral_audit.ai_construction_detectors import AIConstructionDetectors
from zephyr.behavioral_audit.ai_context_injector import (
    HealthSnapshot,
    InjectedContext,
    InjectionLevel,
    TopDriftItem,
    build_health_snapshot,
    build_top_drifts,
    inject_full,
    inject_minimal,
    inject_standard,
)
from zephyr.behavioral_audit.alert_router import Alert, AlertRouter
from zephyr.behavioral_audit.backcompat_checker import (
    CompatBreakEvent,
    FunctionSignature,
    compare_signatures,
    detect_intentional_breaks,
    extract_signatures,
    find_renamed_functions,
    run_backcompat_check,
    scan_impact,
)
from zephyr.behavioral_audit.baseline_manager import BaselineManager, DiffReport
from zephyr.behavioral_audit.baseline_poisoning_guard import (
    BaselineSnapshot,
    HashChainEntry,
    MultiBaselineVote,
    build_hash_chain,
    cross_validate_baseline,
    generate_integrity_manifest,
    multi_baseline_vote,
    verify_hash_chain,
)
from zephyr.behavioral_audit.canary_controller import (
    CanaryComparison,
    CanaryConfig,
    CanaryResult,
    CanaryRun,
    classify_event_id,
    get_canary_history,
    promote_detector,
    rollback_detector,
    run_canary,
)
from zephyr.behavioral_audit.cascade_detector import (
    CascadeAlert,
    CascadeConfig,
    CascadeEvent,
    detect_cascade,
    dry_run_impact_analysis,
    is_auto_fix_paused,
)
from zephyr.behavioral_audit.chaos_injector import (
    ChaosInjection,
    ChaosInjectionType,
    ChaosMetrics,
    ChaosPhase,
    ChaosResult,
    import_hallucination,
    inject_fake_todo_bomb,
    inject_path_rename,
    inject_yaml_field_flip,
    run_chaos_experiment,
)
from zephyr.behavioral_audit.cold_start import (
    ColdStartResult,
    bootstrap,
    detect_missing_env,
    init_database,
    init_directories,
    session_entry_activate,
)
from zephyr.behavioral_audit.config_consistency import (
    ConfigAuditReport,
    ConfigConflict,
    ConfigSource,
    detect_conflicts,
    extract_hardcoded_defaults,
    generate_config_sync,
    parse_env_config,
    parse_yaml_config,
    run_config_audit,
)
from zephyr.behavioral_audit.contract_drift_detector import DriftAlert as ContractDriftAlert
from zephyr.behavioral_audit.contract_drift_detector import detect_contract_drift
from zephyr.behavioral_audit.correlation_engine import CorrelationEngine, CorrelationReport
from zephyr.behavioral_audit.credibility_engine import CredibilityEngine, CredibilityScore
from zephyr.behavioral_audit.cross_module_score import (
    CrossModuleReport,
    CrossModuleScorer,
    ModuleScore,
)
from zephyr.behavioral_audit.dashboard import Dashboard, DashboardData
from zephyr.behavioral_audit.detector_dispatcher import (
    DetectorDispatcher,
    DetectorResult,
    ResultCache,
    get_max_parallel_for_level,
)
from zephyr.behavioral_audit.drift_engine import (
    build_report,
    load_detector_registry,
    push_to_evolution_engine,
    scan,
    scan_on_commit,
    scan_phase_gate,
    scheduled_deep,
    scheduled_light,
)
from zephyr.behavioral_audit.drift_hotfix_bypass import HotfixAuditEntry, HotfixBypass
from zephyr.behavioral_audit.drift_infrastructure import (
    CheckpointWriter,
    EnvDiffReport,
    MaintenanceWindow,
    PartialDeploymentRecord,
    RecoveryManager,
    check_budget_for_gate,
    check_large_diff,
    consume_budget,
    declare_maintenance_window,
    detect_partial_deployment,
    differential_detection,
    get_maintenance_window,
    get_or_create_budget,
    register_env_tags,
)
from zephyr.behavioral_audit.drift_models import (
    BaselineSnapshot,
    BreakingChange,
    BulkDriftEvent,
    CascadeEvent,
    ConfigConflict,
    Detector,
    DriftBudget,
    DriftEvent,
    DriftReport,
    DriftState,
    ForensicsReport,
    OrphanClassification,
    OrphanFile,
    Runbook,
    ScanLevel,
    ScanResult,
    Severity,
)
from zephyr.behavioral_audit.drift_result_types import (
    DBSchemaDriftResult,
    DepVersionDriftResult,
    DocCodeCoevolutionResult,
    KnowledgeGraphSyncResult,
    SecurityPolicyDriftResult,
    SemanticDriftResult,
    TestCoverageDriftResult,
    detect_concept_cardinality,
    detect_db_schema_drift,
    detect_dep_version_drift,
    detect_doc_code_coevolution,
    detect_enum_value_sync,
    detect_knowledge_graph_sync,
    detect_ownership_consistency,
    detect_security_policy_drift,
    detect_test_coverage_drift,
)
from zephyr.behavioral_audit.drift_training import (
    AITrainingLoopResult,
    CrossLanguageConfig,
    DriftTrainingPattern,
    detect_ai_training_loop,
    detect_cross_language_drift,
    detect_python_dead_code,
    extract_training_patterns,
    inject_patterns_to_prompt,
    parse_python_imports,
    parse_python_public_api,
    track_training_effectiveness,
)
from zephyr.behavioral_audit.events import DriftEvent, DriftState, DriftType
from zephyr.behavioral_audit.file_attr_checker import (
    FileAttrIssue,
    capture_baseline,
    check_encoding,
    check_size_anomaly,
)
from zephyr.behavioral_audit.forensics_engine import (
    ForensicsConfig,
    ForensicsReport,
    ForensicsTimelineEntry,
    generate_forensics_report,
    git_checkout_snapshot,
    replay_baseline_history,
    serialize_report,
)
from zephyr.behavioral_audit.gate_persistence import GatePersistence
from zephyr.behavioral_audit.git_bisector import BisectResult, GitBisector
from zephyr.behavioral_audit.gitignore_auditor import (
    GitignoreAudit,
    audit_gitignore,
    find_over_ignored_critical,
    find_uncovered_types,
    find_untracked_generated,
    parse_gitignore,
)
from zephyr.behavioral_audit.handoff_manager import (
    FileIntegrityRecord,
    HandoffPackage,
    abort_handoff,
    build_handoff_package,
    load_package,
    resume_workflow,
    serialize_package,
    verify_integrity,
)
from zephyr.behavioral_audit.headless_scanner import (
    HeadlessDiffEntry,
    InterruptLog,
    headless_scan_light,
    parse_interrupt_log,
)
from zephyr.behavioral_audit.incremental_scanner import (
    ChangeSet,
    DetectorFileMapping,
    FileChange,
    IncrementalScanner,
)
from zephyr.behavioral_audit.naming_magic_checker import NamingMagicAlert, scan_naming_magic
from zephyr.behavioral_audit.orphan_scanner import (
    OrphanResource,
    find_orphan_data,
    find_orphan_docs,
    find_orphan_scripts,
    scan_orphan_resources,
)
from zephyr.behavioral_audit.python_compat import (
    PythonCompatIssue,
    auto_fix_compat,
    generate_compat_report,
    scan_python_compat,
)
from zephyr.behavioral_audit.reconciler import AutoFixer, FixSnapshot, Suggestion
from zephyr.behavioral_audit.resource_guard import (
    DegradationLevel,
    ResourceLimits,
    ResourceSnapshot,
    ResourceStatus,
    apply_degradation,
    guard_loop,
    is_guard_running,
    set_critical_handler,
    snapshot,
    stop_guard_loop,
    validate_scalability,
)
from zephyr.behavioral_audit.roi_engine import ROIEngine, ROIScore
from zephyr.behavioral_audit.rollback_bridge import DriftRollbackBridge
from zephyr.behavioral_audit.runbook_generator import (
    build_runbook_frontmatter,
    generate_bulk_runbook,
    generate_runbook,
)
from zephyr.behavioral_audit.scan_mutex import QueuedScan, ScanLockRecord, ScanMutex
from zephyr.behavioral_audit.self_check import (
    bootstrap_self_check,
    check_core_files,
    check_registry_parsable,
    run_self_check,
    sha256_file,
)
from zephyr.behavioral_audit.suppression_learner import SuppressionLearner, SuppressionRule
from zephyr.behavioral_audit.symlink_checker import SymlinkIssue, check_broken_symlinks
from zephyr.behavioral_audit.tamper_proof_audit import (
    AnomalyAlert,
    AuditRecord,
    count_states,
    detect_anomalies,
    generate_audit_log,
    setup_append_only,
    snapshot_event_hash,
)
from zephyr.behavioral_audit.test_fixture_checker import (
    FixtureDriftEvent,
    run_fixture_check,
    scan_expected_output_drift,
    scan_fixture_schema_drift,
    scan_mock_target_drift,
)
from zephyr.behavioral_audit.trend_analyzer import TrendAlert, TrendAnalyzer, TrendMetrics
from zephyr.security.access_control.auto_fix_engine_03.state_machine import (
    DriftEventRecord,
    DriftStateMachine,
    InvalidTransitionError,
)

__all__ = [
    "AIConstructionDetectors",
    "AITrainingLoopResult",
    "AbsenceManagerConfig",
    "Alert",
    "AlertRouter",
    "AnomalyAlert",
    "AuditRecord",
    "AutoFixer",
    "BaselineManager",
    "BaselineSnapshot",
    "BisectResult",
    "BreakingChange",
    "BulkDriftEvent",
    "CanaryComparison",
    "CanaryConfig",
    "CanaryResult",
    "CanaryRun",
    "CascadeAlert",
    "CascadeConfig",
    "CascadeEvent",
    "ChangeSet",
    "ChaosInjection",
    "ChaosInjectionType",
    "ChaosMetrics",
    "ChaosPhase",
    "ChaosResult",
    "CheckpointWriter",
    "ColdStartResult",
    "CompatBreakEvent",
    "ConfigAuditReport",
    "ConfigConflict",
    "ConfigSource",
    "ContractDriftAlert",
    "CorrelationEngine",
    "CorrelationReport",
    "CredibilityEngine",
    "CredibilityScore",
    "CrossLanguageConfig",
    "CrossModuleReport",
    "CrossModuleScorer",
    "DBSchemaDriftResult",
    "Dashboard",
    "DashboardData",
    "DegradationLevel",
    "DepVersionDriftResult",
    "Detector",
    "DetectorDispatcher",
    "DetectorFileMapping",
    "DetectorResult",
    "DiffReport",
    "DocCodeCoevolutionResult",
    "DriftBudget",
    "DriftEvent",
    "DriftEventRecord",
    "DriftReport",
    "DriftRollbackBridge",
    "DriftState",
    "DriftStateMachine",
    "DriftTrainingPattern",
    "DriftType",
    "EnvDiffReport",
    "EscalationEntry",
    "FileAttrIssue",
    "FileChange",
    "FileIntegrityRecord",
    "FixSnapshot",
    "FixtureDriftEvent",
    "ForensicsConfig",
    "ForensicsReport",
    "ForensicsTimelineEntry",
    "FunctionSignature",
    "GatePersistence",
    "GitBisector",
    "GitignoreAudit",
    "HandoffPackage",
    "HashChainEntry",
    "HeadlessDiffEntry",
    "HealthSnapshot",
    "HotfixAuditEntry",
    "HotfixBypass",
    "IncrementalScanner",
    "InjectedContext",
    "InjectionLevel",
    "InterruptLog",
    "InvalidTransitionError",
    "KnowledgeGraphSyncResult",
    "MaintenanceWindow",
    "ModuleScore",
    "MultiBaselineVote",
    "NamingMagicAlert",
    "OrphanClassification",
    "OrphanFile",
    "OrphanResource",
    "OwnerStatus",
    "PartialDeploymentRecord",
    "PythonCompatIssue",
    "QueuedScan",
    "ROIEngine",
    "ROIScore",
    "RecoveryManager",
    "ResourceLimits",
    "ResourceSnapshot",
    "ResourceStatus",
    "ResultCache",
    "Runbook",
    "ScanLevel",
    "ScanLockRecord",
    "ScanMutex",
    "ScanResult",
    "SecurityPolicyDriftResult",
    "SemanticDriftResult",
    "Severity",
    "Suggestion",
    "SuppressionLearner",
    "SuppressionRule",
    "SymlinkIssue",
    "TestCoverageDriftResult",
    "TopDriftItem",
    "TrendAlert",
    "TrendAnalyzer",
    "TrendMetrics",
    "__main__",
    "abort_handoff",
    "absence_manager",
    "ai_construction_detectors",
    "ai_context_injector",
    "alert_router",
    "apply_degradation",
    "architecture_contracts",
    "architecture_principles",
    "audit_gitignore",
    "auto_fix_compat",
    "backcompat_checker",
    "baseline_manager",
    "baseline_poisoning_guard",
    "benchmark_integrity",
    "bootstrap",
    "bootstrap_self_check",
    "brain_integration",
    "build_handoff_package",
    "build_hash_chain",
    "build_health_snapshot",
    "build_report",
    "build_runbook_frontmatter",
    "build_top_drifts",
    "canary_controller",
    "capture_baseline",
    "cascade_detector",
    "chaos_injector",
    "check_absence",
    "check_broken_symlinks",
    "check_budget_for_gate",
    "check_core_files",
    "check_encoding",
    "check_large_diff",
    "check_registry_parsable",
    "check_size_anomaly",
    "classify_event_id",
    "code_review_ai",
    "cold_start",
    "compare_signatures",
    "config_consistency",
    "consume_budget",
    "contract_drift_detector",
    "correlation_engine",
    "count_states",
    "credibility_engine",
    "cross_env_consistency",
    "cross_module_score",
    "cross_validate_baseline",
    "dashboard",
    "data_classification",
    "data_lifecycle",
    "data_quality",
    "data_source_reliability",
    "declare_maintenance_window",
    "dependency_manager",
    "detect_ai_training_loop",
    "detect_anomalies",
    "detect_cascade",
    "detect_concept_cardinality",
    "detect_conflicts",
    "detect_contract_drift",
    "detect_cross_language_drift",
    "detect_db_schema_drift",
    "detect_dep_version_drift",
    "detect_doc_code_coevolution",
    "detect_enum_value_sync",
    "detect_intentional_breaks",
    "detect_knowledge_graph_sync",
    "detect_missing_env",
    "detect_owner_return",
    "detect_ownership_consistency",
    "detect_partial_deployment",
    "detect_python_dead_code",
    "detect_security_policy_drift",
    "detect_test_coverage_drift",
    "detector_dispatcher",
    "differential_detection",
    "drift_engine",
    "drift_hotfix_bypass",
    "drift_infrastructure",
    "drift_models",
    "drift_result_types",
    "drift_training",
    "dry_run_impact_analysis",
    "escalate_if_absent",
    "events",
    "extract_hardcoded_defaults",
    "extract_signatures",
    "extract_training_patterns",
    "file_attr_checker",
    "find_orphan_data",
    "find_orphan_docs",
    "find_orphan_scripts",
    "find_over_ignored_critical",
    "find_renamed_functions",
    "find_uncovered_types",
    "find_untracked_generated",
    "forensics_engine",
    "gate_persistence",
    "generate_audit_log",
    "generate_bulk_runbook",
    "generate_compat_report",
    "generate_config_sync",
    "generate_forensics_report",
    "generate_integrity_manifest",
    "generate_runbook",
    "get_canary_history",
    "get_maintenance_window",
    "get_max_parallel_for_level",
    "get_or_create_budget",
    "git_bisector",
    "git_checkout_snapshot",
    "gitignore_auditor",
    "guard_loop",
    "handoff_manager",
    "headless_scan_light",
    "headless_scanner",
    "import_hallucination",
    "incremental_scanner",
    "init_database",
    "init_directories",
    "inject_fake_todo_bomb",
    "inject_full",
    "inject_minimal",
    "inject_path_rename",
    "inject_patterns_to_prompt",
    "inject_standard",
    "inject_yaml_field_flip",
    "integration_test_runner",
    "is_auto_fix_paused",
    "is_guard_running",
    "load_detector_registry",
    "load_package",
    "ml_engineering",
    "model_drift_monitor",
    "multi_baseline_vote",
    "naming_magic_checker",
    "orphan_scanner",
    "parse_env_config",
    "parse_gitignore",
    "parse_interrupt_log",
    "parse_python_imports",
    "parse_python_public_api",
    "parse_yaml_config",
    "performance_baseline",
    "promote_detector",
    "push_to_evolution_engine",
    "python_compat",
    "reconciler",
    "record_activity",
    "regime_detector",
    "register_env_tags",
    "replay_baseline_history",
    "resource_guard",
    "resume_workflow",
    "roi_engine",
    "rollback_bridge",
    "rollback_detector",
    "run_backcompat_check",
    "run_canary",
    "run_chaos_experiment",
    "run_config_audit",
    "run_fixture_check",
    "run_self_check",
    "runbook_generator",
    "scan",
    "scan_expected_output_drift",
    "scan_fixture_schema_drift",
    "scan_impact",
    "scan_mock_target_drift",
    "scan_mutex",
    "scan_naming_magic",
    "scan_on_commit",
    "scan_orphan_resources",
    "scan_phase_gate",
    "scan_python_compat",
    "scheduled_deep",
    "scheduled_light",
    "self_check",
    "self_test_verifier",
    "serialize_package",
    "serialize_report",
    "session_entry_activate",
    "set_critical_handler",
    "set_severity_limit",
    "setup_append_only",
    "sha256_file",
    "snapshot",
    "snapshot_event_hash",
    "state_machine",
    "stop_guard_loop",
    "suppression_learner",
    "symlink_checker",
    "system_topology",
    "tamper_proof_audit",
    "test_fixture_checker",
    "track_training_effectiveness",
    "trend_analyzer",
    "validate_scalability",
    "verify_hash_chain",
    "verify_integrity",
]
