-- SQLite actual schema snapshot (translation baseline for PG migration)
-- Source: D:\ZephyrAlpha\data\databases\depgraph.db
-- Generated by: scripts/_tmp_export_sqlite_schema.py (P2-T2 action 2)

-- ========== TABLES & VIEWS ==========

-- [view] dep_cycles
CREATE VIEW dep_cycles AS
        WITH RECURSIVE
        cycle_nodes AS (
          SELECT DISTINCT from_node_id AS node_id FROM edges e1
          WHERE EXISTS (
            SELECT 1 FROM edges e2
            WHERE e2.from_node_id = e1.to_node_id
            AND e2.to_node_id = e1.from_node_id
          )
          UNION
          SELECT DISTINCT to_node_id AS node_id FROM edges e1
          WHERE EXISTS (
            SELECT 1 FROM edges e2
            WHERE e2.from_node_id = e1.to_node_id
            AND e2.to_node_id = e1.from_node_id
          )
        )
        SELECT
          n.node_id,
          n.path,
          n.domain_id,
          n.design_maturity
        FROM cycle_nodes c
        JOIN nodes n ON c.node_id = n.node_id
        ORDER BY n.domain_id, n.node_id;

-- [table] _schema_version
CREATE TABLE _schema_version (
        version INTEGER PRIMARY KEY,
        applied_at TEXT NOT NULL,
        description TEXT
    );

-- [table] arch_constraints
CREATE TABLE arch_constraints (
        constraint_id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        constraint_type TEXT NOT NULL,
        from_domain TEXT,
        to_domain TEXT,
        rule_definition TEXT NOT NULL,
        severity TEXT DEFAULT 'hard',
        enforcement TEXT DEFAULT 'gate',
        description TEXT, violation_status TEXT DEFAULT 'open', details TEXT, detected_at TEXT,
        FOREIGN KEY (from_domain) REFERENCES domains(domain_id),
        FOREIGN KEY (to_domain) REFERENCES domains(domain_id)
    );

-- [table] arch_directory_tree
CREATE TABLE "arch_directory_tree" (
    path             TEXT    PRIMARY KEY,
    parent_path      TEXT,
    path_type        TEXT    NOT NULL,
    domain_id        TEXT,
    blueprint_id     TEXT,
    change_policy    TEXT,
    modification_permission TEXT,
    build_status     TEXT    DEFAULT 'unbuilt',
    design_maturity  TEXT    NOT NULL DEFAULT 'design',
    last_scanned     TEXT
);

-- [table] arch_path_mappings
CREATE TABLE arch_path_mappings (
        mapping_id INTEGER PRIMARY KEY AUTOINCREMENT,
        domain_id TEXT NOT NULL,
        path_pattern TEXT NOT NULL,
        path_type TEXT NOT NULL,
        state TEXT NOT NULL DEFAULT 'design',
        covers TEXT,
        aliases TEXT,
        FOREIGN KEY (domain_id) REFERENCES domains(domain_id)
    );

-- [table] blueprint_links
CREATE TABLE blueprint_links (
            blueprint_id       TEXT PRIMARY KEY,
            blueprint_path     TEXT NOT NULL,
            alignment_verified INTEGER DEFAULT 0,
            last_verified      TEXT
        );

-- [table] business_streams
CREATE TABLE business_streams (
            stream_id      TEXT PRIMARY KEY,
            name           TEXT NOT NULL,
            goal           TEXT,
            input          TEXT,
            output         TEXT,
            runtime_plane  TEXT,
            CHECK (runtime_plane IN ('data_plane', 'control_plane', 'management_plane'))
        );

-- [table] contracts
CREATE TABLE contracts (
        contract_id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        provider_domain TEXT NOT NULL,
        consumer_domain TEXT NOT NULL,
        contract_type TEXT NOT NULL,
        schema_definition TEXT,
        version TEXT, promise TEXT, actual_consumer TEXT, fulfillment_status TEXT DEFAULT 'unresolved', gap TEXT, target_phase TEXT, last_reviewed TEXT,
        FOREIGN KEY (provider_domain) REFERENCES domains(domain_id),
        FOREIGN KEY (consumer_domain) REFERENCES domains(domain_id)
    );

-- [table] cross_registry_rules
CREATE TABLE cross_registry_rules (
            rule_id         TEXT PRIMARY KEY,
            title           TEXT NOT NULL,
            fields          TEXT,
            ssot            TEXT NOT NULL,
            consistency     TEXT,
            violation_action TEXT,
            CHECK (consistency IN ('exact', 'derived', 'independent')),
            CHECK (violation_action IN ('block', 'warn', 'log'))
        );

-- [table] derived_identifier_registry
CREATE TABLE derived_identifier_registry (
        derived_type        TEXT NOT NULL,
        source_field        TEXT NOT NULL,
        derived_field       TEXT NOT NULL,
        derivation_rule     TEXT NOT NULL,
        propagation_method  TEXT NOT NULL DEFAULT 'exact_value_map',
        source_doc          TEXT,
        PRIMARY KEY (derived_type, derived_field)
    );

-- [table] domain_dependencies
CREATE TABLE domain_dependencies (
        from_domain TEXT NOT NULL,
        to_domain TEXT NOT NULL,
        edge_count INTEGER DEFAULT 0,
        edge_types TEXT,
        constraint_type TEXT,
        PRIMARY KEY (from_domain, to_domain),
        FOREIGN KEY (from_domain) REFERENCES domains(domain_id),
        FOREIGN KEY (to_domain) REFERENCES domains(domain_id)
    );

-- [table] domain_events
CREATE TABLE domain_events (
        event_id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        source_domain TEXT NOT NULL,
        target_domains TEXT,
        payload_schema TEXT,
        priority TEXT DEFAULT 'P1', event_type TEXT DEFAULT 'domain_event',
        FOREIGN KEY (source_domain) REFERENCES domains(domain_id)
    );

-- [table] domain_mapping
CREATE TABLE domain_mapping (
            mapping_id INTEGER PRIMARY KEY AUTOINCREMENT,
            path_prefix TEXT NOT NULL,
            domain_id TEXT NOT NULL,
            subdomain_id TEXT,
            mapping_type TEXT NOT NULL,
            mapped_at TEXT NOT NULL,
            mapped_by TEXT NOT NULL,
            note TEXT
        );

-- [table] domain_naming_rules
CREATE TABLE domain_naming_rules (
        rule_id      TEXT PRIMARY KEY,
        rule_name    TEXT NOT NULL,
        rule_text    TEXT NOT NULL,
        applies_to   TEXT NOT NULL DEFAULT 'create',
        severity     TEXT NOT NULL DEFAULT 'error',
        example_bad  TEXT,
        example_good TEXT,
        created_at   TEXT NOT NULL,
        source_doc   TEXT
    );

-- [table] domains
CREATE TABLE domains (
        domain_id TEXT PRIMARY KEY,
        domain_name TEXT NOT NULL,
        domain_group TEXT NOT NULL,
        description TEXT,
        ssot_path TEXT,
        current_modules INTEGER DEFAULT 0,
        max_modules INTEGER,
        lifecycle TEXT DEFAULT 'design_only',
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    , build_status TEXT DEFAULT 'unbuilt', modification_permission TEXT, layer_id TEXT, target_modules INTEGER, production_nodes INTEGER DEFAULT 0);

-- [table] edges
CREATE TABLE "edges" (
            edge_id INTEGER PRIMARY KEY AUTOINCREMENT,
            from_node_id INTEGER NOT NULL,
            to_node_id INTEGER NOT NULL,
            dep_type TEXT, architecture_direction TEXT, coupling_strength TEXT,
            used_symbol TEXT, invocation_method TEXT, api_contract_refs TEXT,
            event_ref TEXT, ddd_integration_pattern TEXT, failure_mode TEXT,
            fallback TEXT, activation_condition TEXT, data_transfer_description TEXT,
            resource_impact TEXT, relationship_type TEXT, cross_domain INTEGER,
            verified INTEGER, dep_maturity TEXT DEFAULT 'active', valid_since TEXT, is_legal_cycle INTEGER DEFAULT 0,
            FOREIGN KEY (from_node_id) REFERENCES "nodes"(node_id),
            FOREIGN KEY (to_node_id) REFERENCES "nodes"(node_id)
        );

-- [table] field_vocabularies
CREATE TABLE field_vocabularies (
            field_name     TEXT NOT NULL,
            value          TEXT NOT NULL,
            definition     TEXT,
            ai_consumption TEXT,
            source_yaml    TEXT,
            PRIMARY KEY (field_name, value)
        );

-- [table] gates
CREATE TABLE gates (
            gate_id        TEXT PRIMARY KEY,
            name           TEXT NOT NULL,
            entry          TEXT NOT NULL,
            description    TEXT,
            files_trigger  TEXT,
            always_run     INTEGER DEFAULT 0,
            category       TEXT NOT NULL,
            status         TEXT DEFAULT 'active',
            source         TEXT DEFAULT '.pre-commit-config.yaml', event_driven TEXT DEFAULT '', auto_start INTEGER DEFAULT 1,
            CHECK (status IN ('active', 'deprecated', 'disabled'))
        );

-- [table] governance_audit_logs
CREATE TABLE governance_audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, timestamp TEXT NOT NULL, total_gates INTEGER DEFAULT 0, passed_gates INTEGER DEFAULT 0, failed_gates INTEGER DEFAULT 0, skipped_gates INTEGER DEFAULT 0, success INTEGER DEFAULT 0, errors TEXT DEFAULT '');

-- [table] hard_boundaries
CREATE TABLE hard_boundaries (
            boundary_id    TEXT PRIMARY KEY,
            category       TEXT NOT NULL,
            constraint_def TEXT NOT NULL,
            parameters     TEXT,
            impact         TEXT,
            CHECK (category IN ('architectural', 'domain', 'data', 'security', 'operational'))
        );

-- [table] infrastructure_components
CREATE TABLE infrastructure_components (
            component_id    TEXT PRIMARY KEY,
            component_type  TEXT NOT NULL,
            address         TEXT,
            health_check    TEXT,
            dependencies    TEXT,
            sla             TEXT,
            status          TEXT DEFAULT 'active',
            CHECK (component_type IN ('event_bus', 'message_queue', 'relational_db',
                                       'vector_db', 'cache', 'object_storage',
                                       'config_center', 'service_registry', 'ci_pipeline'))
        );

-- [table] model_capabilities
CREATE TABLE model_capabilities (
            model_name              TEXT PRIMARY KEY,
            tier                    TEXT NOT NULL,
            max_files_per_session   INTEGER,
            allowed_paths           TEXT,
            forbidden_paths         TEXT,
            recommended_tasks       TEXT,
            forbidden_tasks         TEXT,
            CHECK (tier IN ('premium', 'standard', 'free', 'api'))
        );

-- [table] nodes
CREATE TABLE "nodes" (
    node_id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    node_type                TEXT,
    path                     TEXT,
    granularity              TEXT,
    domain_id                TEXT,
    subdomain_id             TEXT,
    blueprint_id             TEXT,
    belongs_to               TEXT,
    owner                    TEXT,
    change_policy            TEXT,
    impact_level             TEXT,
    modification_permission  TEXT,
    file_header_score        INTEGER DEFAULT 0,
    tags                     TEXT,
    architecture_layer       TEXT,
    design_maturity          TEXT DEFAULT 'production' CHECK(design_maturity IN ('design','production','prototype')),
    deployment_lifecycle     TEXT DEFAULT 'stable',
    trust_zone               TEXT DEFAULT 'trusted_core',
    license                  TEXT DEFAULT 'Internal',
    drive_direction          TEXT DEFAULT 'bottom_up',
    type_specific_data       TEXT,
    last_verified            TEXT,
    node_name                TEXT DEFAULT '',
    file_path                TEXT DEFAULT '',
    build_status             TEXT DEFAULT 'generated' CHECK(build_status IN ('planned','generated','testing','stable','deprecated')),
    can_build                INTEGER DEFAULT 1,
    gate_reason               TEXT DEFAULT '',
    hard_boundary_ref        TEXT,
    consumed_interfaces      TEXT,
    blueprint_id_invalid     INTEGER DEFAULT 0,
    blueprint_path           TEXT);

-- [table] nodes_archive_module_lifecycle
CREATE TABLE nodes_archive_module_lifecycle (
                node_id              INTEGER,
                module_lifecycle_state TEXT,
                archived_at         TEXT    NOT NULL
            );

-- [table] registries
CREATE TABLE registries (
            registry_id    TEXT PRIMARY KEY,
            name           TEXT NOT NULL,
            title          TEXT,
            path           TEXT NOT NULL,
            version        TEXT,
            description    TEXT,
            ssot_for       TEXT
        );

-- [table] rule_bindings
CREATE TABLE rule_bindings (
        binding_id INTEGER PRIMARY KEY AUTOINCREMENT,
        function_name TEXT NOT NULL,
        rule_id TEXT NOT NULL,
        binding_type TEXT NOT NULL,
        trigger_type TEXT NOT NULL,
        trigger_id TEXT, domain_id TEXT DEFAULT '',
        FOREIGN KEY (rule_id) REFERENCES nodes(node_id)
    );

-- ========== INDEXES (with explicit sql) ==========

-- index on arch_constraints: idx_arch_constraint_from
CREATE INDEX idx_arch_constraint_from ON arch_constraints(from_domain);

-- index on arch_constraints: idx_arch_constraint_to
CREATE INDEX idx_arch_constraint_to ON arch_constraints(to_domain);

-- index on arch_directory_tree: idx_arch_dir_build
CREATE INDEX idx_arch_dir_build     ON arch_directory_tree(build_status);

-- index on arch_directory_tree: idx_arch_dir_domain
CREATE INDEX idx_arch_dir_domain    ON arch_directory_tree(domain_id);

-- index on arch_path_mappings: idx_arch_path_domain
CREATE INDEX idx_arch_path_domain ON arch_path_mappings(domain_id);

-- index on arch_path_mappings: idx_arch_path_type
CREATE INDEX idx_arch_path_type ON arch_path_mappings(path_type);

-- index on business_streams: idx_business_streams_plane
CREATE INDEX idx_business_streams_plane ON business_streams(runtime_plane);

-- index on contracts: idx_contracts_consumer
CREATE INDEX idx_contracts_consumer ON contracts(consumer_domain);

-- index on contracts: idx_contracts_provider
CREATE INDEX idx_contracts_provider ON contracts(provider_domain);

-- index on domain_dependencies: idx_domain_dependencies_constraint_type
CREATE INDEX idx_domain_dependencies_constraint_type ON domain_dependencies(constraint_type);

-- index on domain_dependencies: idx_domdeps_from
CREATE INDEX idx_domdeps_from       ON domain_dependencies(from_domain);

-- index on domain_dependencies: idx_domdeps_to
CREATE INDEX idx_domdeps_to         ON domain_dependencies(to_domain);

-- index on domain_events: idx_events_source
CREATE INDEX idx_events_source ON domain_events(source_domain);

-- index on domain_mapping: idx_domain_mapping_domain
CREATE INDEX idx_domain_mapping_domain ON domain_mapping(domain_id);

-- index on domain_mapping: idx_domain_mapping_prefix
CREATE INDEX idx_domain_mapping_prefix ON domain_mapping(path_prefix);

-- index on domain_mapping: idx_domain_mapping_type
CREATE INDEX idx_domain_mapping_type ON domain_mapping(mapping_type);

-- index on domains: idx_domains_group
CREATE INDEX idx_domains_group ON domains(domain_group);

-- index on domains: idx_domains_lifecycle
CREATE INDEX idx_domains_lifecycle ON domains(lifecycle);

-- index on edges: idx_edges_coupling_strength
CREATE INDEX idx_edges_coupling_strength ON edges(coupling_strength);

-- index on edges: idx_edges_cross_domain
CREATE INDEX idx_edges_cross_domain ON edges(cross_domain);

-- index on edges: idx_edges_dep_maturity
CREATE INDEX idx_edges_dep_maturity ON edges(dep_maturity);

-- index on edges: idx_edges_from
CREATE INDEX idx_edges_from ON edges(from_node_id);

-- index on edges: idx_edges_legal_cycle
CREATE INDEX idx_edges_legal_cycle ON edges(is_legal_cycle);

-- index on edges: idx_edges_to
CREATE INDEX idx_edges_to ON edges(to_node_id);

-- index on edges: idx_edges_type
CREATE INDEX idx_edges_type         ON edges(dep_type);

-- index on edges: idx_edges_valid_since
CREATE INDEX idx_edges_valid_since ON edges(valid_since);

-- index on edges: idx_edges_verified
CREATE INDEX idx_edges_verified ON edges(verified);

-- index on field_vocabularies: idx_field_vocab_field
CREATE INDEX idx_field_vocab_field ON field_vocabularies(field_name);

-- index on gates: idx_gates_category
CREATE INDEX idx_gates_category ON gates(category);

-- index on gates: idx_gates_files_trigger
CREATE INDEX idx_gates_files_trigger ON gates(files_trigger);

-- index on hard_boundaries: idx_hard_boundaries_category
CREATE INDEX idx_hard_boundaries_category ON hard_boundaries(category);

-- index on nodes: idx_nodes_blueprint
CREATE INDEX idx_nodes_blueprint    ON nodes(blueprint_id);

-- index on nodes: idx_nodes_build_status
CREATE INDEX idx_nodes_build_status ON nodes(build_status);

-- index on nodes: idx_nodes_can_build
CREATE INDEX idx_nodes_can_build    ON nodes(can_build);

-- index on nodes: idx_nodes_change_policy
CREATE INDEX idx_nodes_change_policy ON nodes(change_policy);

-- index on nodes: idx_nodes_domain
CREATE INDEX idx_nodes_domain       ON nodes(domain_id);

-- index on nodes: idx_nodes_file_path
CREATE INDEX idx_nodes_file_path    ON nodes(file_path);

-- index on nodes: idx_nodes_path
CREATE INDEX idx_nodes_path         ON nodes(path);

-- index on nodes: idx_nodes_type
CREATE INDEX idx_nodes_type         ON nodes(node_type);

-- ========== TRIGGERS ==========

-- trigger on blueprint_links: readonly_blueprint_links_delete
CREATE TRIGGER readonly_blueprint_links_delete
        BEFORE DELETE ON blueprint_links
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'blueprint_links 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on blueprint_links: readonly_blueprint_links_insert
CREATE TRIGGER readonly_blueprint_links_insert
        BEFORE INSERT ON blueprint_links
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'blueprint_links 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on blueprint_links: readonly_blueprint_links_update
CREATE TRIGGER readonly_blueprint_links_update BEFORE UPDATE ON blueprint_links FOR EACH ROW BEGIN SELECT RAISE(ABORT, 'blueprint_links 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py'); END;

-- trigger on business_streams: readonly_business_streams_delete
CREATE TRIGGER readonly_business_streams_delete
        BEFORE DELETE ON business_streams
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'business_streams 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on business_streams: readonly_business_streams_insert
CREATE TRIGGER readonly_business_streams_insert
        BEFORE INSERT ON business_streams
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'business_streams 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on business_streams: readonly_business_streams_update
CREATE TRIGGER readonly_business_streams_update
        BEFORE UPDATE ON business_streams
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'business_streams 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on cross_registry_rules: readonly_cross_registry_rules_delete
CREATE TRIGGER readonly_cross_registry_rules_delete
        BEFORE DELETE ON cross_registry_rules
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'cross_registry_rules 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on cross_registry_rules: readonly_cross_registry_rules_insert
CREATE TRIGGER readonly_cross_registry_rules_insert
        BEFORE INSERT ON cross_registry_rules
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'cross_registry_rules 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on cross_registry_rules: readonly_cross_registry_rules_update
CREATE TRIGGER readonly_cross_registry_rules_update
        BEFORE UPDATE ON cross_registry_rules
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'cross_registry_rules 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on domains: chk_domains_build_status_insert
CREATE TRIGGER chk_domains_build_status_insert
            BEFORE INSERT ON domains
            WHEN NEW.build_status NOT IN ('planned', 'generated', 'testing', 'stable', 'deprecated')
            BEGIN
                SELECT RAISE(ABORT, 'domains.build_status illegal value (legal: planned/generated/testing/stable/deprecated)');
            END;

-- trigger on domains: chk_domains_build_status_update
CREATE TRIGGER chk_domains_build_status_update
            BEFORE UPDATE OF build_status ON domains
            WHEN NEW.build_status NOT IN ('planned', 'generated', 'testing', 'stable', 'deprecated')
            BEGIN
                SELECT RAISE(ABORT, 'domains.build_status illegal value (legal: planned/generated/testing/stable/deprecated)');
            END;

-- trigger on domains: chk_domains_layer_id_insert
CREATE TRIGGER chk_domains_layer_id_insert
            BEFORE INSERT ON domains
            WHEN NEW.layer_id IS NOT NULL AND NEW.layer_id NOT IN ('L0_infrastructure', 'L1_foundation', 'L2_domain', 'L3_application')
            BEGIN
                SELECT RAISE(ABORT, 'domains.layer_id illegal value (legal: L0_infrastructure/L1_foundation/L2_domain/L3_application/NULL)');
            END;

-- trigger on domains: chk_domains_layer_id_update
CREATE TRIGGER chk_domains_layer_id_update
            BEFORE UPDATE OF layer_id ON domains
            WHEN NEW.layer_id IS NOT NULL AND NEW.layer_id NOT IN ('L0_infrastructure', 'L1_foundation', 'L2_domain', 'L3_application')
            BEGIN
                SELECT RAISE(ABORT, 'domains.layer_id illegal value (legal: L0_infrastructure/L1_foundation/L2_domain/L3_application/NULL)');
            END;

-- trigger on domains: chk_domains_lifecycle_insert
CREATE TRIGGER chk_domains_lifecycle_insert
            BEFORE INSERT ON domains
            WHEN NEW.lifecycle NOT IN ('operational', 'design_only', 'prototype', 'deprecated')
            BEGIN
                SELECT RAISE(ABORT, 'domains.lifecycle illegal value (legal: operational/design_only/prototype/deprecated)');
            END;

-- trigger on domains: chk_domains_lifecycle_update
CREATE TRIGGER chk_domains_lifecycle_update
            BEFORE UPDATE OF lifecycle ON domains
            WHEN NEW.lifecycle NOT IN ('operational', 'design_only', 'prototype', 'deprecated')
            BEGIN
                SELECT RAISE(ABORT, 'domains.lifecycle illegal value (legal: operational/design_only/prototype/deprecated)');
            END;

-- trigger on field_vocabularies: readonly_field_vocabularies_delete
CREATE TRIGGER readonly_field_vocabularies_delete
        BEFORE DELETE ON field_vocabularies
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'field_vocabularies 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on field_vocabularies: readonly_field_vocabularies_insert
CREATE TRIGGER readonly_field_vocabularies_insert
        BEFORE INSERT ON field_vocabularies
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'field_vocabularies 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on field_vocabularies: readonly_field_vocabularies_update
CREATE TRIGGER readonly_field_vocabularies_update
        BEFORE UPDATE ON field_vocabularies
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'field_vocabularies 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on gates: readonly_gates_delete
CREATE TRIGGER readonly_gates_delete
        BEFORE DELETE ON gates
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'gates 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on gates: readonly_gates_insert
CREATE TRIGGER readonly_gates_insert
        BEFORE INSERT ON gates
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'gates 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on gates: readonly_gates_update
CREATE TRIGGER readonly_gates_update
        BEFORE UPDATE ON gates
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'gates 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on hard_boundaries: readonly_hard_boundaries_delete
CREATE TRIGGER readonly_hard_boundaries_delete
        BEFORE DELETE ON hard_boundaries
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'hard_boundaries 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on hard_boundaries: readonly_hard_boundaries_insert
CREATE TRIGGER readonly_hard_boundaries_insert
        BEFORE INSERT ON hard_boundaries
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'hard_boundaries 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on hard_boundaries: readonly_hard_boundaries_update
CREATE TRIGGER readonly_hard_boundaries_update
        BEFORE UPDATE ON hard_boundaries
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'hard_boundaries 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on infrastructure_components: readonly_infrastructure_components_delete
CREATE TRIGGER readonly_infrastructure_components_delete
        BEFORE DELETE ON infrastructure_components
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'infrastructure_components 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on infrastructure_components: readonly_infrastructure_components_insert
CREATE TRIGGER readonly_infrastructure_components_insert
        BEFORE INSERT ON infrastructure_components
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'infrastructure_components 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on infrastructure_components: readonly_infrastructure_components_update
CREATE TRIGGER readonly_infrastructure_components_update
        BEFORE UPDATE ON infrastructure_components
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'infrastructure_components 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on model_capabilities: readonly_model_capabilities_delete
CREATE TRIGGER readonly_model_capabilities_delete
        BEFORE DELETE ON model_capabilities
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'model_capabilities 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on model_capabilities: readonly_model_capabilities_insert
CREATE TRIGGER readonly_model_capabilities_insert
        BEFORE INSERT ON model_capabilities
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'model_capabilities 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on model_capabilities: readonly_model_capabilities_update
CREATE TRIGGER readonly_model_capabilities_update
        BEFORE UPDATE ON model_capabilities
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'model_capabilities 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on nodes: chk_nodes_blueprint_id_insert
CREATE TRIGGER chk_nodes_blueprint_id_insert
            BEFORE INSERT ON nodes
            WHEN NEW.blueprint_id IS NOT NULL
              AND NEW.blueprint_id != ''
              AND NEW.blueprint_id_invalid = 0
              AND NEW.blueprint_id NOT GLOB 'MOD-*'
              AND NEW.blueprint_id NOT GLOB 'D-*'
              AND NEW.blueprint_id NOT GLOB 'SH-*'
              AND NEW.blueprint_id NOT GLOB 'PLACEHOLDER*'
            BEGIN
                SELECT RAISE(ABORT, 'nodes.blueprint_id format violation (裁定#208 双轨制+历史兼容: MOD-*/D-*/SH-*/PLACEHOLDER*, or set blueprint_id_invalid=1 for legacy)');
            END;

-- trigger on nodes: chk_nodes_blueprint_id_update
CREATE TRIGGER chk_nodes_blueprint_id_update
            BEFORE UPDATE OF blueprint_id ON nodes
            WHEN NEW.blueprint_id IS NOT NULL
              AND NEW.blueprint_id != ''
              AND NEW.blueprint_id_invalid = 0
              AND NEW.blueprint_id NOT GLOB 'MOD-*'
              AND NEW.blueprint_id NOT GLOB 'D-*'
              AND NEW.blueprint_id NOT GLOB 'SH-*'
              AND NEW.blueprint_id NOT GLOB 'PLACEHOLDER*'
            BEGIN
                SELECT RAISE(ABORT, 'nodes.blueprint_id format violation (裁定#208 双轨制+历史兼容: MOD-*/D-*/SH-*/PLACEHOLDER*, or set blueprint_id_invalid=1 for legacy)');
            END;

-- trigger on nodes: trg_nodes_delete_cleanup_edges
CREATE TRIGGER trg_nodes_delete_cleanup_edges
            AFTER DELETE ON nodes
            BEGIN
                DELETE FROM edges WHERE from_node_id = OLD.node_id OR to_node_id = OLD.node_id;
            END;

-- trigger on registries: readonly_registries_delete
CREATE TRIGGER readonly_registries_delete
        BEFORE DELETE ON registries
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'registries 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on registries: readonly_registries_insert
CREATE TRIGGER readonly_registries_insert
        BEFORE INSERT ON registries
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'registries 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- trigger on registries: readonly_registries_update
CREATE TRIGGER readonly_registries_update
        BEFORE UPDATE ON registries
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'registries 表只读（唯一真源是 YAML），请修改 YAML 后运行 sync_yaml_to_depgraph.py');
        END;

-- ========== SUMMARY ==========
-- tables: 25
-- views: 1
-- indexes(with sql): 39
-- triggers: 36

-- ========== TABLE ROW COUNTS ==========
-- _schema_version: 18 rows
-- arch_constraints: 59 rows
-- arch_directory_tree: 9393 rows
-- arch_path_mappings: 320 rows
-- blueprint_links: 847 rows
-- business_streams: 5 rows
-- contracts: 380 rows
-- cross_registry_rules: 6 rows
-- derived_identifier_registry: 4 rows
-- domain_dependencies: 270 rows
-- domain_events: 118 rows
-- domain_mapping: 94 rows
-- domain_naming_rules: 5 rows
-- domains: 53 rows
-- edges: 7094 rows
-- field_vocabularies: 191 rows
-- gates: 129 rows
-- governance_audit_logs: 67 rows
-- hard_boundaries: 8 rows
-- infrastructure_components: 11 rows
-- model_capabilities: 9 rows
-- nodes: 6428 rows
-- nodes_archive_module_lifecycle: 6804 rows
-- registries: 18 rows
-- rule_bindings: 73 rows

-- ========== TABLE COLUMNS (count + names) ==========
-- _schema_version (3 cols): version, applied_at, description
-- arch_constraints (12 cols): constraint_id, name, constraint_type, from_domain, to_domain, rule_definition, severity, enforcement, description, violation_status, details, detected_at
-- arch_directory_tree (10 cols): path, parent_path, path_type, domain_id, blueprint_id, change_policy, modification_permission, build_status, design_maturity, last_scanned
-- arch_path_mappings (7 cols): mapping_id, domain_id, path_pattern, path_type, state, covers, aliases
-- blueprint_links (4 cols): blueprint_id, blueprint_path, alignment_verified, last_verified
-- business_streams (6 cols): stream_id, name, goal, input, output, runtime_plane
-- contracts (13 cols): contract_id, name, provider_domain, consumer_domain, contract_type, schema_definition, version, promise, actual_consumer, fulfillment_status, gap, target_phase, last_reviewed
-- cross_registry_rules (6 cols): rule_id, title, fields, ssot, consistency, violation_action
-- derived_identifier_registry (6 cols): derived_type, source_field, derived_field, derivation_rule, propagation_method, source_doc
-- domain_dependencies (5 cols): from_domain, to_domain, edge_count, edge_types, constraint_type
-- domain_events (7 cols): event_id, name, source_domain, target_domains, payload_schema, priority, event_type
-- domain_mapping (8 cols): mapping_id, path_prefix, domain_id, subdomain_id, mapping_type, mapped_at, mapped_by, note
-- domain_naming_rules (9 cols): rule_id, rule_name, rule_text, applies_to, severity, example_bad, example_good, created_at, source_doc
-- domains (15 cols): domain_id, domain_name, domain_group, description, ssot_path, current_modules, max_modules, lifecycle, created_at, updated_at, build_status, modification_permission, layer_id, target_modules, production_nodes
-- edges (22 cols): edge_id, from_node_id, to_node_id, dep_type, architecture_direction, coupling_strength, used_symbol, invocation_method, api_contract_refs, event_ref, ddd_integration_pattern, failure_mode, fallback, activation_condition, data_transfer_description, resource_impact, relationship_type, cross_domain, verified, dep_maturity, valid_since, is_legal_cycle
-- field_vocabularies (5 cols): field_name, value, definition, ai_consumption, source_yaml
-- gates (11 cols): gate_id, name, entry, description, files_trigger, always_run, category, status, source, event_driven, auto_start
-- governance_audit_logs (8 cols): id, timestamp, total_gates, passed_gates, failed_gates, skipped_gates, success, errors
-- hard_boundaries (5 cols): boundary_id, category, constraint_def, parameters, impact
-- infrastructure_components (7 cols): component_id, component_type, address, health_check, dependencies, sla, status
-- model_capabilities (7 cols): model_name, tier, max_files_per_session, allowed_paths, forbidden_paths, recommended_tasks, forbidden_tasks
-- nodes (31 cols): node_id, node_type, path, granularity, domain_id, subdomain_id, blueprint_id, belongs_to, owner, change_policy, impact_level, modification_permission, file_header_score, tags, architecture_layer, design_maturity, deployment_lifecycle, trust_zone, license, drive_direction, type_specific_data, last_verified, node_name, file_path, build_status, can_build, gate_reason, hard_boundary_ref, consumed_interfaces, blueprint_id_invalid, blueprint_path
-- nodes_archive_module_lifecycle (3 cols): node_id, module_lifecycle_state, archived_at
-- registries (7 cols): registry_id, name, title, path, version, description, ssot_for
-- rule_bindings (7 cols): binding_id, function_name, rule_id, binding_type, trigger_type, trigger_id, domain_id
