# [BLUEPRINT] MOD-BT-001 | (auto-injected by S4 reconciler) | §
# [TTL] permanent
"""
Auto-generated contracts package — core

Generated by: scripts/governance/d5_architecture/generate_contracts.py
"""

from .engine_base import BacktestEngineBase, BacktestResult, FactorDiscovery

__all__ = [
    "engine_base",
]
