# [BLUEPRINT] MOD-INF-005 | scripts/generate_manifest.py | §
# [MODULE] scripts.generate_manifest
# [DOMAIN] D_GOVERNANCE
# [DEPENDENCIES] scripts.__init__
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS]
# [MODIFY-GUARD]
# [STABILITY] evolving
# [SAFETY] M
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [TTL] permanent
"""Generate complete script_manifest.yaml from scripts/ tree scan."""
# 双 manifest 体系说明（P1-T4 校正，2026-06-26）
# 本生成器 → scripts/script_manifest.yaml（全树 563 脚本，简单 desc 提取）
# 兄弟生成器 scripts/governance/generators/generate_script_manifest.py
#   → scripts/governance/script_manifest.yaml（governance 子集 369，__manifest__ 块提取）
# 二者非冗余：消费链不同（本生成器供 GitCommitGateway _post_commit_reconcile
#   + audit_registration；兄弟供 GATE-19 validate_static_manifest_drift --check）
# 禁止以"统一 SSoT"为由废弃任一——会破坏对应消费链。
# 详见 .trae/documents/systemic_drift_root_cure_continuation_plan.md §3

import os
import sys
from datetime import date
from pathlib import Path

import yaml

SCRIPTS_ROOT = Path("scripts")
OUTPUT_PATH = "scripts/script_manifest.yaml"
EXCLUDE_DIRS = {"__pycache__", "reports", ".git", "node_modules"}


def extract_description(filepath: Path) -> str:
    try:
        content = filepath.read_text(encoding="utf-8", errors="ignore")
        lines = [l.strip() for l in content.split("\n") if l.strip() and not l.strip().startswith("#")]
        if not lines:
            return "No description"
        for line in lines[:10]:
            line = line.strip()
            if line.startswith('"""') or line.startswith("'''") or line.startswith("#"):
                continue
            if len(line) > 3:
                return line[:120]
        return "Script entry"
    except Exception:
        return "Could not read"


def determine_phase(rel_path: str) -> str:
    parts = rel_path.lower().replace("\\", "/").split("/")
    for p in parts:
        if "phase" in p or "g0" in p or "g1" in p or "g2" in p or "gate" in p:
            return "hot-path"
    return "warm-path"


def determine_domain(rel_path: str) -> str:
    parts = rel_path.lower().replace("\\", "/").split("/")
    domain_map = {
        "governance": "governance",
        "gate": "governance",
        "rollback": "rollback",
        "audit": "audit",
        "drift": "drift",
        "escalation": "escalation",
        "budget": "budget",
        "rbac": "rbac",
        "a2a": "a2a",
        "pipeline": "pipeline",
        "contract": "contract",
        "test": "test",
        "sync": "sync",
        "generate": "generator",
        "scan": "scanner",
        "health": "health",
        "doctor": "health",
    }
    for p in parts:
        for keyword, domain in domain_map.items():
            if keyword in p:
                return domain
    if parts:
        return parts[0]
    return "misc"


scripts = []
for root, dirs, files in os.walk(SCRIPTS_ROOT):
    dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
    for f in sorted(files):
        if not f.endswith(".py"):
            continue
        full = Path(root) / f
        rel = str(full.relative_to(SCRIPTS_ROOT)).replace("\\", "/")
        desc = extract_description(full)
        domain = determine_domain(rel)
        phase = determine_phase(rel)
        scripts.append(
            {
                "name": rel,
                "path": rel,
                "description": desc,
                "domain": domain,
                "execution_plane": phase,
                "status": "registered",
                "timeout_seconds": 60,
                "dimensions": [],
            }
        )

manifest = {
    "manifest_version": "2.0.0",
    "generated_by": "generate_manifest.py (auto-scan)",
    "generated_at": date.today().isoformat(),
    "total_scripts": len(scripts),
    "scripts": scripts,
}

import os as _os

tmp_path = f"{OUTPUT_PATH}.{_os.getpid()}.tmp"
try:
    with open(tmp_path, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by scripts/generate_manifest.py\n")
        f.write("# DO NOT EDIT MANUALLY — run generate_manifest.py to regenerate\n")
        f.write("#\n")
        yaml.dump(manifest, f, default_flow_style=False, allow_unicode=True, sort_keys=False, width=200)
    _os.replace(tmp_path, OUTPUT_PATH)
    print(f"OK: {len(scripts)} scripts written to {OUTPUT_PATH}")
except PermissionError:
    try:
        _os.remove(tmp_path)
    except OSError:
        pass
    print("ERROR: Permission denied", file=sys.stderr)
    sys.exit(1)
