# [BLUEPRINT] MOD-INF-005 | scripts/generate_manifest.py | §
# [MODULE] scripts.generate_manifest
# [DOMAIN] D_GOVERNANCE
# [DEPENDENCIES] scripts.__init__
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] production
# [INVARIANTS]
# [MODIFY-GUARD]
# [STABILITY] evolving
# [SAFETY] M
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-INF-005 | layer=module | stability=evolving | safety=M | ai_autonomy=ai_modifiable
# [TTL] permanent
"""Generate complete script-manifest.yaml from scripts/ tree scan."""
# 双 manifest 体系说明（P1-T4 校正，2026-06-26；#51 裁定收敛，2026-08-14）
# 本生成器 → scripts/script-manifest.yaml（全树脚本登记真源 SSoT，简单 desc 提取）
# 兄弟生成器 scripts/governance/generators/generate_script_manifest.py
#   → scripts/governance/script_manifest.yaml（governance 子集，__manifest__ 块提取）
# 二者非冗余：消费链不同（本生成器供 GitCommitGateway _post_commit_reconcile
#   + audit_registration + orphan_scanner/registration_checker 等登记检查链；
#   兄弟供 GATE-19/21 validate_static_manifest_drift --check）
# #51 裁定（2026-08-14 统筹）：连字符版为登记真源——orphan_scanner/
#   speed_baseline_checker/pipeline_runner/scaffold_registrar/registration_checker/
#   registry_adapter REG-SCRIPT-001 均消费连字符版；其自 2026-07-19 起失维护
#   （生成器 OUTPUT_PATH 曾漂移到下划线版，形成多真源隐患），下划线
#   script_manifest.yaml 收敛退库，生成器 OUTPUT_PATH 已锚回连字符真源。

import io
import os
import re
import sys
from datetime import date
from pathlib import Path

import yaml

SCRIPTS_ROOT = Path("scripts")
OUTPUT_PATH = "scripts/script-manifest.yaml"
EXCLUDE_DIRS = {"__pycache__", "reports", ".git", "node_modules"}


def extract_description(filepath: Path) -> str:
    try:
        content = filepath.read_text(encoding="utf-8", errors="ignore")
        lines = [l.strip() for l in content.split("\n") if l.strip() and not l.strip().startswith("#")]
        if not lines:
            return "No description"
        for line in lines[:10]:
            line = line.strip()
            if line.startswith('"""') or line.startswith("'''") or line.startswith("#"):
                continue
            if len(line) > 3:
                return line[:120]
        return "Script entry"
    except Exception:  # noqa: BLE001 — desc 提取失败沉底占位，不让单文件编码问题炸全树扫描（HEAD 存量）
        return "Could not read"


def determine_phase(rel_path: str) -> str:
    parts = rel_path.lower().replace("\\", "/").split("/")
    for p in parts:
        if "phase" in p or "g0" in p or "g1" in p or "g2" in p or "gate" in p:
            return "hot-path"
    return "warm-path"


def determine_domain(rel_path: str) -> str:
    parts = rel_path.lower().replace("\\", "/").split("/")
    domain_map = {
        "governance": "governance",
        "gate": "governance",
        "rollback": "rollback",
        "audit": "audit",
        "drift": "drift",
        "escalation": "escalation",
        "budget": "budget",
        "rbac": "rbac",
        "a2a": "a2a",
        "pipeline": "pipeline",
        "contract": "contract",
        "test": "test",
        "sync": "sync",
        "generate": "generator",
        "scan": "scanner",
        "health": "health",
        "doctor": "health",
    }
    for p in parts:
        for keyword, domain in domain_map.items():
            if keyword in p:
                return domain
    if parts:
        return parts[0]
    return "misc"


def build_manifest_content() -> tuple[str, int]:
    """全树扫描→manifest 文本（与台数）。纯函数：零写盘、零 argv 依赖。"""
    scripts = []
    for root, dirs, files in os.walk(SCRIPTS_ROOT):
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
        for f in sorted(files):
            if not f.endswith(".py"):
                continue
            full = Path(root) / f
            rel = str(full.relative_to(SCRIPTS_ROOT)).replace("\\", "/")
            desc = extract_description(full)
            domain = determine_domain(rel)
            phase = determine_phase(rel)
            scripts.append(
                {
                    "name": rel,
                    "path": rel,
                    "description": desc,
                    "domain": domain,
                    "execution_plane": phase,
                    "status": "registered",
                    "timeout_seconds": 60,
                    "dimensions": [],
                }
            )

    manifest = {
        "manifest_version": "2.0.0",
        "generated_by": "generate_manifest.py (auto-scan)",
        "generated_at": date.today().isoformat(),
        "total_scripts": len(scripts),
        "scripts": scripts,
    }

    buf = io.StringIO()
    buf.write("# Auto-generated by scripts/generate_manifest.py\n")
    buf.write("# DO NOT EDIT MANUALLY — run generate_manifest.py to regenerate\n")
    buf.write("#\n")
    yaml.dump(manifest, buf, default_flow_style=False, allow_unicode=True, sort_keys=False, width=200)
    return buf.getvalue(), len(scripts)


def write_manifest(out_path: str) -> int:
    """幂等写目标位（P0② AI-20：内容未变跳写，generated_at 不参与比对）。返回台数。"""
    content, n = build_manifest_content()
    out = Path(out_path)
    rx = re.compile(r"^generated_at: .*$", re.MULTILINE)
    try:
        existing = out.read_text(encoding="utf-8")
        if rx.sub("", content) == rx.sub("", existing):
            print(f"OK: {n} scripts unchanged, skipped {out_path} (idempotent)")
            return n
    except (OSError, UnicodeDecodeError):
        pass
    tmp_path = f"{out_path}.{os.getpid()}.tmp"
    try:
        with open(tmp_path, "w", encoding="utf-8") as f:
            f.write(content)
        os.replace(tmp_path, out_path)
        print(f"OK: {n} scripts written to {out_path}")
    except PermissionError:
        try:
            os.remove(tmp_path)
        except OSError:
            pass
        print("ERROR: Permission denied", file=sys.stderr)
        sys.exit(1)
    return n


def main(argv: list[str] | None = None) -> int:
    """Entry point: parse args, run logic, return exit code."""
    import argparse

    parser = argparse.ArgumentParser(description="scripts/ 全树脚本登记 manifest 机生器（SSoT=连字符真源）")
    parser.add_argument(
        "--output",
        default=OUTPUT_PATH,
        help=f"输出路径（缺省={OUTPUT_PATH} 登记真源；测试传隔离副本禁写生产路径——宪法 §9.6）",
    )
    args = parser.parse_args(argv)
    write_manifest(args.output)
    return 0


# noqa: m11-perm-manual-legitimate  M11豁免: 本件=双通道件——①事件触发面=reconciliation_registry
# 登记链 subprocess 自动调用（无参缺省真源位，非 cron/daemon 常驻）②人工再生 CLI=会话/CI 显式
# 触发（--output 隔离副本=测试隔离契约）；MANUAL-ONLY 启发式对 argv/argparse 的误判与
# generate_commit_guide.py 同款豁免先例（2026-09-30 landing 死因 MANUAL-ONLY-PERMANENT 治本）
if __name__ == "__main__":
    sys.exit(main())
