# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared_core/blueprint.md | §
# [MODULE] zephyr.shared.security.lock
# [DOMAIN] D_SHARED
# [DEPENDENCIES] zephyr.shared.infra.lock
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-SHR_lock | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] permanent

"""
lock.py —— Re-export wrapper -> canonical: zephyr.shared.infra.lock

Backward-compatible top-level alias. Canonical implementation at infra/lock.py.
Edit infra/lock.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.infra.lock import *  # noqa: F403
