# [TTL] permanent
"""
Auto-generated contracts package — errors

Generated by: scripts/governance/d5_architecture/generate_contracts.py

# [ALGO_FLOW]
# 层: 输入
# - id: I1
#   name: 包内子模块公共符号
#   fields: import 再导出符号: ContractViolationError, DataQualityError, ExecutionRejectionError, Fa…
#   code: __init__.py import L34
# 层: 算法
# - id: A1
#   name_zh: ① 包公共面再导出
#   name_en: __init__ re-export
#   intro: 再导出 contract_violation_error, data_quality_error, execution_rejection_error, fa…
#   desc: __init__ import L34；__all__ 5 项（AST 事实）
#   inputs: I1
#   outputs: __all__ 公共符号表
# 层: 输出
# - id: O1
#   name_zh: 公共 API 面（5 符号）
#   name_en: __all__
#   intro: contract_violation_error, data_quality_error, execution_rejection_error, factor…
#   downstream: 见模块头 [CONSUMERS]
# [/ALGO_FLOW]
#
# 边:
# I1 --> A1
# A1 --> O1
"""

from .contract_violation_error import ContractViolationError
from .data_quality_error import DataQualityError
from .execution_rejection_error import ExecutionRejectionError
from .factor_computation_error import FactorComputationError
from .risk_limit_violation_error import RiskLimitViolationError

__all__ = [
    "contract_violation_error",
    "data_quality_error",
    "execution_rejection_error",
    "factor_computation_error",
    "risk_limit_violation_error",
]
