"""
Auto-generated contracts package — errors

Generated by: scripts/governance/d5_architecture/generate_contracts.py
"""

from .contract_violation_error import ContractViolationError
from .data_quality_error import DataQualityError
from .execution_rejection_error import ExecutionRejectionError
from .factor_computation_error import FactorComputationError
from .risk_limit_violation_error import RiskLimitViolationError
from .signal_degradation_warning import SignalDegradationWarning

__all__ = [
    "contract_violation_error",
    "data_quality_error",
    "execution_rejection_error",
    "factor_computation_error",
    "risk_limit_violation_error",
    "signal_degradation_warning",
]
