# [BLUEPRINT] MOD-INF-023 | docs/03_modules/_domain_governance/drift_detector/blueprint.md | §
# [A_module] module_id=MOD-INF-023 | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] permanent
from __future__ import annotations

# ============================================================================
# behavioral_audit 模块地图（ARCH-034 治本：强化发现性，不建物理子目录）
# ============================================================================
# ARCH-042 阶段3裁定（2026-07-03）：本包66个.py文件享GOV-DOC-018 T_soft=120（5簇多前缀
# 命名约定满足"前缀分组+可预测+覆盖全部文件"），66≤120合规，物理拆分非阈值强制。
# 不建物理子目录的理由（ARCH-034 + ARCH-042裁定双重支持）：
#   ① 已有5聚合是现成分类（_core/_drift/_scanners/_infrastructure/_analysis），建物理子目录=造第二套分类=违反原则①
#   ② 104+外部import改动=漂移源（含大量@patch字符串引用+drift_engine的__file__路径陷阱）
#   ③ behavioral_auditor/__init__.py 是Safety=H对外垫片（40+import），拆分风险>收益
# 物理平铺 + 逻辑分类已分层：新AI通过本地图 + _SYMBOL_SOURCE 字典即可定位任意符号。
#
# 5个聚合子模块（_xxx.py）是功能域门面，各自聚合一类功能模块：
#
#   _core.py        — 核心引擎与状态机（drift扫描调度/事件/状态/检测器分发/架构契约）
#     含: drift_engine, drift_models, events, state_machine, detector_dispatcher,
#         architecture_contracts, architecture_principles, brain_integration,
#         dependency_manager, integration_test_runner,
#         ml_engineering, model_drift_monitor, performance_baseline, regime_detector
#         （已迁至 drift_detector_core/）
#
#   _drift.py       — 漂移检测器簇（契约/DB/版本/文档/语义/安全等漂移类型）
#     含: contract_drift_detector, drift_hotfix_bypass, drift_infrastructure,
#         drift_result_types, drift_training, cascade_detector, baseline_poisoning_guard
#
#   _scanners.py    — 扫描器与检查器簇（增量/无头/孤儿/符号链接/文件属性等扫描）
#     含: incremental_scanner, headless_scanner, orphan_scanner, scan_mutex,
#         symlink_checker, file_attr_checker, naming_magic_checker,
#         test_fixture_checker, python_compat, gitignore_auditor,
#         benchmark_integrity（已迁至 drift_detector_core/）, code_review_ai, cross_env_consistency,
#         data_classification, data_lifecycle, data_quality, data_source_reliability
#
#   _infrastructure.py — 基础设施簇（缺勤/告警/基线/金丝雀/冷启动/配置/仪表盘等）
#     含: absence_manager, ai_context_injector, alert_router, baseline_manager,
#         canary_controller, cold_start, config_consistency, dashboard,
#         gate_persistence, handoff_manager, resource_guard
#
#   _analysis.py    — 分析与报告簇（相关性/可信度/取证/ROI/趋势/混沌/回滚等）
#     含: correlation_engine, credibility_engine, cross_module_score,
#         forensics_engine, git_bisector, reconciler, roi_engine, rollback_bridge,
#         runbook_generator, self_check, suppression_learner, tamper_proof_audit,
#         trend_analyzer, chaos_injector, backcompat_checker,
#         ai_construction_detectors, self_test_verifier
#
# 命名规则约定（未来新增文件遵循，便于按名定位归聚合）：
#   - drift_* / *_drift_detector / cascade_detector / baseline_poisoning*  -> _drift
#   - *_scanner / *_checker / scan_mutex / data_* / cross_env_consistency   -> _scanners
#   - *_manager / *_controller / *_router / cold_start / dashboard          -> _infrastructure
#   - *_engine / *_analyzer / forensics_* / reconciler / runbook_*          -> _analysis
#   - events / state_machine / detector_dispatcher / architecture_*         -> _core
#
# 新AI使用指引（对应向内收原则④：如何发现+如何不重造）：
#   1. 定位符号：查 _SYMBOL_SOURCE 字典（符号->聚合映射），再 import 对应聚合
#   2. 定位模块：本地图按文件名前缀归位，直接 import zephyr.gov_drift.<module>
#   3. 新增功能前：先 CapabilityLookup.find("<关键词>") 反查是否已有实现（防重造）
#   4. 新增文件：按命名规则命名，并更新对应聚合的 _SUBMODULES + 本地图 + 能力卡
# ============================================================================

# [BLUEPRINT] MOD-INF-023 | docs/03_modules/_domain_governance/drift_detector/blueprint.md
# [MODULE] zephyr.gov_drift
# [INVARIANTS] __all__列表不变; 公开API不变
# [MODIFY-GUARD] 新增子模块须同步更新_SUBMODULES和__all__
# [CONSUMERS] orchestrator; gates; runtime; pipeline
# [STABILITY] evolving
# [SAFETY] M
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT] AttributeError: 模块无此属性
# [TESTS] tests/test_behavioral_auditor_imports.py
# [TTL] permanent

_SYMBOL_SOURCE = {
    "AIConstructionDetectors": "_analysis",
    "AITrainingLoopResult": "_drift",
    "AbsenceManagerConfig": "_infrastructure",
    "Alert": "_infrastructure",
    "AlertRouter": "_infrastructure",
    "AnomalyAlert": "_analysis",
    "AuditRecord": "_analysis",
    "AutoFixer": "_analysis",
    "BaselineManager": "_infrastructure",
    "BaselineSnapshot": "_core",
    "BisectResult": "_analysis",
    "BreakingChange": "_core",
    "BulkDriftEvent": "_core",
    "CanaryComparison": "_infrastructure",
    "CanaryConfig": "_infrastructure",
    "CanaryResult": "_infrastructure",
    "CanaryRun": "_infrastructure",
    "CascadeAlert": "_drift",
    "CascadeConfig": "_drift",
    "CascadeEvent": "_core",
    "ChangeSet": "_scanners",
    "ChaosInjection": "_analysis",
    "ChaosInjectionType": "_analysis",
    "ChaosMetrics": "_analysis",
    "ChaosPhase": "_analysis",
    "ChaosResult": "_analysis",
    "CheckpointWriter": "_drift",
    "ColdStartResult": "_infrastructure",
    "CompatBreakEvent": "_analysis",
    "ConfigAuditReport": "_infrastructure",
    "ConfigConflict": "_core",
    "ConfigConflictInfra": "_infrastructure",
    "ConfigSource": "_infrastructure",
    "ContractDriftAlert": "_drift",
    "CorrelationEngine": "_analysis",
    "CorrelationReport": "_analysis",
    "CredibilityEngine": "_analysis",
    "CredibilityScore": "_analysis",
    "CrossLanguageConfig": "_drift",
    "CrossModuleReport": "_analysis",
    "CrossModuleScorer": "_analysis",
    "DBSchemaDriftResult": "_drift",
    "Dashboard": "_infrastructure",
    "DashboardData": "_infrastructure",
    "DegradationLevel": "_infrastructure",
    "DepVersionDriftResult": "_drift",
    "Detector": "_core",
    "DetectorDispatcher": "_core",
    "DetectorFileMapping": "_scanners",
    "DetectorResult": "_core",
    "DiffReport": "_infrastructure",
    "DocCodeCoevolutionResult": "_drift",
    "DriftBudget": "_core",
    "DriftEvent": "_core",
    "DriftEventRecord": "_core",
    "DriftReport": "_core",
    "DriftRollbackBridge": "_analysis",
    "DriftState": "_core",
    "DriftStateMachine": "_core",
    "DriftTrainingPattern": "_drift",
    "DriftType": "_core",
    "EnvDiffReport": "_drift",
    "EscalationEntry": "_infrastructure",
    "FileAttrIssue": "_scanners",
    "FileChange": "_scanners",
    "FileIntegrityRecord": "_infrastructure",
    "FixSnapshot": "_analysis",
    "FixtureDriftEvent": "_scanners",
    "ForensicsConfig": "_analysis",
    "ForensicsReport": "_analysis",
    "ForensicsTimelineEntry": "_analysis",
    "FunctionSignature": "_analysis",
    "GatePersistence": "_infrastructure",
    "GitBisector": "_analysis",
    "GitignoreAudit": "_scanners",
    "HandoffPackage": "_infrastructure",
    "HashChainEntry": "_drift",
    "HeadlessDiffEntry": "_scanners",
    "HealthSnapshot": "_infrastructure",
    "HotfixAuditEntry": "_drift",
    "HotfixBypass": "_drift",
    "IncrementalScanner": "_scanners",
    "InjectedContext": "_infrastructure",
    "InjectionLevel": "_infrastructure",
    "InterruptLog": "_scanners",
    "InvalidTransitionError": "_core",
    "KnowledgeGraphSyncResult": "_drift",
    "MaintenanceWindow": "_drift",
    "ManagedDriftEvent": "_core",
    "ManagedDriftState": "_core",
    "ModuleScore": "_analysis",
    "MultiBaselineVote": "_drift",
    "NamingMagicAlert": "_scanners",
    "OrphanClassification": "_core",
    "OrphanFile": "_core",
    "OrphanResource": "_scanners",
    "OwnerStatus": "_infrastructure",
    "PartialDeploymentRecord": "_drift",
    "PythonCompatIssue": "_scanners",
    "QueuedScan": "_scanners",
    "ROIEngine": "_analysis",
    "ROIScore": "_analysis",
    "RecoveryManager": "_drift",
    "ResourceLimits": "_infrastructure",
    "ResourceSnapshot": "_infrastructure",
    "ResourceStatus": "_infrastructure",
    "ResultCache": "_core",
    "Runbook": "_core",
    "ScanLevel": "_core",
    "ScanLockRecord": "_scanners",
    "ScanMutex": "_scanners",
    "ScanResult": "_core",
    "SecurityPolicyDriftResult": "_drift",
    "SemanticDriftResult": "_drift",
    "Severity": "_core",
    "Suggestion": "_analysis",
    "SuppressionLearner": "_analysis",
    "SuppressionRule": "_analysis",
    "SymlinkIssue": "_scanners",
    "TestCoverageDriftResult": "_drift",
    "TopDriftItem": "_infrastructure",
    "TrendAlert": "_analysis",
    "TrendAnalyzer": "_analysis",
    "TrendMetrics": "_analysis",
    "abort_handoff": "_infrastructure",
    "apply_degradation": "_infrastructure",
    "audit_gitignore": "_scanners",
    "auto_fix_compat": "_scanners",
    "bootstrap": "_infrastructure",
    "bootstrap_self_check": "_analysis",
    "build_handoff_package": "_infrastructure",
    "build_hash_chain": "_drift",
    "build_health_snapshot": "_infrastructure",
    "build_report": "_core",
    "build_runbook_frontmatter": "_analysis",
    "build_top_drifts": "_infrastructure",
    "capture_baseline": "_scanners",
    "check_absence": "_infrastructure",
    "check_broken_symlinks": "_scanners",
    "check_budget_for_gate": "_drift",
    "check_core_files": "_analysis",
    "check_encoding": "_scanners",
    "check_large_diff": "_drift",
    "check_registry_parsable": "_analysis",
    "check_size_anomaly": "_scanners",
    "classify_event_id": "_infrastructure",
    "compare_signatures": "_analysis",
    "consume_budget": "_drift",
    "count_states": "_analysis",
    "cross_validate_baseline": "_drift",
    "declare_maintenance_window": "_drift",
    "detect_ai_training_loop": "_drift",
    "detect_anomalies": "_analysis",
    "detect_cascade": "_drift",
    "detect_concept_cardinality": "_drift",
    "detect_conflicts": "_infrastructure",
    "detect_contract_drift": "_drift",
    "detect_cross_language_drift": "_drift",
    "detect_db_schema_drift": "_drift",
    "detect_dep_version_drift": "_drift",
    "detect_doc_code_coevolution": "_drift",
    "detect_enum_value_sync": "_drift",
    "detect_intentional_breaks": "_analysis",
    "detect_knowledge_graph_sync": "_drift",
    "detect_missing_env": "_infrastructure",
    "detect_owner_return": "_infrastructure",
    "detect_ownership_consistency": "_drift",
    "detect_partial_deployment": "_drift",
    "detect_python_dead_code": "_drift",
    "detect_security_policy_drift": "_drift",
    "detect_test_coverage_drift": "_drift",
    "differential_detection": "_drift",
    "dry_run_impact_analysis": "_drift",
    "escalate_if_absent": "_infrastructure",
    "extract_hardcoded_defaults": "_infrastructure",
    "extract_signatures": "_analysis",
    "extract_training_patterns": "_drift",
    "find_orphan_data": "_scanners",
    "find_orphan_docs": "_scanners",
    "find_orphan_scripts": "_scanners",
    "find_over_ignored_critical": "_scanners",
    "find_renamed_functions": "_analysis",
    "find_uncovered_types": "_scanners",
    "find_untracked_generated": "_scanners",
    "generate_audit_log": "_analysis",
    "generate_bulk_runbook": "_analysis",
    "generate_compat_report": "_scanners",
    "generate_config_sync": "_infrastructure",
    "generate_forensics_report": "_analysis",
    "generate_integrity_manifest": "_drift",
    "generate_runbook": "_analysis",
    "get_canary_history": "_infrastructure",
    "get_maintenance_window": "_drift",
    "get_max_parallel_for_level": "_core",
    "get_or_create_budget": "_drift",
    "git_checkout_snapshot": "_analysis",
    "guard_loop": "_infrastructure",
    "headless_scan_light": "_scanners",
    "import_hallucination": "_analysis",
    "init_database": "_infrastructure",
    "init_directories": "_infrastructure",
    "inject_fake_todo_bomb": "_analysis",
    "inject_full": "_infrastructure",
    "inject_minimal": "_infrastructure",
    "inject_path_rename": "_analysis",
    "inject_patterns_to_prompt": "_drift",
    "inject_standard": "_infrastructure",
    "inject_yaml_field_flip": "_analysis",
    "is_auto_fix_paused": "_drift",
    "is_guard_running": "_infrastructure",
    "load_detector_registry": "_core",
    "load_package": "_infrastructure",
    "multi_baseline_vote": "_drift",
    "parse_env_config": "_infrastructure",
    "parse_gitignore": "_scanners",
    "parse_interrupt_log": "_scanners",
    "parse_python_imports": "_drift",
    "parse_python_public_api": "_drift",
    "parse_yaml_config": "_infrastructure",
    "promote_detector": "_infrastructure",
    "push_to_evolution_engine": "_core",
    "record_activity": "_infrastructure",
    "register_env_tags": "_drift",
    "replay_baseline_history": "_analysis",
    "resume_workflow": "_infrastructure",
    "rollback_detector": "_infrastructure",
    "run_backcompat_check": "_analysis",
    "run_canary": "_infrastructure",
    "run_chaos_experiment": "_analysis",
    "run_config_audit": "_infrastructure",
    "run_fixture_check": "_scanners",
    "run_self_check": "_analysis",
    "scan": "_core",
    "scan_expected_output_drift": "_scanners",
    "scan_fixture_schema_drift": "_scanners",
    "scan_impact": "_analysis",
    "scan_mock_target_drift": "_scanners",
    "scan_naming_magic": "_scanners",
    "scan_on_commit": "_core",
    "scan_orphan_resources": "_scanners",
    "scan_phase_gate": "_core",
    "scan_python_compat": "_scanners",
    "scheduled_deep": "_core",
    "scheduled_light": "_core",
    "serialize_package": "_infrastructure",
    "serialize_report": "_analysis",
    "session_entry_activate": "_infrastructure",
    "set_critical_handler": "_infrastructure",
    "set_severity_limit": "_infrastructure",
    "setup_append_only": "_analysis",
    "sha256_file": "_analysis",
    "snapshot": "_infrastructure",
    "snapshot_event_hash": "_analysis",
    "stop_guard_loop": "_infrastructure",
    "track_training_effectiveness": "_drift",
    "validate_scalability": "_infrastructure",
    "verify_hash_chain": "_drift",
    "verify_integrity": "_infrastructure",
}
# Total: 256 symbols mapped

_SUBMODULES: list[str] | None = None


def _init_submodules():
    global _SUBMODULES
    if _SUBMODULES is not None:
        return _SUBMODULES
    import importlib

    _SUBMODULES = []
    for src in ("_core", "_drift", "_scanners", "_infrastructure", "_analysis"):
        try:
            mod = importlib.import_module(f"zephyr.gov_drift.{src}")
            _SUBMODULES.extend(mod._SUBMODULES)
        except ImportError:
            pass
    return _SUBMODULES


def __getattr__(name):
    if name in _SYMBOL_SOURCE:
        import importlib

        mod = importlib.import_module(f"zephyr.gov_drift.{_SYMBOL_SOURCE[name]}")
        val = getattr(mod, name)
        globals()[name] = val
        return val
    subs = _init_submodules()
    if name in subs:
        import importlib

        mod = importlib.import_module(f"zephyr.gov_drift.{name}")
        globals()[name] = mod
        return mod
    try:
        import importlib

        mod = importlib.import_module(f"zephyr.gov_drift.{name}")
        globals()[name] = mod
        return mod
    except ImportError:
        pass
    raise AttributeError(f"module 'zephyr.gov_drift' has no attribute {name!r}")


__all__ = [
    "AIConstructionDetectors",
    "AITrainingLoopResult",
    "AbsenceManagerConfig",
    "Alert",
    "AlertRouter",
    "AnomalyAlert",
    "AuditRecord",
    "AutoFixer",
    "BaselineManager",
    "BaselineSnapshot",
    "BisectResult",
    "BreakingChange",
    "BulkDriftEvent",
    "CanaryComparison",
    "CanaryConfig",
    "CanaryResult",
    "CanaryRun",
    "CascadeAlert",
    "CascadeConfig",
    "CascadeEvent",
    "ChangeSet",
    "ChaosInjection",
    "ChaosInjectionType",
    "ChaosMetrics",
    "ChaosPhase",
    "ChaosResult",
    "CheckpointWriter",
    "ColdStartResult",
    "CompatBreakEvent",
    "ConfigAuditReport",
    "ConfigConflict",
    "ConfigSource",
    "ContractDriftAlert",
    "CorrelationEngine",
    "CorrelationReport",
    "CredibilityEngine",
    "CredibilityScore",
    "CrossLanguageConfig",
    "CrossModuleReport",
    "CrossModuleScorer",
    "DBSchemaDriftResult",
    "Dashboard",
    "DashboardData",
    "DegradationLevel",
    "DepVersionDriftResult",
    "Detector",
    "DetectorDispatcher",
    "DetectorFileMapping",
    "DetectorResult",
    "DiffReport",
    "DocCodeCoevolutionResult",
    "DriftBudget",
    "DriftEvent",
    "DriftEventRecord",
    "DriftReport",
    "DriftRollbackBridge",
    "DriftState",
    "DriftStateMachine",
    "DriftTrainingPattern",
    "DriftType",
    "EnvDiffReport",
    "EscalationEntry",
    "FileAttrIssue",
    "FileChange",
    "FileIntegrityRecord",
    "FixSnapshot",
    "FixtureDriftEvent",
    "ForensicsConfig",
    "ForensicsReport",
    "ForensicsTimelineEntry",
    "FunctionSignature",
    "GatePersistence",
    "GitBisector",
    "GitignoreAudit",
    "HandoffPackage",
    "HashChainEntry",
    "HeadlessDiffEntry",
    "HealthSnapshot",
    "HotfixAuditEntry",
    "HotfixBypass",
    "IncrementalScanner",
    "InjectedContext",
    "InjectionLevel",
    "InterruptLog",
    "InvalidTransitionError",
    "KnowledgeGraphSyncResult",
    "MaintenanceWindow",
    "ModuleScore",
    "MultiBaselineVote",
    "NamingMagicAlert",
    "OrphanClassification",
    "OrphanFile",
    "OrphanResource",
    "OwnerStatus",
    "PartialDeploymentRecord",
    "PythonCompatIssue",
    "QueuedScan",
    "ROIEngine",
    "ROIScore",
    "RecoveryManager",
    "ResourceLimits",
    "ResourceSnapshot",
    "ResourceStatus",
    "ResultCache",
    "Runbook",
    "ScanLevel",
    "ScanLockRecord",
    "ScanMutex",
    "ScanResult",
    "SecurityPolicyDriftResult",
    "SemanticDriftResult",
    "Severity",
    "Suggestion",
    "SuppressionLearner",
    "SuppressionRule",
    "SymlinkIssue",
    "TestCoverageDriftResult",
    "TopDriftItem",
    "TrendAlert",
    "TrendAnalyzer",
    "TrendMetrics",
    "__main__",
    "_analysis",
    "_core",
    "_drift",
    "_infrastructure",
    "_scanners",
    "abort_handoff",
    "absence_manager",
    "ai_construction_detectors",
    "ai_context_injector",
    "alert_router",
    "apply_degradation",
    "audit_gitignore",
    "auto_fix_compat",
    "backcompat_checker",
    "baseline_manager",
    "baseline_poisoning_guard",
    "benchmark_integrity",
    "bootstrap",
    "bootstrap_self_check",
    "brain_integration",
    "build_handoff_package",
    "build_hash_chain",
    "build_health_snapshot",
    "build_report",
    "build_runbook_frontmatter",
    "build_top_drifts",
    "canary_controller",
    "capture_baseline",
    "cascade_detector",
    "chaos_injector",
    "check_absence",
    "check_broken_symlinks",
    "check_budget_for_gate",
    "check_core_files",
    "check_encoding",
    "check_large_diff",
    "check_registry_parsable",
    "check_size_anomaly",
    "classify_event_id",
    "cold_start",
    "compare_signatures",
    "config_consistency",
    "consume_budget",
    "contract_drift_detector",
    "correlation_engine",
    "count_states",
    "credibility_engine",
    "cross_module_score",
    "cross_validate_baseline",
    "dashboard",
    "declare_maintenance_window",
    "detect_ai_training_loop",
    "detect_anomalies",
    "detect_cascade",
    "detect_concept_cardinality",
    "detect_conflicts",
    "detect_contract_drift",
    "detect_cross_language_drift",
    "detect_db_schema_drift",
    "detect_dep_version_drift",
    "detect_doc_code_coevolution",
    "detect_enum_value_sync",
    "detect_intentional_breaks",
    "detect_knowledge_graph_sync",
    "detect_missing_env",
    "detect_owner_return",
    "detect_ownership_consistency",
    "detect_partial_deployment",
    "detect_python_dead_code",
    "detect_security_policy_drift",
    "detect_test_coverage_drift",
    "detector_dispatcher",
    "differential_detection",
    "drift_engine",
    "drift_hotfix_bypass",
    "drift_infrastructure",
    "drift_models",
    "drift_result_types",
    "drift_training",
    "dry_run_impact_analysis",
    "escalate_if_absent",
    "events",
    "extract_hardcoded_defaults",
    "extract_signatures",
    "extract_training_patterns",
    "file_attr_checker",
    "find_orphan_data",
    "find_orphan_docs",
    "find_orphan_scripts",
    "find_over_ignored_critical",
    "find_renamed_functions",
    "find_uncovered_types",
    "find_untracked_generated",
    "forensics_engine",
    "gate_persistence",
    "generate_audit_log",
    "generate_bulk_runbook",
    "generate_compat_report",
    "generate_config_sync",
    "generate_forensics_report",
    "generate_integrity_manifest",
    "generate_runbook",
    "get_canary_history",
    "get_maintenance_window",
    "get_max_parallel_for_level",
    "get_or_create_budget",
    "git_bisector",
    "git_checkout_snapshot",
    "gitignore_auditor",
    "guard_loop",
    "handoff_manager",
    "headless_scan_light",
    "headless_scanner",
    "import_hallucination",
    "incremental_scanner",
    "init_database",
    "init_directories",
    "inject_fake_todo_bomb",
    "inject_full",
    "inject_minimal",
    "inject_path_rename",
    "inject_patterns_to_prompt",
    "inject_standard",
    "inject_yaml_field_flip",
    "is_auto_fix_paused",
    "is_guard_running",
    "load_detector_registry",
    "load_package",
    "ml_engineering",
    "model_drift_monitor",
    "multi_baseline_vote",
    "naming_magic_checker",
    "orphan_scanner",
    "parse_env_config",
    "parse_gitignore",
    "parse_interrupt_log",
    "parse_python_imports",
    "parse_python_public_api",
    "parse_yaml_config",
    "performance_baseline",
    "promote_detector",
    "push_to_evolution_engine",
    "python_compat",
    "reconciler",
    "record_activity",
    "regime_detector",
    "register_env_tags",
    "replay_baseline_history",
    "resource_guard",
    "resume_workflow",
    "roi_engine",
    "rollback_bridge",
    "rollback_detector",
    "run_backcompat_check",
    "run_canary",
    "run_chaos_experiment",
    "run_config_audit",
    "run_fixture_check",
    "run_self_check",
    "runbook_generator",
    "scan",
    "scan_expected_output_drift",
    "scan_fixture_schema_drift",
    "scan_impact",
    "scan_mock_target_drift",
    "scan_mutex",
    "scan_naming_magic",
    "scan_on_commit",
    "scan_orphan_resources",
    "scan_phase_gate",
    "scan_python_compat",
    "scheduled_deep",
    "scheduled_light",
    "self_check",
    "self_test_verifier",
    "serialize_package",
    "serialize_report",
    "session_entry_activate",
    "set_critical_handler",
    "set_severity_limit",
    "setup_append_only",
    "sha256_file",
    "snapshot",
    "snapshot_event_hash",
    "state_machine",
    "stop_guard_loop",
    "suppression_learner",
    "symlink_checker",
    "tamper_proof_audit",
    "test_fixture_checker",
    "track_training_effectiveness",
    "trend_analyzer",
    "validate_scalability",
    "verify_hash_chain",
    "verify_integrity",
'artifact_scanner', 'autonomy_regressor', 'bootstrapping_calibrator', 'drift_detector', 'reward_hacking_rebound_detector', 'silence_detector', 'spiral_ews', 'vigil_runtime']
