"""[A_module] module_id=MOD-AUTONOMY_CORE | layer=infrastructure | stability=evolving | safety=L | ai_autonomy=ai_modifiable

autonomy_core 包结构指引（ARCH-033 治本）：
- skill_*.py → skills/ 子包（技能子系统，MODULE_LIST 封闭集合）
- context_*.py + ce_*.py → context/ 子包（上下文引擎子系统；ce_*.py 是工具/playground 层，原 ce/ 子包已合并）
- 其余独立功能模块平铺根目录（命名即分类，无前缀簇不强行归位）

查找方式：Glob src/zephyr/autonomy_core/**/*.py 实时列出所有模块
新建模块：按文件名前缀归位对应子包；无前缀的独立模块放根目录平铺
"""

__all__ = [
    "adversarial_robustness",
    "agent_observability",
    "alignment_scorer",
    "all_skill_modules",
    "architecture_context_loader",
    "atomic_injector",
    "budget_forecaster",
    "cache_invalidation",
    "checkpoint_manager",
    "citation_walker",
    "cold_start_booster",
    "complexity_budget",
    "config_safety_guard",
    "contextual_fetch_api",
    "curation_loop",
    "dependency_tracker",
    "diff_injector",
    "dispatch_table",
    "diversity_constraint",
    "doc_compressor",
    "domain_decay_config",
    "embedding_version_lock",
    "spec_engine",
    "fallback_staleness_gate",
    "file_autoregister",
    "fragmentation_index",
    "host_resource_governor",
    "ide_watcher",
    "integrity_check",
    "intent_keyword_mapper",
    "intent_parser",
    "kill_switch",
    "knowledge_distiller",
    "ce_file_lister",
    "lsg_pattern_tracker",
    "memory_bank",
    "mode_manager",
    "otel_instrumentation",
    "pattern_library",
    "phase_planner",
    "pipeline_orchestrator",
    "poisoning_monitor",
    "position_optimizer",
    "progressive_disclosure_injector",
    "prompt_registry",
    "ke_justification",
    "skill_rbac_registry",
    "self_diagnosis",
    "self_evolution_fidelity_gate",
    "sensitivity_classifier",
    "session_learner",
    "shadow_canary",
    "solo_dev_safety_net",
    "staleness_manager",
    "system_snapshot",
    "task_context_builder",
    "token_budget",
    "trigger_router",
    "vector_bridge",
    "vector_writer",
    "verify_paths",
    "vibe_coding_quality_gate",
]
