# [A_module] module_id=MOD-INF_observability | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] task_bound
"""
Auto-generated contracts package — system-telemetry

Generated by: scripts/governance/d5_architecture/generate_contracts.py
"""

__all__ = [
    "ContractMetricsCollector",
    "DriftAlert",
    "SlaRecord",
    "TelemetryHealth",
    "TelemetryMetrics",
    "contract_metrics",
    "get_contract_metrics",
    "health_probes",
    "notifier",
    "trace_decorator",
]
