# [BLUEPRINT] MOD-INF-016 | (auto-injected by S4 reconciler) | §
# [TTL] permanent
# [A_module] module_id=MOD-INF-observability | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
"""
Auto-generated contracts package — system-telemetry

Generated by: scripts/governance/d5_architecture/generate_contracts.py

# [ALGO_FLOW] external: docs/03_modules/_domain_infrastructure/algo_flow/observability/observability__init__.yaml
"""

__all__ = [
    "notifier",
    "trace_decorator",
]
