# [BLUEPRINT] MOD-INF-016 | (auto-injected by S4 reconciler) | §
# [TTL] permanent
# [A_module] module_id=MOD-INF_observability | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] permanent
"""
Auto-generated contracts package — system-telemetry

Generated by: scripts/governance/d5_architecture/generate_contracts.py
"""

__all__ = [
    "notifier",
    "trace_decorator",
]
