"""
api_client.py —— Re-export wrapper → canonical: zephyr.shared.api.api_client

Backward-compatible top-level alias. Canonical implementation at api/api_client.py.
Edit api/api_client.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.api.api_client import *  # noqa: F401, F403
