# [BLUEPRINT] MOD-INF-016 | 03_modules/_cross_layer/shared-core/blueprint.md | §

# [MODULE] zephyr.shared.API_INDEX

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
API_INDEX.py —— Re-export wrapper → canonical: zephyr.shared.api.api_index

Backward-compatible top-level alias. Canonical implementation at api/api_index.py.
Edit api/api_index.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.api.api_index import *  # noqa: F401, F403
