"""
API_INDEX.py —— Re-export wrapper → canonical: zephyr.shared.api.api_index

Backward-compatible top-level alias. Canonical implementation at api/api_index.py.
Edit api/api_index.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.api.api_index import *  # noqa: F401, F403
