# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared_core/blueprint.md | §
# [MODULE] zephyr.shared.api_client
# [DOMAIN] D-SHARED
# [DEPENDENCIES] zephyr.shared.api.api_client
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-SHR_api_client | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable

"""
api_client.py —— Re-export wrapper → canonical: zephyr.shared.api.api_client

Backward-compatible top-level alias. Canonical implementation at api/api_client.py.
Edit api/api_client.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.api.api_client import *  # noqa: F403
