# [A_module] module_id=MOD-SHR_blueprint_scorer | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md | §

# [MODULE] zephyr.shared.blueprint_scorer

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
blueprint_scorer.py — Re-export wrapper → canonical: zephyr.governance.audit_orchestration.blueprint_scorer

Backward-compatible top-level alias. Canonical implementation at orchestrator/blueprint_scorer.py.
Edit orchestrator/blueprint_scorer.py to modify logic — do NOT edit this file.
"""

import importlib

# Re-export shim — canonical: zephyr.governance.audit_orchestration.blueprint_scorer
_mod = importlib.import_module("zephyr.governance.audit_orchestration.blueprint_scorer")
for _name in getattr(_mod, "__all__", [n for n in dir(_mod) if not n.startswith("_")]):
    globals()[_name] = getattr(_mod, _name)
del _mod, _name
