"""
blueprint_scorer.py —— Re-export wrapper → canonical: zephyr.shared.utils.blueprint_scorer

Backward-compatible top-level alias. Canonical implementation at utils/blueprint_scorer.py.
Edit utils/blueprint_scorer.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.utils.blueprint_scorer import *  # noqa: F401, F403
