# [BLUEPRINT] MOD-INF-016 | 03_modules/_cross_layer/shared-core/blueprint.md | §

# [MODULE] zephyr.shared.blueprint_scorer

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
blueprint_scorer.py — Re-export wrapper → canonical: zephyr.orchestrator.blueprint_scorer

Backward-compatible top-level alias. Canonical implementation at orchestrator/blueprint_scorer.py.
Edit orchestrator/blueprint_scorer.py to modify logic — do NOT edit this file.
"""

from zephyr.orchestrator.blueprint_scorer import *  # noqa: F401, F403
