# [BLUEPRINT] MOD-INF-016 | 03_modules/_cross_layer/shared-core/blueprint.md | §

# [MODULE] zephyr.shared.capability

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
capability.py —— Re-export wrapper → canonical: zephyr.shared.security.capability

Backward-compatible top-level alias. Canonical implementation at security/capability.py.
Edit security/capability.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.security.capability import *  # noqa: F401, F403
