"""
capability.py —— Re-export wrapper → canonical: zephyr.shared.security.capability

Backward-compatible top-level alias. Canonical implementation at security/capability.py.
Edit security/capability.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.security.capability import *  # noqa: F401, F403
