# [BLUEPRINT] MOD-INF-016 | 03_modules/_cross_layer/shared-core/blueprint.md | §

# [MODULE] zephyr.shared.constants

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
constants.py —— Re-export wrapper → canonical: zephyr.shared.foundation.constants

Backward-compatible top-level alias. Canonical implementation at foundation/constants.py.
Edit foundation/constants.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.foundation.constants import *  # noqa: F401, F403
