# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared_core/blueprint.md | §
# [MODULE] zephyr.shared.constants
# [DOMAIN] D-SHARED
# [DEPENDENCIES] zephyr.shared.foundation.constants
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-SHR_constants | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] task_bound

"""
constants.py —— Re-export wrapper → canonical: zephyr.shared.foundation.constants

Backward-compatible top-level alias. Canonical implementation at foundation/constants.py.
Edit foundation/constants.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.foundation.constants import *  # noqa: F403
