"""
content_fingerprint.py —— Re-export wrapper → canonical: zephyr.shared.io.content_fingerprint

Backward-compatible top-level alias. Canonical implementation at io/content_fingerprint.py.
Edit io/content_fingerprint.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.io.content_fingerprint import *  # noqa: F401, F403
