# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md | §
# [MODULE] zephyr.shared.deprecation
# [DOMAIN] D-SHARED
# [DEPENDENCIES] zephyr.shared.foundation.deprecation
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-SHR_deprecation | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable

"""
deprecation.py —— Re-export wrapper → canonical: zephyr.shared.foundation.deprecation

Backward-compatible top-level alias. Canonical implementation at foundation/deprecation.py.
Edit foundation/deprecation.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.foundation.deprecation import *  # noqa: F403
