# [BLUEPRINT] MOD-INF-016 | 03_modules/_cross_layer/shared-core/blueprint.md | §

# [MODULE] zephyr.shared.deprecation

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
deprecation.py —— Re-export wrapper → canonical: zephyr.shared.foundation.deprecation

Backward-compatible top-level alias. Canonical implementation at foundation/deprecation.py.
Edit foundation/deprecation.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.foundation.deprecation import *  # noqa: F401, F403
