"""
deprecation.py —— Re-export wrapper → canonical: zephyr.shared.foundation.deprecation

Backward-compatible top-level alias. Canonical implementation at foundation/deprecation.py.
Edit foundation/deprecation.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.foundation.deprecation import *  # noqa: F401, F403
