"""
diff_utils.py —— Re-export wrapper → canonical: zephyr.shared.utils.diff_utils

Backward-compatible top-level alias. Canonical implementation at utils/diff_utils.py.
Edit utils/diff_utils.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.utils.diff_utils import *  # noqa: F401, F403
