# [BLUEPRINT] MOD-INF-016 | 03_modules/_cross_layer/shared-core/blueprint.md | §

# [MODULE] zephyr.shared.diff_utils

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
diff_utils.py —— Re-export wrapper → canonical: zephyr.shared.utils.diff_utils

Backward-compatible top-level alias. Canonical implementation at utils/diff_utils.py.
Edit utils/diff_utils.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.utils.diff_utils import *  # noqa: F401, F403
