# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared_core/blueprint.md | §
# [MODULE] zephyr.shared.env
# [DOMAIN] D_SHARED
# [DEPENDENCIES] zephyr.shared.foundation.env
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-SHR_env | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] task_bound

"""
env.py —— Re-export wrapper → canonical: zephyr.shared.foundation.env

Backward-compatible top-level alias. Canonical implementation at foundation/env.py.
Edit foundation/env.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.foundation.env import *  # noqa: F403
