"""
env.py —— Re-export wrapper → canonical: zephyr.shared.foundation.env

Backward-compatible top-level alias. Canonical implementation at foundation/env.py.
Edit foundation/env.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.foundation.env import *  # noqa: F401, F403
