"""
file_utils.py —— Re-export wrapper → canonical: zephyr.shared.io.file_utils

Backward-compatible top-level alias. Canonical implementation at io/file_utils.py.
Edit io/file_utils.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.io.file_utils import *  # noqa: F401, F403
