# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared_core/blueprint.md | §
# [MODULE] zephyr.shared.flags
# [DOMAIN] D-SHARED
# [DEPENDENCIES] zephyr.shared.foundation.flags
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-SHR_flags | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable

"""
flags.py —— Re-export wrapper → canonical: zephyr.shared.foundation.flags

Backward-compatible top-level alias. Canonical implementation at foundation/flags.py.
Edit foundation/flags.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.foundation.flags import *  # noqa: F403
