"""
flags.py —— Re-export wrapper → canonical: zephyr.shared.foundation.flags

Backward-compatible top-level alias. Canonical implementation at foundation/flags.py.
Edit foundation/flags.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.foundation.flags import *  # noqa: F401, F403
