# [BLUEPRINT] MOD-INF-016 | 03_modules/_cross_layer/shared-core/blueprint.md | §

# [MODULE] zephyr.shared.frontmatter_utils

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
frontmatter_utils.py —— Re-export wrapper → canonical: zephyr.shared.io.frontmatter_utils

Backward-compatible top-level alias. Canonical implementation at io/frontmatter_utils.py.
Edit io/frontmatter_utils.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.io.frontmatter_utils import *  # noqa: F401, F403
