"""
frontmatter_utils.py —— Re-export wrapper → canonical: zephyr.shared.io.frontmatter_utils

Backward-compatible top-level alias. Canonical implementation at io/frontmatter_utils.py.
Edit io/frontmatter_utils.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.io.frontmatter_utils import *  # noqa: F401, F403
