# [BLUEPRINT] MOD-INF-016 | 03_modules/_cross_layer/shared-core/blueprint.md | §

# [MODULE] zephyr.shared.health

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
health.py —— Re-export wrapper → canonical: zephyr.shared.observability.health

Backward-compatible top-level alias. Canonical implementation at observability/health.py.
Edit observability/health.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.observability.health import *  # noqa: F401, F403
