# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md | §
# [MODULE] zephyr.shared.health
# [DOMAIN] D-SHARED
# [DEPENDENCIES] zephyr.ops.observability.health
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] production
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-SHR_health | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable

"""
health.py —— Re-export wrapper → canonical: zephyr.ops.observability.health

Backward-compatible top-level alias. Canonical implementation at observability/health.py.
Edit observability/health.py to modify logic — do NOT edit this file.
"""

from zephyr.ops.observability.health import *  # noqa: F403
