"""
health.py —— Re-export wrapper → canonical: zephyr.shared.observability.health

Backward-compatible top-level alias. Canonical implementation at observability/health.py.
Edit observability/health.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.observability.health import *  # noqa: F401, F403
