"""
idempotency.py —— Re-export wrapper → canonical: zephyr.shared.infra.idempotency

Backward-compatible top-level alias. Canonical implementation at infra/idempotency.py.
Edit infra/idempotency.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.infra.idempotency import *  # noqa: F401, F403
