"""
limiter.py —— Re-export wrapper → canonical: zephyr.shared.infra.limiter

Backward-compatible top-level alias. Canonical implementation at infra/limiter.py.
Edit infra/limiter.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.infra.limiter import *  # noqa: F401, F403
