"""
lock.py —— Re-export wrapper → canonical: zephyr.shared.infra.lock

Backward-compatible top-level alias. Canonical implementation at infra/lock.py.
Edit infra/lock.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.infra.lock import *  # noqa: F401, F403
