# [A_module] module_id=MOD-SHR_migration | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md | §

# [MODULE] zephyr.shared.migration

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
migration.py —— Re-export wrapper → canonical: zephyr.shared.utils.migration

Backward-compatible top-level alias. Canonical implementation at utils/migration.py.
Edit utils/migration.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.utils.migration import *  # noqa: F401, F403
