"""
migration.py —— Re-export wrapper → canonical: zephyr.shared.utils.migration

Backward-compatible top-level alias. Canonical implementation at utils/migration.py.
Edit utils/migration.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.utils.migration import *  # noqa: F401, F403
