# [A_module] module_id=MOD-SHR_observer | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md | §

# [MODULE] zephyr.shared.observer

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
observer.py —— Re-export wrapper → canonical: zephyr.shared.infra.observer

Backward-compatible top-level alias. Canonical implementation at infra/observer.py.
Edit infra/observer.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.infra.observer import *  # noqa: F401, F403
