"""
observer.py —— Re-export wrapper → canonical: zephyr.shared.infra.observer

Backward-compatible top-level alias. Canonical implementation at infra/observer.py.
Edit infra/observer.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.infra.observer import *  # noqa: F401, F403
