"""
outbox.py —— Re-export wrapper → canonical: zephyr.shared.infra.outbox

Backward-compatible top-level alias. Canonical implementation at infra/outbox.py.
Edit infra/outbox.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.infra.outbox import *  # noqa: F401, F403
