# [BLUEPRINT] MOD-INF-016 | 03_modules/_cross_layer/shared-core/blueprint.md | §

# [MODULE] zephyr.shared.outbox

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
outbox.py —— Re-export wrapper → canonical: zephyr.shared.infra.outbox

Backward-compatible top-level alias. Canonical implementation at infra/outbox.py.
Edit infra/outbox.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.infra.outbox import *  # noqa: F401, F403
