"""
pagination.py —— Re-export wrapper → canonical: zephyr.shared.utils.pagination

Backward-compatible top-level alias. Canonical implementation at utils/pagination.py.
Edit utils/pagination.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.utils.pagination import *  # noqa: F401, F403
