# [BLUEPRINT] MOD-INF-016 | 03_modules/_cross_layer/shared-core/blueprint.md | §

# [MODULE] zephyr.shared.paths

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
paths.py —— Re-export wrapper → canonical: zephyr.shared.io.paths

Backward-compatible top-level alias. Canonical implementation at io/paths.py.
Edit io/paths.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.io.paths import *  # noqa: F401, F403
