"""
paths.py —— Re-export wrapper → canonical: zephyr.shared.io.paths

Backward-compatible top-level alias. Canonical implementation at io/paths.py.
Edit io/paths.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.io.paths import *  # noqa: F401, F403
