# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared_core/blueprint.md | §
# [MODULE] zephyr.shared.paths
# [DOMAIN] D-SHARED
# [DEPENDENCIES] zephyr.shared.io.paths
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-SHR_paths | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable

"""
paths.py —— Re-export wrapper → canonical: zephyr.shared.io.paths

Backward-compatible top-level alias. Canonical implementation at io/paths.py.
Edit io/paths.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.io.paths import *  # noqa: F403
