# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared_core/blueprint.md | §
# [MODULE] zephyr.shared.schema_registry
# [DOMAIN] D_SHARED
# [DEPENDENCIES] zephyr.shared.schema.schema_registry
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-SHR_schema_registry | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] task_bound

"""
schema_registry.py —— Re-export wrapper → canonical: zephyr.shared.schema.schema_registry

Backward-compatible top-level alias. Canonical implementation at schema/schema_registry.py.
Edit schema/schema_registry.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.schema.schema_registry import *  # noqa: F403
