"""
schema_registry.py —— Re-export wrapper → canonical: zephyr.shared.schema.schema_registry

Backward-compatible top-level alias. Canonical implementation at schema/schema_registry.py.
Edit schema/schema_registry.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.schema.schema_registry import *  # noqa: F401, F403
