# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared_core/blueprint.md | §
# [MODULE] zephyr.shared.secrets
# [DOMAIN] D_SHARED
# [DEPENDENCIES] zephyr.shared.security.secrets
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-SHR_secrets | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] task_bound

"""
secrets.py —— Re-export wrapper → canonical: zephyr.shared.security.secrets

Backward-compatible top-level alias. Canonical implementation at security/secrets.py.
Edit security/secrets.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.security.secrets import *  # noqa: F403
