"""
secrets.py —— Re-export wrapper → canonical: zephyr.shared.security.secrets

Backward-compatible top-level alias. Canonical implementation at security/secrets.py.
Edit security/secrets.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.security.secrets import *  # noqa: F401, F403
