"""
ssot_guard.py —— Re-export wrapper → canonical: zephyr.shared.security.ssot_guard

Backward-compatible top-level alias. Canonical implementation at security/ssot_guard.py.
Edit security/ssot_guard.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.security.ssot_guard import *  # noqa: F401, F403
