# [BLUEPRINT] MOD-INF-016 | 03_modules/_cross_layer/shared-core/blueprint.md | §

# [MODULE] zephyr.shared.testing

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
testing.py —— Re-export wrapper → canonical: zephyr.shared.utils.testing

Backward-compatible top-level alias. Canonical implementation at utils/testing.py.
Edit utils/testing.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.utils.testing import *  # noqa: F401, F403
