# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared_core/blueprint.md | §
# [MODULE] zephyr.shared.time_utils
# [DOMAIN] D-SHARED
# [DEPENDENCIES] zephyr.shared.utils.time_utils
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-SHR_time_utils | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable

"""
time_utils.py —— Re-export wrapper → canonical: zephyr.shared.utils.time_utils

Backward-compatible top-level alias. Canonical implementation at utils/time_utils.py.
Edit utils/time_utils.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.utils.time_utils import *  # noqa: F403
