"""
token_utils.py —— Re-export wrapper → canonical: zephyr.shared.observability.token_utils

Backward-compatible top-level alias. Canonical implementation at observability/token_utils.py.
Edit observability/token_utils.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.observability.token_utils import *  # noqa: F401, F403
