"""
tracing.py —— Re-export wrapper → canonical: zephyr.shared.observability.tracing

Backward-compatible top-level alias. Canonical implementation at observability/tracing.py.
Edit observability/tracing.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.observability.tracing import *  # noqa: F401, F403
