# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md | §
# [MODULE] zephyr.shared.tracing
# [DOMAIN] D-SHARED
# [DEPENDENCIES] zephyr.ops.observability.tracing
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-SHR_tracing | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable

"""
tracing.py —— Re-export wrapper → canonical: zephyr.ops.observability.tracing

Backward-compatible top-level alias. Canonical implementation at observability/tracing.py.
Edit observability/tracing.py to modify logic — do NOT edit this file.
"""

from zephyr.ops.observability.tracing import *  # noqa: F403
