# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared_core/blueprint.md | §
# [MODULE] zephyr.shared.types
# [DOMAIN] D_SHARED
# [DEPENDENCIES] zephyr.shared.foundation.types
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-SHR_types | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] task_bound

"""
types.py —— Re-export wrapper → canonical: zephyr.shared.foundation.types

Backward-compatible top-level alias. Canonical implementation at foundation/types.py.
Edit foundation/types.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.foundation.types import *  # noqa: F403
from zephyr.shared.foundation.types import __all__  # noqa: F401
