# [BLUEPRINT] MOD-INF-035 | 03_modules/_cross_layer/auto-runtime-core/blueprint.md | §

# [MODULE] zephyr.shared.utils.blueprint_scorer

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
blueprint_scorer.py — Re-export shim → canonical: zephyr.orchestrator.blueprint_scorer

Backward-compatible alias. Canonical implementation moved to orchestrator/blueprint_scorer.py.
Edit orchestrator/blueprint_scorer.py to modify logic — do NOT edit this file.
"""

from zephyr.orchestrator.blueprint_scorer import *  # noqa: F401, F403
