# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared_core/blueprint.md | §
# [MODULE] zephyr.shared.utils.content_fingerprint
# [DOMAIN] D_SHARED
# [DEPENDENCIES] zephyr.shared.io.content_fingerprint
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-SHR_content_fingerprint | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] permanent

"""
content_fingerprint.py —— Re-export wrapper -> canonical: zephyr.shared.io.content_fingerprint

Backward-compatible top-level alias. Canonical implementation at io/content_fingerprint.py.
Edit io/content_fingerprint.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.io.content_fingerprint import *  # noqa: F403
