# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared_core/blueprint.md | §
# [MODULE] zephyr.shared.utils.file_utils
# [DOMAIN] D_SHARED
# [DEPENDENCIES] zephyr.shared.io.file_utils
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-SHR_file_utils | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] permanent

"""
file_utils.py —— Re-export wrapper → canonical: zephyr.shared.io.file_utils

Backward-compatible top-level alias. Canonical implementation at io/file_utils.py.
Edit io/file_utils.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.io.file_utils import *  # noqa: F403
