# [BLUEPRINT] MOD-INF-039 | docs/03_modules/_cross_layer/agent-orchestrator/blueprint.md
# [MODULE] zephyr.orchestrator.contracts.contract_registry
# [DOMAIN] D_ORCHESTRATOR
# [DEPENDENCIES] zephyr.shared.contracts.core.registry
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] stable
# [SAFETY] M
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-ORC_contract_registry | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] permanent

"""
集成契约注册表（Contract Registry）

依据：MOD-MASTER-002 蓝图 §二 集成契约登记表
注册全部 17 条核心 CT-* 集成契约，提供查询、ai_read_only_hint 检查功能。

ai_read_only_hint 四级：
- DO_NOT_CALL -> 拒绝调用（契约不存在/未实现）
- IMPL_REQUIRED -> 拒绝调用（需先完成实现）
- CAUTION_STUB -> 允许调用但 warn 消费者
- SAFE -> 允许调用
"""

from __future__ import annotations

from typing import Final
from enum import Enum

from pydantic import BaseModel, Field


class AIReadOnlyHint(str, Enum):
    DO_NOT_CALL = "DO_NOT_CALL"
    IMPL_REQUIRED = "IMPL_REQUIRED"
    CAUTION_STUB = "CAUTION_STUB"
    SAFE = "SAFE"


class TelemetryType(str, Enum):
    RED = "RED"
    USE = "USE"


class Contract(BaseModel):
    contract_id: str = Field(min_length=1)
    producer: str
    consumer: str
    status: str
    ai_read_only_hint: AIReadOnlyHint
    trigger: str = ""
    input_schema: str = ""
    output_schema: str = ""
    telemetry: TelemetryType = TelemetryType.RED
    telemetry_metrics: list[str] = Field(default_factory=list)
    ai_prompt: str = ""
    route_target: str = ""


CONTRACTS: Final[dict[str, Contract]] = {
    "CT-ORC-SCRIPT-001": Contract(
        contract_id="CT-ORC-SCRIPT-001",
        producer="Orchestrator",
        consumer="Script System",
        status="部分实现",
        ai_read_only_hint=AIReadOnlyHint.CAUTION_STUB,
        trigger="脚本系统产出 Findings 时评估 severity",
        input_schema="Finding",
        output_schema="TaskCard",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="脚本系统产出 Findings -> severity 评估 -> CRITICAL/HIGH 创建 OPS 任务卡",
        route_target="script-system",
    ),
    "CT-ORC-CE-001": Contract(
        contract_id="CT-ORC-CE-001",
        producer="Orchestrator",
        consumer="Context Engine",
        status="骨架",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="Orc 请求为任务构建上下文",
        input_schema="TaskCard",
        output_schema="ContextPackage",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Orc 请求构建上下文 -> CE 四阶段处理 -> 返回 ContextPackage",
        route_target="context-engine",
    ),
    "CT-ORC-VMS-001": Contract(
        contract_id="CT-ORC-VMS-001",
        producer="Orchestrator",
        consumer="Vector Memory Service",
        status="骨架",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="Orc 完成任务后写入输出向量",
        input_schema="TaskCard",
        output_schema="VectorEntry",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Orc 完成任务 -> TaskCard 输出 -> VMS 写入向量",
        route_target="vector-memory",
    ),
    "CT-ORC-GATE-001": Contract(
        contract_id="CT-ORC-GATE-001",
        producer="Orchestrator",
        consumer="Gate Engine",
        status="部分实现",
        ai_read_only_hint=AIReadOnlyHint.CAUTION_STUB,
        trigger="Orc 在任务生命周期中调用门禁",
        input_schema="TaskCard",
        output_schema="GateDecision",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Orc 在任务生命周期 -> 调用 Gates 门禁 -> G0-G7 判定",
        route_target="gate-engine",
    ),
    "CT-SCRIPT-KB-001": Contract(
        contract_id="CT-SCRIPT-KB-001",
        producer="Script System",
        consumer="Knowledge Base",
        status="蓝图已定义",
        ai_read_only_hint=AIReadOnlyHint.IMPL_REQUIRED,
        trigger="脚本系统产出 MEDIUM severity Finding",
        input_schema="Finding",
        output_schema="KnowledgeEntry",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Script 产出 MEDIUM Finding -> KB 入库为 KE",
        route_target="knowledge-base",
    ),
    "CT-SCRIPT-GATE-001": Contract(
        contract_id="CT-SCRIPT-GATE-001",
        producer="Script System",
        consumer="Gate Engine",
        status="部分实现",
        ai_read_only_hint=AIReadOnlyHint.CAUTION_STUB,
        trigger="Script 退出码评估",
        input_schema="ScriptResult",
        output_schema="GateDecision",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Script Exit Code -> Gate 决策 -> 通过/阻塞/告警",
        route_target="gate-engine",
    ),
    "CT-CE-VMS-001": Contract(
        contract_id="CT-CE-VMS-001",
        producer="Context Engine",
        consumer="Vector Memory Service",
        status="已实现:VectorBridge已建桥接(含超时/降级/结果解析),8 Collection全量检索已接通",
        ai_read_only_hint=AIReadOnlyHint.SAFE,
        trigger="CE 需要从 VMS 检索知识向量",
        input_schema="ContextQuery",
        output_schema="VectorResult",
        telemetry=TelemetryType.USE,
        telemetry_metrics=["utilization", "saturation", "error"],
        ai_prompt="CE 构建上下文 -> VMS 向量检索(8 collection: decisions/code_context/lessons/knowledge/rules/blueprints/session_snapshots/execution_traces) -> 注入上下文",
        route_target="vector-memory",
    ),
    "CT-CE-LSG-001": Contract(
        contract_id="CT-CE-LSG-001",
        producer="Context Engine",
        consumer="LLM Security Gateway",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="CE 在 context injection 前检查安全性",
        input_schema="ContextPackage",
        output_schema="SecurityDecision",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="CE 上下文注入前 -> LSG 安全检查 -> 通过/阻断",
        route_target="llm-security",
    ),
    "CT-KB-VMS-001": Contract(
        contract_id="CT-KB-VMS-001",
        producer="Knowledge Base",
        consumer="Vector Memory Service",
        status="beta",
        ai_read_only_hint=AIReadOnlyHint.CAUTION_STUB,
        trigger="KB 创建/更新 KE 时同步向量",
        input_schema="KnowledgeEntry",
        output_schema="VectorEntry",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="KB 管理 KE -> VMS 向量同步 -> 可检索",
        route_target="vector-memory",
    ),
    "CT-FLE-ORC-001": Contract(
        contract_id="CT-FLE-ORC-001",
        producer="Feedback Loop Engine",
        consumer="Orchestrator",
        status="部分实现:decision_engine已创建(Orc->FLE方向),FLE->Orc方向通过Protocol适配器待接通",
        ai_read_only_hint=AIReadOnlyHint.CAUTION_STUB,
        trigger="FLE 检测到异常 -> 调整调度策略",
        input_schema="AnomalyReport",
        output_schema="ScheduleAdjustment",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="FLE 异常检测 -> Orc 调度调整 -> 闭环改进(Orc->FLE已通,FLE->Orc通过Protocol待接通)",
        route_target="orchestrator",
    ),
    "CT-FLE-DB-001": Contract(
        contract_id="CT-FLE-DB-001",
        producer="Feedback Loop Engine",
        consumer="Database",
        status="部分实现:metrics_collector已sqlite3持久化metrics表(create/record/bulk_record/query/aggregate),未通过正式zephyr.trading.db契约路径",
        ai_read_only_hint=AIReadOnlyHint.CAUTION_STUB,
        trigger="FLE 持久化指标数据",
        input_schema="FLEMetrics",
        output_schema="DBWriteResult",
        telemetry=TelemetryType.USE,
        telemetry_metrics=["utilization", "saturation", "error"],
        ai_prompt="FLE 指标采集 -> db 持久化 -> 历史分析(metrics_collector已有sqlite3实现,需迁移到zephyr.trading.db正式契约)",
        route_target="database",
    ),
    "CT-TELE-FLE-001": Contract(
        contract_id="CT-TELE-FLE-001",
        producer="System Telemetry",
        consumer="Feedback Loop Engine",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="Telemetry 推送指标到 FLE",
        input_schema="TelemetryData",
        output_schema="FLEIngestResult",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Telemetry 推送 -> FLE 摄入 -> 异常检测",
        route_target="feedback-loop",
    ),
    "CT-PIPE-ORC-001": Contract(
        contract_id="CT-PIPE-ORC-001",
        producer="Task Pipeline",
        consumer="Orchestrator",
        status="task_queue直接import PipelineOrchestrator",
        ai_read_only_hint=AIReadOnlyHint.SAFE,
        trigger="Pipeline 为 TaskCard 选择管线路由",
        input_schema="TaskCard",
        output_schema="PipelineRoute",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Pipeline 接收 TaskCard -> 路由决策 -> A区/B区管线",
        route_target="pipeline",
    ),
    "CT-ORC-DB": Contract(
        contract_id="CT-ORC-DB",
        producer="Orchestrator",
        consumer="Database",
        status="18处import确认已实现:TaskRepository/sqlite_schema贯穿全Orc",
        ai_read_only_hint=AIReadOnlyHint.SAFE,
        trigger="Orc 通过 TaskRepository 执行 CRUD",
        input_schema="TaskCard",
        output_schema="DBWriteResult",
        telemetry=TelemetryType.USE,
        telemetry_metrics=["utilization", "saturation", "error"],
        ai_prompt="Orc -> TaskRepository -> db CRUD -> FTS5 全文搜索",
        route_target="database",
    ),
    "CT-CBAC-001": Contract(
        contract_id="CT-CBAC-001",
        producer="Gate Engine",
        consumer="全系统",
        status="部分实现",
        ai_read_only_hint=AIReadOnlyHint.CAUTION_STUB,
        trigger="Gate Engine 检查 AI Agent 能力边界",
        input_schema="AgentCapability",
        output_schema="CapabilityDecision",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="CBAC 矩阵 -> 能力边界检查 -> Agent 准入判定",
        route_target="gate-engine",
    ),
    "CT-CDC-001": Contract(
        contract_id="CT-CDC-001",
        producer="全系统",
        consumer="Gate Engine",
        status="部分实现",
        ai_read_only_hint=AIReadOnlyHint.CAUTION_STUB,
        trigger="Can-I-Deploy 预部署检查",
        input_schema="DeployRequest",
        output_schema="DeployDecision",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="CDC 消费者驱动契约 -> 预部署验证 -> Can-I-Deploy",
        route_target="gate-engine",
    ),
    "CT-SESSION-handoff-001": Contract(
        contract_id="CT-SESSION-handoff-001",
        producer="全系统",
        consumer="AI Session",
        status="新建",
        ai_read_only_hint=AIReadOnlyHint.CAUTION_STUB,
        trigger="AI Session 启停时检查 Handoff Manifest",
        input_schema="SessionContext",
        output_schema="HandoffManifest",
        telemetry=TelemetryType.USE,
        telemetry_metrics=["utilization", "saturation"],
        ai_prompt="Session 启停 -> Handoff Manifest -> 上下文可恢复",
        route_target="session-state",
    ),
    "CT-RBK-GATE-001": Contract(
        contract_id="CT-RBK-GATE-001",
        producer="Rollback System",
        consumer="Gate Engine",
        status="协议定义完成(51 exit code+映射表),运行时集成未连通:Gate/Pipeline未消费EXIT_CODE_TO_GATE_ACTION",
        ai_read_only_hint=AIReadOnlyHint.CAUTION_STUB,
        trigger="Rollback Exit Code 触发 Gate/Pipeline 联合判定",
        input_schema="RollbackExitCode",
        output_schema="GatePipelineAction",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Rollback Exit Code -> Gate 判定 + Pipeline 行为 -> 51 exit code 回滚出口(协议已定义,运行时桥接待接通)",
        route_target="rollback",
    ),
    "CT-RB-001": Contract(
        contract_id="CT-RB-001",
        producer="MOD-INF-030",
        consumer="MOD-INF-027",
        status="planned",
        ai_read_only_hint=AIReadOnlyHint.IMPL_REQUIRED,
        trigger="audit-orchestrator.phase_5",
        input_schema="RedBlueRequest",
        output_schema="RedBlueReport",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="红白对抗验证->审计编排器Phase5:攻击注入->防御验证->绕过记录->自愈闭环",
        route_target="red-blue-validator.scan",
    ),
    "CT-RB-002": Contract(
        contract_id="CT-RB-002",
        producer="MOD-INF-030",
        consumer="MOD-INF-031",
        status="planned",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="red_blue.bypass_detected",
        input_schema="BypassEntry",
        output_schema="FixResult",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="红白对抗绕过->自动修复引擎:绕过条目->修复执行->修复验证",
        route_target="auto-fix-engine.fix",
    ),
    "CT-RB-003": Contract(
        contract_id="CT-RB-003",
        producer="MOD-INF-030",
        consumer="MOD-INF-020",
        status="planned",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="red_blue.session_complete",
        input_schema="RedBlueReport",
        output_schema="AuditEntry",
        telemetry=TelemetryType.USE,
        telemetry_metrics=["utilization", "saturation"],
        ai_prompt="红白对抗报告->审计轨迹:对抗结果->审计条目->不可篡改记录",
        route_target="audit-trail.record",
    ),
    "CT-HEALTH-001": Contract(
        contract_id="CT-HEALTH-001",
        producer="System Telemetry",
        consumer="全系统",
        status="部分实现:AggregateHealth已存在(异步健康检查/三态判定/JSON序列化),gate_health.py已有SLI仪表板,需注册到全系统Discovery",
        ai_read_only_hint=AIReadOnlyHint.CAUTION_STUB,
        trigger="全系统 liveness/readiness/degraded 三态探针",
        input_schema="HealthProbeRequest",
        output_schema="HealthProbeResult",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="三态探针: liveness->alive / readiness->ready / healthz->healthy|degraded(实现已存在,需全系统注册)",
        route_target="telemetry",
    ),
    "CT-DLQ-001": Contract(
        contract_id="CT-DLQ-001",
        producer="全系统",
        consumer="Database",
        status="部分实现:DeadLetterQueue已完整实现(SQLite持久化/重试/过期清理/统计查询/attach_dlq_to_observer),需注册到全系统事件总线",
        ai_read_only_hint=AIReadOnlyHint.CAUTION_STUB,
        trigger="失败消息/事件入死信队列",
        input_schema="DeadLetterEntry",
        output_schema="DLQWriteResult",
        telemetry=TelemetryType.USE,
        telemetry_metrics=["utilization", "saturation", "error"],
        ai_prompt="失败事件 -> DLQ 持久化 -> 定期重试/告警(DLQ实现已存在438行,需接入全系统事件总线)",
        route_target="database",
    ),
    "CT-RECONCILE-001": Contract(
        contract_id="CT-RECONCILE-001",
        producer="全系统",
        consumer="Gate Engine",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="定期对账: 注册表 ↔ 代码 ↔ 蓝图",
        input_schema="ReconcileRequest",
        output_schema="ReconcileResult",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="对账扫描 -> 差异报告 -> 自动修复/告警",
        route_target="gate-engine",
    ),
    "CT-STARTUP-001": Contract(
        contract_id="CT-STARTUP-001",
        producer="Orchestrator",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="系统冷启动顺序编排",
        input_schema="StartupSequence",
        output_schema="StartupResult",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="冷启动序列: SYS-MASTER -> MOD-MASTER -> 12系统依序启动",
        route_target="orchestrator",
    ),
    "CT-TEARDOWN-001": Contract(
        contract_id="CT-TEARDOWN-001",
        producer="Orchestrator",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="系统安全关闭顺序编排",
        input_schema="TeardownSequence",
        output_schema="TeardownResult",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="安全关闭: 释放锁 -> 保存状态 -> 关闭连接 -> 确认零残留",
        route_target="orchestrator",
    ),
    "CT-SLO-001": Contract(
        contract_id="CT-SLO-001",
        producer="System Telemetry",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="SLI 采集与 SLO 告警阈值判定",
        input_schema="SLOMetrics",
        output_schema="SLOAlert",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="11 SLI 持续监控 -> SLO 突破 -> 记录事故 + 通知Owner",
        route_target="telemetry",
    ),
    "CT-BULKHEAD-001": Contract(
        contract_id="CT-BULKHEAD-001",
        producer="Gate Engine",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="资源隔离与故障域边界控制",
        input_schema="BulkheadConfig",
        output_schema="BulkheadStatus",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Bulkhead: 线程池隔离 -> 连接池隔离 -> 故障不扩散",
        route_target="gate-engine",
    ),
    "CT-WATCHDOG-001": Contract(
        contract_id="CT-WATCHDOG-001",
        producer="Gate Engine",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="系统僵死检测与自动重启",
        input_schema="WatchdogConfig",
        output_schema="WatchdogAction",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Watchdog: 心跳检测 -> 僵死判定 -> 自动重启/告警",
        route_target="gate-engine",
    ),
    "CT-BACKUP-001": Contract(
        contract_id="CT-BACKUP-001",
        producer="Database",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="定期备份 + 可恢复性验证",
        input_schema="BackupConfig",
        output_schema="BackupResult",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="备份: 全量+增量 -> 异地存储 -> 定期恢复演练",
        route_target="database",
    ),
    "CT-CONFIG-001": Contract(
        contract_id="CT-CONFIG-001",
        producer="Orchestrator",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="配置中心: 热加载 + 版本回滚",
        input_schema="ConfigChange",
        output_schema="ConfigResult",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="配置变更 -> 校验 -> 热加载 -> 失败自动回滚",
        route_target="orchestrator",
    ),
    "CT-FEATUREFLAG-001": Contract(
        contract_id="CT-FEATUREFLAG-001",
        producer="Orchestrator",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="Feature Flag 暗启动 + 灰度发布",
        input_schema="FeatureFlagToggle",
        output_schema="FlagResult",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Feature Flag: 暗启动 -> 渐进式放量 -> 异常自动关闭",
        route_target="orchestrator",
    ),
    "CT-SECRETS-001": Contract(
        contract_id="CT-SECRETS-001",
        producer="LLM Security Gateway",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="密钥生命周期管理: 生成/轮替/吊销",
        input_schema="SecretRotation",
        output_schema="SecretResult",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Secrets: 定期轮替 -> 泄露检测 -> 自动吊销",
        route_target="llm-security",
    ),
    "CT-KISS-001": Contract(
        contract_id="CT-KISS-001",
        producer="全系统",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="KISS 原则: 单文件 ≤ 500行 / 单函数 ≤ 50行",
        input_schema="KISSViolation",
        output_schema="KISSReport",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="KISS: 复杂度检查 -> 超标告警 -> 拒绝合并",
        route_target="gate-engine",
    ),
    "CT-DATA-LIFECYCLE-001": Contract(
        contract_id="CT-DATA-LIFECYCLE-001",
        producer="Database",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="Hot->Warm->Cool->Cold->Purge 五阶段自动流转",
        input_schema="DataTier",
        output_schema="LifecycleAction",
        telemetry=TelemetryType.USE,
        telemetry_metrics=["utilization", "saturation"],
        ai_prompt="数据生命周期: 逐级冷却 -> 自动清理 -> 合规保留",
        route_target="database",
    ),
    "CT-CHAOS-001": Contract(
        contract_id="CT-CHAOS-001",
        producer="Orchestrator",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="混沌工程: 故障注入 + 恢复验证",
        input_schema="ChaosExperiment",
        output_schema="ChaosResult",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Chaos: 周日非交易时段 -> 故障注入 -> MTTR 度量",
        route_target="orchestrator",
    ),
    "CT-MODEL-REGISTRY-001": Contract(
        contract_id="CT-MODEL-REGISTRY-001",
        producer="Orchestrator",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="模型注册: capability_declaration -> 模型版本追踪",
        input_schema="ModelDeclaration",
        output_schema="ModelRegistryEntry",
        telemetry=TelemetryType.USE,
        telemetry_metrics=["utilization", "saturation"],
        ai_prompt="模型注册: key-based 引用 -> 禁止硬编码模型名",
        route_target="orchestrator",
    ),
    "CT-DEPS-001": Contract(
        contract_id="CT-DEPS-001",
        producer="Gate Engine",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="依赖审计: SBOM + 已知CVE + 许可证合规",
        input_schema="DependencyCheck",
        output_schema="DependencyReport",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="依赖审计: 新增依赖 -> CVE扫描 -> 许可证检查 -> 拒绝高危",
        route_target="gate-engine",
    ),
    "CT-KNOWLEDGE-FRESHNESS-001": Contract(
        contract_id="CT-KNOWLEDGE-FRESHNESS-001",
        producer="Knowledge Base",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="KE 新鲜度检查: TTL 过期 -> 标记 stale -> 触发更新",
        input_schema="KEFreshnessCheck",
        output_schema="KEFreshnessReport",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="KB 新鲜度: 定期扫描 -> stale KE 标记 -> 通知Owner",
        route_target="knowledge-base",
    ),
    "CT-HOUSEKEEPING-001": Contract(
        contract_id="CT-HOUSEKEEPING-001",
        producer="Database",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="每日 03:00 AutoHousekeep: 清理过期数据/临时文件",
        input_schema="HousekeepSchedule",
        output_schema="HousekeepResult",
        telemetry=TelemetryType.USE,
        telemetry_metrics=["utilization", "saturation"],
        ai_prompt="AutoHousekeep: 每日03:00 -> 扫描临时文件 -> 清理过期数据",
        route_target="database",
    ),
    "CT-STABILITY-001": Contract(
        contract_id="CT-STABILITY-001",
        producer="Gate Engine",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="稳定性保障: Circuit Breaker + Retry + Backoff + Jitter",
        input_schema="StabilityConfig",
        output_schema="StabilityStatus",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="稳定性: CB 状态 -> 熔断/半开/恢复 -> 级联防护",
        route_target="gate-engine",
    ),
    "CT-CANARY-001": Contract(
        contract_id="CT-CANARY-001",
        producer="Orchestrator",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="Canary 部署: 小流量验证 -> 渐进式推广 -> 自动回滚",
        input_schema="CanaryDeploy",
        output_schema="CanaryResult",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Canary: 5%->25%->100% -> 异常自动回滚 -> 1h观察窗口",
        route_target="orchestrator",
    ),
    "CT-INCIDENT-001": Contract(
        contract_id="CT-INCIDENT-001",
        producer="Orchestrator",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="事故响应: L1-L5 分级 + Telemetry 告警联动",
        input_schema="IncidentReport",
        output_schema="IncidentResponse",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Incident: 自动分级 -> 升级矩阵 -> Postmortem -> 改进闭环",
        route_target="orchestrator",
    ),
    "CT-RACE-CONDITIONS-001": Contract(
        contract_id="CT-RACE-CONDITIONS-001",
        producer="Gate Engine",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="竞态条件检测: 文件锁 + 原子操作 + 冲突重试",
        input_schema="RaceConditionCheck",
        output_schema="RaceReport",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="竞态检测: 并发写入 -> 锁冲突 -> 退避重试 -> 告警",
        route_target="gate-engine",
    ),
    "CT-COST-BUDGET-001": Contract(
        contract_id="CT-COST-BUDGET-001",
        producer="Orchestrator",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="Token 成本预算: 任务前评估 -> 超预算拒绝",
        input_schema="CostBudgetRequest",
        output_schema="CostBudgetDecision",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="成本预算: 估算 Token -> 分层预算 -> 超预算 -> 升级审批",
        route_target="orchestrator",
    ),
    "CT-DISK-GUARD-001": Contract(
        contract_id="CT-DISK-GUARD-001",
        producer="Orchestrator",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="磁盘空间守卫: 剩余<10% -> 自动清理 -> 告警",
        input_schema="DiskGuardCheck",
        output_schema="DiskGuardAction",
        telemetry=TelemetryType.USE,
        telemetry_metrics=["utilization", "saturation"],
        ai_prompt="Disk Guard: 阈值告警 -> 自动清理 -> 紧急冻结写入",
        route_target="orchestrator",
    ),
    "CT-NETWORK-PARTITION-001": Contract(
        contract_id="CT-NETWORK-PARTITION-001",
        producer="Orchestrator",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="网络分区: 脑裂检测 -> 仲裁 -> 自动恢复",
        input_schema="PartitionEvent",
        output_schema="PartitionAction",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Network Partition: 心跳超时 -> 仲裁决策 -> 隔离/恢复",
        route_target="orchestrator",
    ),
    "CT-BENCH-001": Contract(
        contract_id="CT-BENCH-001",
        producer="Orchestrator",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="性能基准: SLO 回归检测 -> 退化>10% -> CI FAIL",
        input_schema="BenchmarkRun",
        output_schema="BenchmarkResult",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Benchmark: 每次变更后运行 -> SLA退化检测 -> 阻断合并",
        route_target="orchestrator",
    ),
    "CT-DEPLOY-001": Contract(
        contract_id="CT-DEPLOY-001",
        producer="Orchestrator",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="零停机滚动升级: 逐实例替换 + 健康检查",
        input_schema="DeployPlan",
        output_schema="DeployResult",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Rolling Upgrade: 逐实例 -> HealthCheck -> 失败自动回滚",
        route_target="orchestrator",
    ),
    "CT-SCHEMA-MIGRATE-001": Contract(
        contract_id="CT-SCHEMA-MIGRATE-001",
        producer="Database",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="DB Schema 演化: forward-compat 新增 / deprecation 删除",
        input_schema="SchemaMigration",
        output_schema="MigrationResult",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Schema Migrate: 向前兼容 -> 双写过渡 -> 旧字段废弃",
        route_target="database",
    ),
    "CT-DEGRADE-CASCADE-001": Contract(
        contract_id="CT-DEGRADE-CASCADE-001",
        producer="Gate Engine",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="级联降级预防: 依赖失败 -> 隔舱阻断 -> 局部降级",
        input_schema="DegradeEvent",
        output_schema="DegradeAction",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Degrade Cascade: 单点故障 -> 不扩散 -> 自动降级 -> 恢复回升",
        route_target="gate-engine",
    ),
    "CT-AUTONOMY-001": Contract(
        contract_id="CT-AUTONOMY-001",
        producer="Orchestrator",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="Owner 缺位自治: 分级决策树 × 离线时长 = 自动响应",
        input_schema="AutonomyContext",
        output_schema="AutonomyDecision",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Autonomy: Owner离线 -> 四级决策 -> 自动冻结/降级/继续",
        route_target="orchestrator",
    ),
    "CT-AGENT-QUALITY-001": Contract(
        contract_id="CT-AGENT-QUALITY-001",
        producer="Orchestrator",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="AI 施工质量闭环: WQA七维自检 + SPC统计过程控制",
        input_schema="AgentQualityCheck",
        output_schema="QualityReport",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Agent Quality: 每次施工后 -> WQA七维 -> SPC退化检测",
        route_target="orchestrator",
    ),
    "CT-PROMPT-VERSION-001": Contract(
        contract_id="CT-PROMPT-VERSION-001",
        producer="Orchestrator",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="Prompt 版本演化: 变更->回归测试->3+退化->回滚",
        input_schema="PromptVersionChange",
        output_schema="PromptVersionResult",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Prompt Version: 历史任务重放 -> 一致性验证 -> 回滚保护",
        route_target="orchestrator",
    ),
    "CT-SESSION-CONFLICT-001": Contract(
        contract_id="CT-SESSION-CONFLICT-001",
        producer="Orchestrator",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="并行 Session 冲突预防: 同CT-* -> WARN + 协调文件访问",
        input_schema="SessionConflict",
        output_schema="ConflictResolution",
        telemetry=TelemetryType.USE,
        telemetry_metrics=["utilization", "saturation"],
        ai_prompt="Session Conflict: 同契约并发 -> 协调 -> 只读共享/写互斥",
        route_target="orchestrator",
    ),
    "CT-LEAN-001": Contract(
        contract_id="CT-LEAN-001",
        producer="Orchestrator",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="Lean 扫描: 死代码检测 + 孤儿文件 + 未引用模块",
        input_schema="LeanScan",
        output_schema="LeanReport",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Lean: 定期扫描 -> 标记死代码 -> 安全删除 -> 减少熵",
        route_target="orchestrator",
    ),
    "CT-BLUEPRINT-HEALTH-001": Contract(
        contract_id="CT-BLUEPRINT-HEALTH-001",
        producer="Gate Engine",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="蓝图自健康诊断: 版本一致性 / 引用完整性 / 过期检测",
        input_schema="BlueprintHealthCheck",
        output_schema="BlueprintHealthReport",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Blueprint Health: 蓝图间交叉验证 -> 不一致告警 -> 自动修复建议",
        route_target="gate-engine",
    ),
    "CT-TRANSFER-001": Contract(
        contract_id="CT-TRANSFER-001",
        producer="Orchestrator",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="系统移交/迁移: 状态导出 -> 新环境导入 -> 验证",
        input_schema="TransferPlan",
        output_schema="TransferResult",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Transfer: 全状态导出 -> 幂等导入 -> 逐项验证",
        route_target="orchestrator",
    ),
    "CT-KE-QUALITY-001": Contract(
        contract_id="CT-KE-QUALITY-001",
        producer="Knowledge Base",
        consumer="全系统",
        status="规划",
        ai_read_only_hint=AIReadOnlyHint.DO_NOT_CALL,
        trigger="KE 质量评分: provenance 完整性 / 新鲜度 / 引用计数",
        input_schema="KEQualityCheck",
        output_schema="KEQualityReport",
        telemetry=TelemetryType.USE,
        telemetry_metrics=["utilization", "saturation"],
        ai_prompt="KE Quality: 评分 -> 低分标记 -> 触发改进/归档",
        route_target="knowledge-base",
    ),
    "CT-EVT-BUS-001": Contract(
        contract_id="CT-EVT-BUS-001",
        producer="EventBus",
        consumer="全系统",
        status="运行中",
        ai_read_only_hint=AIReadOnlyHint.CAUTION_STUB,
        trigger="EventBus.emit() 带 contract_id 参数时自动经 ContractBus Schema 校验",
        input_schema="EventPayload",
        output_schema="EventEmitResult",
        telemetry=TelemetryType.USE,
        telemetry_metrics=["rate", "error", "duration", "contract_rejected"],
        ai_prompt="EventBus+ContractBus 桥接: emit(contract_id=X) -> Schema校验 -> 通过入队/拒绝丢弃",
        route_target="shared",
    ),
    "CT-FLE-EVT-001": Contract(
        contract_id="CT-FLE-EVT-001",
        producer="FeedbackLoop",
        consumer="EventBus",
        status="运行中",
        ai_read_only_hint=AIReadOnlyHint.CAUTION_STUB,
        trigger="FLE 五阶段闭环关键事件发布到 EventBus",
        input_schema="FLEPipelineEvent",
        output_schema="EventEmitResult",
        telemetry=TelemetryType.USE,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="FLE->EventBus: fle.{phase} / fle.anomaly / fle.action 三类事件",
        route_target="feedback-loop",
    ),
    "CT-LLM-GW-001": Contract(
        contract_id="CT-LLM-GW-001",
        producer="LLMGateway",
        consumer="PipelineOrchestrator",
        status="运行中",
        ai_read_only_hint=AIReadOnlyHint.CAUTION_STUB,
        trigger="PipelineOrchestrator._call_model() 通过 LLMGateway 调用真实 LLM API",
        input_schema="LLMRequest",
        output_schema="LLMResponse",
        telemetry=TelemetryType.USE,
        telemetry_metrics=["rate", "error", "duration", "cost_usd"],
        ai_prompt="LLMGateway: DeepSeek/GLM/Claude/OpenAI 四provider + 降级链 + 成本追踪",
        route_target="agent-spec",
    ),
    "CT-VMS-BRIDGE-001": Contract(
        contract_id="CT-VMS-BRIDGE-001",
        producer="VMSMemoryBackend",
        consumer="UnifiedMemoryAPI",
        status="运行中",
        ai_read_only_hint=AIReadOnlyHint.CAUTION_STUB,
        trigger="UnifiedMemoryAPI 通过 VMSMemoryBackend 将操作路由到 VMS 8 Collection",
        input_schema="MemoryRecord",
        output_schema="VMSWriteResult",
        telemetry=TelemetryType.USE,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="VMS Bridge: topic->Collection 映射 + VMS不可用时降级到ChromaDB/InMemory",
        route_target="vector-memory",
    ),
    "CT-RB-GATE-001": Contract(
        contract_id="CT-RB-GATE-001",
        producer="Red-Blue Validator",
        consumer="Gate Engine",
        status="已实现:RedBlueValidator.run_adversarial_session() 调用 DefenseRunner 执行 17 gate 映射检查",
        ai_read_only_hint=AIReadOnlyHint.CAUTION_STUB,
        trigger="Red-Blue 每轮攻击后评估 bypass 结果，Gate Engine 判定通过/阻塞",
        input_schema="ScenarioResult",
        output_schema="DefenseResult",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Red-Blue 攻击 -> DefenseRunner GATE_MAP 17 门禁映射 -> Gate Engine 判定",
        route_target="gate-engine",
    ),
    "CT-RB-ESC-002": Contract(
        contract_id="CT-RB-ESC-002",
        producer="Red-Blue Validator",
        consumer="Escalation Protocol",
        status="已实现:BypassRecorder 3次绕过触发 escalation-engine.evaluate",
        ai_read_only_hint=AIReadOnlyHint.CAUTION_STUB,
        trigger="BypassRecorder 检测到 3 次绕过 -> EscalationEngine 升级",
        input_schema="BypassEntry",
        output_schema="EscalationDecision",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="3 bypasses -> EscalationEngine.evaluate(RuleCategory.SECURITY) -> 升级/降级/告警",
        route_target="escalation-engine",
    ),
    "CT-RB-KB-003": Contract(
        contract_id="CT-RB-KB-003",
        producer="Red-Blue Validator",
        consumer="Knowledge Base",
        status="已实现:ConstitutionEngine 新增 article 通过 kb.write 写入知识库",
        ai_read_only_hint=AIReadOnlyHint.CAUTION_STUB,
        trigger="Convergence 卡住 3 轮无改善 -> ConstitutionEngine.learn_from_bypass() 生成新 article -> kb.write",
        input_schema="BypassEntry",
        output_schema="KnowledgeEntry",
        telemetry=TelemetryType.RED,
        telemetry_metrics=["rate", "error", "duration"],
        ai_prompt="Convergence 停滞 -> ConstitutionEngine 自动学习 -> kb.write 写入新 article -> 防御自进化",
        route_target="knowledge-base",
    ),
}


class ContractCallResult(BaseModel):
    allowed: bool
    contract_id: str
    hint: AIReadOnlyHint
    message: str


class ContractRegistry:
    def get(self, contract_id: str) -> Contract | None:
        return CONTRACTS.get(contract_id)

    def list_all(self) -> list[Contract]:
        return list(CONTRACTS.values())

    def list_ids(self) -> list[str]:
        return list(CONTRACTS.keys())

    def check_ai_read_only(self, contract_id: str) -> ContractCallResult:
        contract = CONTRACTS.get(contract_id)
        if contract is None:
            return ContractCallResult(
                allowed=False,
                contract_id=contract_id,
                hint=AIReadOnlyHint.DO_NOT_CALL,
                message=f"契约 '{contract_id}' 不存在",
            )

        hint = contract.ai_read_only_hint
        if hint is AIReadOnlyHint.DO_NOT_CALL:
            return ContractCallResult(
                allowed=False,
                contract_id=contract_id,
                hint=hint,
                message=f"契约 '{contract_id}' 不可调用（DO_NOT_CALL）",
            )
        elif hint is AIReadOnlyHint.IMPL_REQUIRED:
            return ContractCallResult(
                allowed=False,
                contract_id=contract_id,
                hint=hint,
                message=f"契约 '{contract_id}' 需先完成实现（IMPL_REQUIRED）",
            )
        elif hint is AIReadOnlyHint.CAUTION_STUB:
            return ContractCallResult(
                allowed=True,
                contract_id=contract_id,
                hint=hint,
                message=f"契约 '{contract_id}' 仅部分功能可用（CAUTION_STUB）",
            )
        else:
            return ContractCallResult(
                allowed=True,
                contract_id=contract_id,
                hint=hint,
                message=f"契约 '{contract_id}' 可用",
            )

    def get_by_producer(self, producer: str) -> list[Contract]:
        return [c for c in CONTRACTS.values() if c.producer == producer]

    def get_by_consumer(self, consumer: str) -> list[Contract]:
        return [c for c in CONTRACTS.values() if c.consumer == consumer]

    def get_route_target(self, contract_id: str) -> str:
        contract = CONTRACTS.get(contract_id)
        if contract is None:
            return ""
        return contract.route_target

    def stats(self) -> dict[str, int | float]:
        total = len(CONTRACTS)
        by_hint: dict[str, int] = {}
        for c in CONTRACTS.values():
            hint_label = c.ai_read_only_hint.name if hasattr(c.ai_read_only_hint, "name") else str(c.ai_read_only_hint)
            by_hint[hint_label] = by_hint.get(hint_label, 0) + 1
        producers: set[str] = {c.producer for c in CONTRACTS.values()}
        consumers: set[str] = {c.consumer for c in CONTRACTS.values()}
        return {
            "total_contracts": total,
            "unique_producers": len(producers),
            "unique_consumers": len(consumers),
            "by_hint": by_hint,
            "readiness_pct": round(
                sum(
                    1
                    for c in CONTRACTS.values()
                    if hasattr(c.ai_read_only_hint, "name")
                    and c.ai_read_only_hint.name not in ("DO_NOT_CALL", "IMPL_REQUIRED")
                )
                / max(total, 1)
                * 100,
                1,
            ),
        }
