# [A_module] module_id=MOD-INT_shared_08 | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md
# [MODULE] zephyr.shared
# [INVARIANTS] pending_review
# [MODIFY-GUARD] no structural changes without owner approval
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [CONSUMERS]
# [ERROR_CONTRACT]
# [TESTS]
"""
ZephyrAlpha — shared/

跨层共享基础设施：契约（contracts）、工具（utils）、不可变核心（immutable_core）。

本包的内容**不绑定任何业务层**，所有 L00-L11 层均可 import。

实现状态图例（AI必读）：
  [STABLE]  = 生产就绪，可直接使用
  [BETA]    = 核心功能可用，边缘case待验证，使用时需包裹try/except
  [STUB]    = 仅有骨架（类型定义+占位），不可用于生产逻辑——导入不会报错但调用可能什么都不做
  [PLANNED] = 仅有接口声明，底层代码尚未撰写——导入可能 ImportError

SSoT 模块（所有路径/时间/解析/token 常量和函数的唯一真源）：
  - paths.py           → [STABLE] REPO_ROOT, DB_PATH, 路径常量
  - time_utils.py      → [STABLE] utc_now(), now_iso(), default_now()
  - frontmatter_utils.py → [STABLE] parse_frontmatter(), extract_body()
  - token_utils.py     → [STABLE] estimate_tokens()
  - errors.py          → [STABLE] ZephyrBaseError + 12 子类
  - constants.py       → [STABLE] 共享枚举集中 re-export
  - events/            → [BETA]  Observer 事件体 Pydantic V2 Schema
  - resilience/        → [STABLE] 重试/熔断/降级韧性基类（async_retry/CircuitBreaker/FallbackChain）
  - lifecycle/         → [STABLE] 模块生命周期钩子 + 健康检查（LifecycleAware/ModuleHealth）
  - flags.py           → [STABLE] Feature Flag 功能开关系统（FlagRegistry/global_flag_registry）
  - types.py           → [STABLE] 共享类型别名 NewType/Annotated
  - diff_utils.py      → [BETA] 统一 diff/patch 工具
  - file_utils.py      → [BETA] 安全文件操作——原子写/备份/rollback
  - config/            → [BETA] YAML 配置加载与 Pydantic 校验
  - health.py          → [BETA] 聚合健康检查
  - idempotency.py     → [STABLE] 幂等性记录与存储（IdempotencyStore/IdempotencyRecord）
  - limiter.py         → [STABLE] 速率限制（TokenBucketLimiter/async_limited）
  - lock.py            → [STABLE] 内存锁（MemoryLock/LockHandle）
  - metrics.py         → [STABLE] 指标注册表（MetricsRegistry/MetricSnapshot）
  - outbox.py          → [STABLE] 发件箱模式（OutboxStore/OutboxPublisher）
  - schema_registry.py → [STABLE] Schema版本注册表（SchemaRegistry/SchemaEntry）
  - secrets.py         → [BETA] 密钥管理（支持dotenv/env两种provider）
  - api_client.py      → [STABLE] HTTP客户端（AioHttpProvider/ApiClient/ApiCallMetrics）
  - cache.py           → [STABLE] 缓存（MemoryCache/CacheProvider/CacheStats）
  - migration.py       → [STABLE] 任务迁移框架（migrate_task/downgrade_task）
  - pagination.py      → [STABLE] 分页工具（OffsetPagination/CursorPagination）
  - serialization.py   → [BETA] 序列化/反序列化
  - testing.py         → [STABLE] 测试工厂函数
  - context.py         → [STABLE] 请求上下文
  - logging.py         → [STABLE] 日志系统
  - deprecation.py     → [STABLE] 废弃API机制
  - env.py             → [STABLE] 环境检测

跨层数据契约（CTR-001 ~ CTR-006，承重墙，禁止在模块内自造等价类型）：
  - contracts.market_data    → [STABLE] NormalizedMarketData（L00→L02）
  - contracts.factor_signal  → [STABLE] FactorSignal（L02→L03/L04/L05）
  - contracts.risk_limits    → [STABLE] RiskLimits（L04→L05）
  - contracts.order          → [STABLE] Order, OrderSide, OrderType, OrderStatus（L05→L06）
  - contracts.fill           → [STABLE] Fill（L06→L07）
  - contracts.position       → [STABLE] PositionSnapshot（L06/L07→L04/L11）
  - contracts.instrument     → [STABLE] Instrument + 6子类
  - contracts.money          → [STABLE] Money + 货币精度表
  - contracts.timestamp      → [STABLE] Timestamp + utcnow/ensure_utc
  - contracts.runtime_plane_tag → [STABLE] RuntimePlaneTag + HOT/WARM/COLD
  - contracts.enforcer       → [BETA]  契约强制执行（enforce_input/enforce_output）

参见：
  - cross_layer_contracts.yaml（CTR SSoT）
"""

MODULE_ID = "MOD-SHARED-001"

from zephyr.integration.shared_08._contracts import (
    COLD_PATH_LATENCY_BUDGET_MS,
    COLD_PATH_PARTIAL_ACTIVATED,
    HOT_PATH_ACTIVATED,
    HOT_PATH_LATENCY_BUDGET_MS,
    WARM_PATH_LATENCY_BUDGET_MS,
    ApprovalRequest,
    ContractViolationError,
    EnforcementMode,
    RollbackResult,
    RollbackStatus,
    RuntimePlane,
    Timestamp,
    ValidationResult,
    enforce,
    enforce_input,
    enforce_output,
    ensure_utc,
    utcnow,
)
from zephyr.integration.shared_08._infrastructure import (
    ENCODING_RULES,
    SECRET_INDICATOR_PATTERNS,
    AioHttpProvider,
    ApiCallError,
    ApiCallMetrics,
    ApiClient,
    ApiClientConfig,
    ApiResponse,
    AtomicWriteError,
    CacheError,
    CacheProvider,
    CacheStats,
    CostRecord,
    DecisionRecord,
    DotEnvSecretProvider,
    EnvSecretProvider,
    ErrorRecord,
    HttpMethod,
    HttpProvider,
    MemoryCache,
    OutcomeRecord,
    PatchConflictError,
    PromptRecord,
    SecretProvider,
    SecretsError,
    SerializationError,
    SerializationFormat,
    SessionAuditTrail,
    SessionRecord,
    ToolCallRecord,
    apply_patch,
    atomic_write,
    backup_and_rollback,
    backup_file,
    cache_key,
    compute_diff,
    compute_file_diff,
    deserialize_datetime,
    deserialize_decimal,
    from_dict,
    from_json,
    restore_backup,
    safe_read,
    sanitize_secret,
    serialize_datetime,
    serialize_decimal,
    similarity_ratio,
    to_dict,
    to_json,
    try_apply_patch,
)
from zephyr.integration.shared_08._version_and_types import (
    DB_PATH,
    DEFAULT_CONTEXT_TOKEN_BUDGET,
    MIN_COMPATIBLE_SHARED_VERSION,
    MOCKED_TIME,
    REPO_ROOT,
    AbsPath,
    AgentId,
    BlueprintVersion,
    ContractId,
    DocumentId,
    Env,
    ExecutionModel,
    FilePath,
    FingerprintHash,
    MetricName,
    ModuleId,
    Priority,
    SafetyLevel,
    SessionId,
    SSoT_Key,
    Task,
    TaskId,
    TaskNamespace,
    TaskStatus,
    TokenCount,
    VersionMismatchError,
    __version__,
    __version_info__,
    check_shared_version,
    current_env,
    estimate_tokens,
    format_iso,
    freeze_time,
    is_debug,
    is_dev,
    is_prod,
    is_staging,
    is_test,
    normalize_execution_model,
    now_utc,
    parse_iso,
    seconds_since,
    seconds_until,
    version_compatible,
    version_eq,
    version_gt,
    version_gte,
    version_lt,
    version_lte,
    version_major,
    version_minor,
    version_patch,
)


# Lazy imports to break circular: loader → shared_08 → _infrastructure → loader
def __getattr__(name):
    if name in ("ConfigLoadError", "load_yaml_config", "load_yaml_config_validated"):
        from zephyr.shared.config import loader as _loader

        return getattr(_loader, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


from zephyr.integration.shared_08._observability import (
    EVENT_PAYLOAD_MAP,
    AggregateHealth,
    ConfigError,
    ContextError,
    ContractError,
    DataError,
    DeadLetter,
    DeadLetterQueue,
    FeedbackError,
    FileEventPayload,
    GateError,
    HealthStatus,
    HealthSummary,
    IOError,
    LifecycleAware,
    LifecycleManager,
    LifecycleState,
    ManualEventPayload,
    MetricEventPayload,
    MetricSnapshot,
    MetricsRegistry,
    MetricType,
    ModuleHealth,
    PipelineError,
    RequestContext,
    SecurityError,
    TaskError,
    TaskEventPayload,
    TimeEventPayload,
    TraceContext,
    UnimplementedError,
    ValidationError,
    ZephyrBaseError,
    ZephyrLogger,
    attach_dlq_to_observer,
    collect_health,
    configure_root_logger,
    current_context,
    get_logger,
    get_registry,
    get_request_id,
    set_context,
    set_request_id,
    trace_id_var,
)
from zephyr.integration.shared_08._patterns import (
    MIGRATIONS,
    CircuitBreaker,
    CircuitOpenError,
    CircuitState,
    CursorPage,
    CursorPagination,
    DeprecatedAPIError,
    DeprecationMode,
    FallbackChain,
    FeatureFlag,
    FlagNotFoundError,
    FlagRegistry,
    FlagState,
    IdempotencyError,
    IdempotencyRecord,
    IdempotencyStatus,
    IdempotencyStore,
    LockError,
    LockHandle,
    MemoryLock,
    MemoryOutboxStore,
    MigrationError,
    OffsetPagination,
    OutboxEntry,
    OutboxError,
    OutboxPublisher,
    OutboxStatus,
    OutboxStore,
    Page,
    RateLimitError,
    RateLimiterStats,
    RetryConfig,
    RetryExhaustedError,
    SchemaEntry,
    SchemaRegistry,
    SchemaRegistryError,
    SchemaVersion,
    TokenBucketLimiter,
    async_limited,
    async_retry,
    deprecated,
    downgrade_task,
    fallback,
    get_deprecation_mode,
    get_schema_registry,
    global_flag_registry,
    latest_schema_version,
    make_completed_task,
    make_p0_task,
    make_valid_audit_report,
    make_valid_failure_pattern,
    make_valid_handoff_package,
    make_valid_knowledge_entry,
    make_valid_task,
    migrate_task,
    paginate,
    paginate_cursor,
    set_deprecation_mode,
)
from zephyr.integration.shared_08.agent_identity_impl import AgentIdentity
from zephyr.integration.shared_08.contract_versions import ContractRegistry

__all__ = [
    "COLD_PATH_LATENCY_BUDGET_MS",
    "COLD_PATH_PARTIAL_ACTIVATED",
    "DB_PATH",
    "DEFAULT_CONTEXT_TOKEN_BUDGET",
    "ENCODING_RULES",
    "EVENT_PAYLOAD_MAP",
    "HOT_PATH_ACTIVATED",
    "HOT_PATH_LATENCY_BUDGET_MS",
    "MIGRATIONS",
    "MIN_COMPATIBLE_SHARED_VERSION",
    "MOCKED_TIME",
    "REPO_ROOT",
    "SECRET_INDICATOR_PATTERNS",
    "WARM_PATH_LATENCY_BUDGET_MS",
    "AbsPath",
    "AgentId",
    "AggregateHealth",
    "AioHttpProvider",
    "ApiCallError",
    "ApiCallMetrics",
    "ApiClient",
    "ApiClientConfig",
    "ApiResponse",
    "ApprovalRequest",
    "AtomicWriteError",
    "BlueprintVersion",
    "CacheError",
    "CacheProvider",
    "CacheStats",
    "CircuitBreaker",
    "CircuitOpenError",
    "CircuitState",
    "ConfigError",
    "ConfigLoadError",
    "ContextError",
    "ContractError",
    "ContractId",
    "ContractViolationError",
    "CostRecord",
    "CursorPage",
    "CursorPagination",
    "DataError",
    "DeadLetter",
    "DeadLetterQueue",
    "DecisionRecord",
    "DeprecatedAPIError",
    "DeprecationMode",
    "DocumentId",
    "DotEnvSecretProvider",
    "EnforcementMode",
    "Env",
    "EnvSecretProvider",
    "ErrorRecord",
    "ExecutionModel",
    "FallbackChain",
    "FeatureFlag",
    "FeedbackError",
    "FileEventPayload",
    "FilePath",
    "FingerprintHash",
    "FlagNotFoundError",
    "FlagRegistry",
    "FlagState",
    "GateError",
    "HealthStatus",
    "HealthSummary",
    "HttpMethod",
    "HttpProvider",
    "IOError",
    "IdempotencyError",
    "IdempotencyRecord",
    "IdempotencyStatus",
    "IdempotencyStore",
    "LifecycleAware",
    "LifecycleManager",
    "LifecycleState",
    "LockError",
    "LockHandle",
    "ManualEventPayload",
    "MemoryCache",
    "MemoryLock",
    "MemoryOutboxStore",
    "MetricEventPayload",
    "MetricName",
    "MetricSnapshot",
    "MetricType",
    "MetricsRegistry",
    "MigrationError",
    "ModuleHealth",
    "ModuleId",
    "OffsetPagination",
    "OutboxEntry",
    "OutboxError",
    "OutboxPublisher",
    "OutboxStatus",
    "OutboxStore",
    "OutcomeRecord",
    "Page",
    "PatchConflictError",
    "PipelineError",
    "Priority",
    "PromptRecord",
    "RateLimitError",
    "RateLimiterStats",
    "RequestContext",
    "RetryConfig",
    "RetryExhaustedError",
    "RollbackResult",
    "RollbackStatus",
    "RuntimePlane",
    "SSoT_Key",
    "SafetyLevel",
    "SchemaEntry",
    "SchemaRegistry",
    "SchemaRegistryError",
    "SchemaVersion",
    "SecretProvider",
    "SecretsError",
    "SecurityError",
    "SerializationError",
    "SerializationFormat",
    "SessionAuditTrail",
    "SessionId",
    "SessionRecord",
    "Task",
    "TaskError",
    "TaskEventPayload",
    "TaskId",
    "TaskNamespace",
    "TaskStatus",
    "TimeEventPayload",
    "Timestamp",
    "TokenBucketLimiter",
    "TokenCount",
    "ToolCallRecord",
    "TraceContext",
    "UnimplementedError",
    "ValidationError",
    "ValidationResult",
    "VersionMismatchError",
    "ZephyrBaseError",
    "ZephyrLogger",
    "__version__",
    "__version_info__",
    "_contracts",
    "_infrastructure",
    "_observability",
    "_patterns",
    "_version_and_types",
    "agent_identity_impl",
    "api_client",
    "api_index",
    "apply_patch",
    "async_limited",
    "async_retry",
    "atomic_write",
    "attach_dlq_to_observer",
    "backup_and_rollback",
    "backup_file",
    "cache",
    "cache_key",
    "capability",
    "check_shared_version",
    "collect_health",
    "compute_diff",
    "compute_file_diff",
    "configure_root_logger",
    "constants",
    "content_fingerprint",
    "context",
    "contract_bus",
    "contract_enforcer",
    "contract_tester",
    "contract_versions",
    "current_context",
    "current_env",
    "deprecated",
    "deprecation",
    "deserialize_datetime",
    "deserialize_decimal",
    "diff_utils",
    "downgrade_task",
    "durable_execution",
    "enforce",
    "enforce_input",
    "enforce_output",
    "ensure_utc",
    "env",
    "errors",
    "estimate_tokens",
    "evals",
    "event_bus",
    "fallback",
    "file_utils",
    "flags",
    "format_hook",
    "format_iso",
    "freeze_time",
    "from_dict",
    "from_json",
    "frontmatter_utils",
    "get_deprecation_mode",
    "get_logger",
    "get_registry",
    "get_request_id",
    "get_schema_registry",
    "global_flag_registry",
    "health",
    "idempotency",
    "is_debug",
    "is_dev",
    "is_prod",
    "is_staging",
    "is_test",
    "kg_interface",
    "latest_schema_version",
    "limiter",
    "load_yaml_config",
    "load_yaml_config_validated",
    "lock",
    "logging",
    "make_completed_task",
    "make_p0_task",
    "make_valid_audit_report",
    "make_valid_failure_pattern",
    "make_valid_handoff_package",
    "make_valid_knowledge_entry",
    "make_valid_task",
    "metrics",
    "migrate_task",
    "migration",
    "normalize_execution_model",
    "now_utc",
    "observer",
    "outbox",
    "paginate",
    "paginate_cursor",
    "pagination",
    "parse_iso",
    "paths",
    "restore_backup",
    "safe_read",
    "sanitize_secret",
    "schema_registry",
    "schemas",
    "seconds_since",
    "seconds_until",
    "secrets",
    "serialization",
    "serialize_datetime",
    "serialize_decimal",
    "session_audit",
    "set_context",
    "set_deprecation_mode",
    "set_request_id",
    "similarity_ratio",
    "ssot_guard",
    "state_machine",
    "testing",
    "time_utils",
    "timestamp_utils",
    "to_dict",
    "to_json",
    "token_utils",
    "trace_id_var",
    "tracing",
    "try_apply_patch",
    "types",
    "utcnow",
    "version_compatible",
    "version_eq",
    "version_gt",
    "version_gte",
    "version_lt",
    "version_lte",
    "version_major",
    "version_minor",
    "version_negotiation",
    "version_patch",
]

_SUBMODULES = [
    "api_index",
    "api_client",
    "cache",
    "capability",
    "constants",
    "content_fingerprint",
    "contract_bus",
    "contract_tester",
    "deprecation",
    "diff_utils",
    "durable_execution",
    "env",
    "errors",
    "event_bus",
    "evals",
    "file_utils",
    "flags",
    "frontmatter_utils",
    "health",
    "idempotency",
    "kg_interface",
    "limiter",
    "lock",
    "logging",
    "metrics",
    "migration",
    "observer",
    "outbox",
    "pagination",
    "paths",
    "schema_registry",
    "schemas",
    "secrets",
    "serialization",
    "session_audit",
    "ssot_guard",
    "state_machine",
    "testing",
    "time_utils",
    "tracing",
    "types",
    "version_negotiation",
]

_LOCAL_ONLY_SUBMODULES = {"kg_interface", "durable_execution", "evals", "version_negotiation"}


def __getattr__(name):
    if name in _SUBMODULES:
        import importlib

        if name in _LOCAL_ONLY_SUBMODULES:
            return importlib.import_module(f"zephyr.integration.shared_08.{name}")
        return importlib.import_module(f"zephyr.shared.{name}")
    raise AttributeError(f"module 'zephyr.integration.shared_08' has no attribute {name!r}")


__all__.append("TimestampUtils")

__all__.append("ContractRegistry")
__all__.append("contract_versions")
__all__.append("ContractEnforcer")
__all__.append("AgentIdentity")
__all__.append("agent_identity_impl")
