# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md
# [MODULE] zephyr.integration.shared_08.api_client
# [DOMAIN] D-INTEGRATION
# [DEPENDENCIES] zephyr.integration.shared.api_03.api_client
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-INT_api_client | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] task_bound

"""
api_client.py —— Re-export wrapper → canonical: zephyr.integration.shared.api_03.api_client

Backward-compatible top-level alias. Canonical implementation at api/api_client.py.
Edit api/api_client.py to modify logic — do NOT edit this file.
"""

from zephyr.integration.shared.api_03.api_client import *  # noqa: F403
