# [A_module] module_id=MOD-INT_api_index | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md

# [MODULE] zephyr.integration.shared_08.api_index

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
API_INDEX.py —— Re-export wrapper → canonical: zephyr.integration.shared.api_03.api_index

Backward-compatible top-level alias. Canonical implementation at api/api_index.py.
Edit api/api_index.py to modify logic — do NOT edit this file.
"""

from zephyr.integration.shared.api_03.api_index import *  # noqa: F403
