# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md
# [MODULE] zephyr.integration.shared_08.blueprint_scorer
# [DOMAIN] D-INTEGRATION
# [DEPENDENCIES] zephyr.integration.shared_08.__init__
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-INT_blueprint_scorer | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable

"""
blueprint_scorer.py — Re-export wrapper → canonical: zephyr.trading.orchestrator.blueprint_scorer

Backward-compatible top-level alias. Canonical implementation at orchestrator/blueprint_scorer.py.
Edit orchestrator/blueprint_scorer.py to modify logic — do NOT edit this file.
"""

import importlib as _il

_mod = _il.import_module("zephyr.trading.orchestrator.blueprint_scorer")
for _n in getattr(_mod, "__all__", [n for n in dir(_mod) if not n.startswith("_")]):
    globals()[_n] = getattr(_mod, _n)
del _il, _mod, _n
