# [A_module] module_id=MOD-INT_deprecation | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md

# [MODULE] zephyr.integration.shared_08.deprecation

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
deprecation.py —— Re-export wrapper → canonical: zephyr.integration.shared_08.foundation.deprecation

Backward-compatible top-level alias. Canonical implementation at foundation/deprecation.py.
Edit foundation/deprecation.py to modify logic — do NOT edit this file.
"""

from zephyr.integration.shared_08.foundation.deprecation import *  # noqa: F403
