# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md
# [MODULE] zephyr.integration.shared_08.diff_utils
# [DOMAIN] D-INTEGRATION
# [DEPENDENCIES] zephyr.integration.shared_08.utils.diff_utils
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] production
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-INT_diff_utils | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable

"""
diff_utils.py —— Re-export wrapper → canonical: zephyr.integration.shared_08.utils.diff_utils

Backward-compatible top-level alias. Canonical implementation at utils/diff_utils.py.
Edit utils/diff_utils.py to modify logic — do NOT edit this file.
"""

from zephyr.integration.shared_08.utils.diff_utils import *  # noqa: F403
