# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md
# [MODULE] zephyr.integration.shared_08.env
# [DOMAIN] D-INTEGRATION
# [DEPENDENCIES] zephyr.integration.shared_08.foundation.env
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-INT_env | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable

"""
env.py —— Re-export wrapper → canonical: zephyr.integration.shared_08.foundation.env

Backward-compatible top-level alias. Canonical implementation at foundation/env.py.
Edit foundation/env.py to modify logic — do NOT edit this file.
"""

from zephyr.integration.shared_08.foundation.env import *  # noqa: F403
