# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md
# [MODULE] zephyr.integration.shared_08.flags
# [DOMAIN] D-INTEGRATION
# [DEPENDENCIES] zephyr.integration.shared_08.foundation.flags
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] production
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-INT_flags | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] task_bound

"""
flags.py —— Re-export wrapper → canonical: zephyr.integration.shared_08.foundation.flags

Backward-compatible top-level alias. Canonical implementation at foundation/flags.py.
Edit foundation/flags.py to modify logic — do NOT edit this file.
"""

from zephyr.integration.shared_08.foundation.flags import *  # noqa: F403
