# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md
# [MODULE] zephyr.integration.shared_08.idempotency
# [DOMAIN] D_INTEGRATION
# [DEPENDENCIES] zephyr.shared.infra_06.idempotency
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-INT_idempotency | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] task_bound

"""
idempotency.py —— Re-export wrapper → canonical: zephyr.infrastructure.shared_services.infra_06.idempotency

Backward-compatible top-level alias. Canonical implementation at infra/idempotency.py.
Edit infra/idempotency.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.infra_06.idempotency import *  # noqa: F403
