# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md
# [MODULE] zephyr.integration.shared_08.limiter
# [DOMAIN] D-INTEGRATION
# [DEPENDENCIES] zephyr.shared.shared_services.infra_06.limiter
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] production
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-INT_limiter | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable

"""
limiter.py —— Re-export wrapper → canonical: zephyr.infrastructure.shared_services.infra_06.limiter

Backward-compatible top-level alias. Canonical implementation at infra/limiter.py.
Edit infra/limiter.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.shared_services.infra_06.limiter import *  # noqa: F403
