# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md
# [MODULE] zephyr.integration.shared_08.observer
# [DOMAIN] D-INTEGRATION
# [DEPENDENCIES] zephyr.shared.infra_06.observer
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] frozen
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-INT_observer | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] task_bound

"""
observer.py —— Re-export wrapper → canonical: zephyr.infrastructure.shared_services.infra_06.observer

Backward-compatible top-level alias. Canonical implementation at infra/observer.py.
Edit infra/observer.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.infra_06.observer import *  # noqa: F403
