# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md
# [MODULE] zephyr.integration.shared_08.pagination
# [DOMAIN] D_INTEGRATION
# [DEPENDENCIES] zephyr.integration.shared_08.utils.pagination
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] production
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-INT_pagination | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] task_bound

"""
pagination.py —— Re-export wrapper → canonical: zephyr.integration.shared_08.utils.pagination

Backward-compatible top-level alias. Canonical implementation at utils/pagination.py.
Edit utils/pagination.py to modify logic — do NOT edit this file.
"""

from zephyr.integration.shared_08.utils.pagination import *  # noqa: F403
