# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md
# [MODULE] zephyr.integration.shared_08.paths
# [DOMAIN] D-INTEGRATION
# [DEPENDENCIES] zephyr.integration.shared_08.io.paths
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] production
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-INT_paths | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] task_bound

"""
paths.py —— Re-export wrapper → canonical: zephyr.integration.shared_08.io.paths

Backward-compatible top-level alias. Canonical implementation at io/paths.py.
Edit io/paths.py to modify logic — do NOT edit this file.
"""

from zephyr.integration.shared_08.io.paths import *  # noqa: F403
