# [A_module] module_id=MOD-INT_schema_registry | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md

# [MODULE] zephyr.integration.shared_08.schema_registry

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
schema_registry.py —— Re-export wrapper → canonical: zephyr.integration.shared.schema.schema_registry

Backward-compatible top-level alias. Canonical implementation at schema/schema_registry.py.
Edit schema/schema_registry.py to modify logic — do NOT edit this file.
"""

from zephyr.integration.shared.schema.schema_registry import *  # noqa: F403
