# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md
# [MODULE] zephyr.integration.shared_08.secrets
# [DOMAIN] D-INTEGRATION
# [DEPENDENCIES] zephyr.integration.shared_08.security.secrets
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] prototype
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-INT_secrets | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable

"""
secrets.py —— Re-export wrapper → canonical: zephyr.integration.shared_08.security.secrets

Backward-compatible top-level alias. Canonical implementation at security/secrets.py.
Edit security/secrets.py to modify logic — do NOT edit this file.
"""

from zephyr.integration.shared_08.security.secrets import *  # noqa: F403
