# [A_module] module_id=MOD-INT_ssot_guard | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md

# [MODULE] zephyr.integration.shared_08.ssot_guard

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] M

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
ssot_guard.py —— Re-export wrapper → canonical: zephyr.integration.shared_08.security.ssot_guard

Backward-compatible top-level alias. Canonical implementation at security/ssot_guard.py.
Edit security/ssot_guard.py to modify logic — do NOT edit this file.
"""


from zephyr.integration.shared_08.security.ssot_guard import *  # noqa: F401, F403
