# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md
# [MODULE] zephyr.integration.shared_08.time_utils
# [DOMAIN] D_INTEGRATION
# [DEPENDENCIES] zephyr.integration.shared_08.utils.time_utils
# [CONSUMERS]
# [STARTUP] imported
# [MATURITY] production
# [INVARIANTS] none
# [MODIFY-GUARD] none
# [STABILITY] evolving
# [SAFETY] L
# [AI_AUTONOMY] ai_modifiable
# [ERROR_CONTRACT]
# [TESTS]
# [A_module] module_id=MOD-INT_time_utils | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [TTL] task_bound

"""
time_utils.py —— Re-export wrapper → canonical: zephyr.integration.shared_08.utils.time_utils

Backward-compatible top-level alias. Canonical implementation at utils/time_utils.py.
Edit utils/time_utils.py to modify logic — do NOT edit this file.
"""

from datetime import UTC

from zephyr.integration.shared_08.utils.time_utils import *  # noqa: F403


def default_now():
    from datetime import datetime

    return datetime.now(UTC)
