# [A_module] module_id=MOD-INT_tracing | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md

# [MODULE] zephyr.integration.shared_08.tracing

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
tracing.py —— Re-export wrapper → canonical: zephyr.infrastructure.shared_services.observability_02.tracing

Backward-compatible top-level alias. Canonical implementation at observability/tracing.py.
Edit observability/tracing.py to modify logic — do NOT edit this file.
"""

from zephyr.shared.shared_services.observability_02.tracing import *  # noqa: F403
