# [A_module] module_id=MOD-INT_types | layer=module | stability=evolving | safety=L | ai_autonomy=ai_modifiable
# [BLUEPRINT] MOD-INF-016 | docs/03_modules/_cross_layer/shared-core/blueprint.md

# [MODULE] zephyr.integration.shared_08.types

# [INVARIANTS] none

# [MODIFY-GUARD] none

# [CONSUMERS]

# [STABILITY] evolving

# [SAFETY] L

# [AI_AUTONOMY] ai_modifiable

# [ERROR_CONTRACT]

# [TESTS]

"""
types.py —— Re-export wrapper → canonical: zephyr.integration.shared_08.foundation.types

Backward-compatible top-level alias. Canonical implementation at foundation/types.py.
Edit foundation/types.py to modify logic — do NOT edit this file.
"""


from zephyr.integration.shared_08.foundation.types import *  # noqa: F401, F403
from zephyr.integration.shared_08.foundation.types import __all__  # noqa: F401
